src/java/picard/cmdline/CommandLineParser.java, src/tests/java/picard/cmdline/CommandLineParserTest.java
Added a test and some java reflection to set all hidden fields to the child value.
=> Fix overridable option fields.

src/java/picard/sam/AddOrReplaceReadGroups.java, src/java/picard/sam/ViewSam.java, src/java/picard/sam/markduplicates/MarkDuplicates.java, src/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigar.java, src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java, src/tests/java/picard/sam/ViewSamTest.java, src/tests/java/picard/sam/markduplicates/MarkDuplicatesTest.java
This first batch includes AddOrReplaceReadGroups, MarkDuplicates and ViewSam.
=> Allow tools to work with GA4GH resources specified via urls.

.gitignore, .travis.yml, build.sbt, build.xml, project/plugins.sbt, src/tests/java/picard/illumina/CheckIlluminaDirectoryTest.java, src/tests/resources/testng.xml
First pass picard sbt build.
Change git url to https on the fly
=> use ssh url for htsjdk git.

src/java/picard/util/IntervalListTools.java
Added ability to taken an interval list and split into finer intervals based on band multiples in order to allow for finer granularity of scattering.
=> Add ability to split interval_list file on band multiples

src/java/picard/analysis/CollectGcBiasMetrics.java
Changed CollectGcBiasMetrics to work as a SinglePassSam
=> Kb gcbias take2

src/java/picard/util/IntervalListScatterer.java, src/java/picard/util/IntervalListTools.java
Modified IntervalListTools so that if scattering we do the sorting and uniquification up front (and not in the scatter method).
This was important for BREAK_BANDS_AT_MULTIPLES_OF where the unique in scatter was re-merging broken adjacent intervals.
Also made interval list file in scattered directories be NOT broken up into multiples.
=> Modified IntervalListTools so that if scattering we do the sorting and uniquification up front

src/java/picard/analysis/CollectMultipleMetrics.java, src/tests/java/picard/analysis/CollectMultipleMetricsTest.java
to @tfenne 's PR #194
The difference is that the change is done in collectMultipleMetrics and tests are included for 
greater good!
Comments welcome: @jacarey @ktibbett
=> I propose this as an alternative

src/java/picard/vcf/GenotypeConcordance.java
Modify GenotypeConcordance to explicitly require that the VCF files be indexed if an interval file is specified.  Otherwise it would blow up, somewhat more obscurely, for lack of an index file.
=> Modify GenotypeConcordance to explicitly require that the VCF files be indexed if an interval file is specified

src/java/picard/analysis/CollectGcBiasMetrics.java
Resolves #212 though it would still be good if a test be added, perhaps using user's supplied header.
=> fix for bug in collectGcBiasMetrics

src/java/picard/analysis/directed/TargetMetricsCollector.java, src/java/picard/util/MathUtil.java
* collect the normalized minimum coverage in each target
=> A tiny addition to the per-target metrics collection

Dockerfile
Build an image:
docker build -t picard .
Run a tool
docker run picard IntervalListTools
=> Added a dockerfile to picard

src/java/picard/util/IntervalListScatterer.java
- Fixed a small bug in IntervalListTool where in some cases bases were not accounted for in the total count (this can lead to non-uniform intervalLists in the scatter)
- Removed an erroneous Exception that was thrown when the intervals were not uniformly enough sized. We cannot guarantee that they will be uniformly sized...
- Fixed bug that was causing the Last intervalList to be double the size of the rest.
=> fixed a small bug in IntervalListTool and remove spurious exception

src/java/picard/vcf/GenotypeConcordance.java
(I may have messed up the git merging on this one...)
=> Eb genotype concordance should read gzipped files

src/java/picard/util/MathUtil.java, src/java/picard/util/TestNGUtil.java, src/tests/java/picard/util/MathUtilTest.java
- added a utility function to get the log of a list of doubles
- exposed TestNGUtil in picard-public
- added tests for new functionality
=> added a utility function to get the log of a list of doubles.

build.xml
Added this CLP to the package-commands build target in build.xml
=> Add GatherVcfs CLP to autogenerated online documentation

src/scripts/picard/analysis/insertSizeHistogram.R
they are also now dashed.
@yfarjoun or @tfenne
=> updating the colors of the cumulative lines in the insert size plots;

src/java/picard/analysis/GcBiasMetricsCollector.java, src/java/picard/analysis/GcBiasSummaryMetrics.java, src/tests/java/picard/analysis/CollectGcBiasMetricsTest.java, src/tests/java/picard/analysis/CollectMultipleMetricsTest.java
Normalized coverage over quintiles of GC content.
=> Updating GCBias to include new metrics

src/java/picard/cmdline/CommandLineParser.java, src/java/picard/cmdline/Option.java, src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
Stylistic modifications and jar removal done as requested. I did not know how to squash down to a single commit so I create a new pull request and referenced the original one in the title (#328). I hope this is is ok.
=> NEW : Added new printOrder property in Option to control print order is usage #328

src/tests/java/picard/analysis/CollectQualityYieldMetricsTest.java
@tfenne, basic test to compare to for your changes, mind taking a quick look so we can merge it in and get your PR all set?
=> Kb collect quality yield test

src/java/picard/analysis/AlignmentSummaryMetricsCollector.java, src/java/picard/analysis/directed/RnaSeqMetricsCollector.java
`AlignmentSummaryMetrics`, `RnaSeqMetrics`, and `QualityYieldMetrics`.
Note that the same update for `HsMetrics`, `TargetedMetrics`, and `TargetedPcrMetrics` is included in the following pull request: https://github.com/broadinstitute/picard/pull/332
=> Supplementary reads should contribute to metrics that count bases in

src/java/picard/sam/MergeSamFiles.java
The following pull request add an optional parameter INTERVALS to merge the sorted+index bam files in a defined list of regions.
```java
@Option(shortName = "INTERVALS"...)
public File INTERVALS = null;
```
if **INTERVALS** is defined, it checks that the bam is sorted+index, fills a map **samReaderToIterator**   `Map<SamReader, CloseableIterator<SAMRecord> >`   ; The values of the map are used to create a MergingSamRecordIterator.
```java
if( intervalList == null) {
iterator = new MergingSamRecordIterator(headerMerger, readers, mergingSamRecordIteratorAssumeSorted);
}
else {
iterator = new MergingSamRecordIterator(headerMerger, samReaderToIterator, true);
}
```
=> merge sam file with interval

src/java/picard/fingerprint/CheckFingerprint.java
Yossi asked us to do this for RQC in a different PR.
=> Pull out the metrics suffixes to a static constant.

README.md
Addresses https://github.com/broadinstitute/picard/issues/359
=> Update java version requirement

src/java/picard/fingerprint/CheckFingerprint.java
individually.  The old behavior is still the default.
@eitanbanks @yfarjoun 
Address #380.
=> Detail and summary metrics for CheckFingerprint can be specified

src/java/picard/illumina/ExtractIlluminaBarcodes.java
others (it is really useful).
@tfenne
=> moving metrics tallying to a public static method, so it can be used by

src/java/picard/fingerprint/CheckFingerprint.java
Change fingerprint output file instantiation and check if is writeable as opposed to readable
=> Change fingerprint output file instantiation and check if is writeable as opposed to readable

src/java/picard/analysis/TheoreticalSensitivity.java
This should not affect the result (as one should have very high _theoretical_ sensitivity at that depth) but it will affect performance (as in, it will improve it).
- White-space changes
@kbergin could you take a look?
=> Hard cap the depth of the het-Sensitivity calculation at 1000. 

src/java/picard/analysis/AlignmentSummaryMetricsCollector.java, src/java/picard/analysis/CollectAlignmentSummaryMetrics.java
Read pair orientation and SA tag are now considered when detecting
chimeras.
=> Improving how chimeras are detected in CollectAlignmentSummaryMetrics.

src/tests/java/picard/analysis/directed/CollectHsMetricsTest.java
file.  Also fixed up the expected values for the test, and commented
about what it is testing.
=> runCollectTargetedMetricsTest was not writing to the correct output

src/java/picard/illumina/parser/ReadStructure.java
documentation
@yfarjoun @tfenne
=> adding in molecular barcode to the read structure parameter

src/java/picard/sam/markduplicates/util/AbstractOpticalDuplicateFinderCommandLineProgram.java
@tfenne would you agree with this change to the argument doc? I felt that what was there before was not accurate enough.
=> modified usage doc for OPTICAL_DUPLICATE_PIXEL_DISTANCE

src/java/picard/analysis/GcBiasMetricsCollector.java, src/java/picard/illumina/parser/BarcodeParser.java, src/java/picard/illumina/parser/FourChannelIntensityData.java, src/java/picard/illumina/parser/ReadStructure.java, src/java/picard/illumina/parser/readers/BclQualityEvaluationStrategy.java, src/java/picard/illumina/parser/readers/MMapBackedIteratorFactory.java, src/java/picard/sam/markduplicates/util/MemoryBasedReadEndsForMarkDuplicatesMap.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
M-Ezzat
=> pmd:ImmutableField - Immutable Field

src/java/picard/analysis/CollectGcBiasMetrics.java, src/java/picard/cmdline/CommandLineParser.java, src/tests/java/picard/cmdline/CommandLineParserTest.java
@vdauwera took your pr #437  and added tests and the functionality we discussed.
care to look and comment?
=> Yf try more formatting help

src/java/picard/util/DbSnpBitSetUtil.java, src/java/picard/vcf/CollectVariantCallingMetrics.java
CollectVariantCallingMetrics.  This should speed up the load
significantly for smaller regions.
@tfenne @yfarjoun 
I tested with an interval list with only a few hundred intervals.  It took only a few seconds, versus almost a full minute previously.  I used the dsnp file found here: ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/dbsnp_138.b37.excluding_sites_after_129.vcf.gz
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/broadinstitute/picard/429)
=> Only load the overlapping dbSNP sites when using target intervals in

src/java/picard/analysis/directed/TargetMetricsCollector.java, src/java/picard/cmdline/CommandLineParser.java, src/java/picard/illumina/IlluminaBasecallsConverter.java, src/java/picard/illumina/LanePhasingMetricsCollector.java, src/java/picard/illumina/parser/ClusterIntensityFileReader.java, src/java/picard/illumina/parser/OutputMapping.java, src/java/picard/illumina/parser/ReadStructure.java, src/java/picard/illumina/parser/Tile.java, src/java/picard/sam/AbstractAlignmentMerger.java, src/java/picard/sam/PositionBasedDownsampleSam.java, src/java/picard/sam/markduplicates/util/ReadEndsForMateCigar.java, src/java/picard/util/BaitDesigner.java, src/java/picard/vcf/filter/FilterApplyingVariantIterator.java
This pull request is focused on resolving occurrences of Sonar squid:HiddenFieldCheck - Local variables should not shadow class fields
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:HiddenFieldCheck
M-Ezzat
=> squid:HiddenFieldCheck - Local variables should not shadow class fields

src/java/picard/cmdline/CommandLineParser.java, src/java/picard/fingerprint/HaplotypeMap.java
This pull request is focused on resolving occurrences of Sonar pmd:AppendCharacterWithChar - Append Character With Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:AppendCharacterWithChar
M-Ezzat
=> pmd:AppendCharacterWithChar - Append Character With Char

src/java/picard/analysis/CollectMultipleMetrics.java, src/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
FILE_EXTENSION properly.
Addresses https://github.com/broadinstitute/picard/issues/467
@yfarjoun
=> CollectMultipleMetric and CollectSequencingArtifactMetrics use

Picard-public.iml, Picard-public.ipr
@ktibbett, we talked about this a while back. Can you take a look?
=> trying to fix the intellij setting so that it points to the 1.8 java sdk

src/java/picard/analysis/TheoreticalSensitivity.java, src/tests/java/picard/analysis/TheoreticalSensitivityTest.java
@yfarjoun the motivation comes from wanting to call this method many times and not have so many logging messages.
Also, @davidbenjamin, could you possibly add a comment for the class explaining the motivation and reasoning behind this method?  Or provide a link to a paper/reference that does?  It would be great for folks who want more information about the motivation, math, and what it is trying to estimate.
=> Add a method that exposes logging in TheoreticalSensitivity.

src/java/picard/vcf/LiftoverVcf.java, src/tests/java/picard/vcf/LiftoverVcfTest.java
LiftoverVCF will lift variants to an alternate genome, given a chain file.  This patch will add attributes to each record to store the source chromosome/position for the lifted variant.  It can be a nice improvement when trying to work w/ the lifted VCF.
=> Store source chr/position on liftover

src/java/picard/analysis/CollectWgsMetricsFromQuerySorted.java, src/java/picard/analysis/CollectWgsMetricsFromSampledSites.java, src/tests/java/picard/analysis/CollectWgsMetricsFromQuerySortedTest.java, src/tests/java/picard/analysis/CollectWgsMetricsFromSampledSitesTest.java
@ktibbett: deprecating these classes as requested.
I'll also add an issue here to remove them in a few months.
=> Deprecating tools that we no longer want to support

src/java/picard/vcf/GenotypeConcordance.java, src/java/picard/vcf/GenotypeConcordanceContingencyMetrics.java, src/java/picard/vcf/GenotypeConcordanceStates.java, src/java/picard/vcf/GenotypeConcordanceSummaryMetrics.java
Also fixed a NPE when run on a whole genome (no intervals).
=> Making more classes and methods public in Genotype Concordance.

src/java/picard/analysis/CollectMultipleMetrics.java
so that the output will not have duplication of programs if the user neglects to include a null as the first element. Also clarify documentation wrt INTERVALS and DB_SNP which are (currently) only use by one PROGRAM.
=> Changes the List of ProgramInterfaces to a Set 

src/scripts/release_picard.sh
@jacarey I needed to fix this typo to have the release work.
=> fixing a typo in the release script

src/java/picard/vcf/LiftoverVcf.java
I am trying to lift over [NIST's NA12878 reference vcf](http://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/NA12878_HG001/NISTv2.19/NISTIntegratedCalls_14datasets_131103_allcall_UGHapMerge_HetHomVarPASS_VQSRv2.19_2mindatasets_5minYesNoRatio_all_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs.vcf.gz) to b38.  Unfortunately it has some info and format fields in the VCF records which are not found (described) in the VCF header.  I would like the tool not to fail when such records are encountered.
Relies on https://github.com/samtools/htsjdk/pull/590
=> New option: ALLOW_MISSING_FIELDS_IN_HEADER in LiftoverVcf.

src/java/picard/analysis/TheoreticalSensitivity.java
Tests for theoretical het sensitivity passed locally, having trouble with my picard-htsjdk set up to try testing all so opening a PR so it tests for me :)
=> Small changes to make HetSense deterministic

src/java/picard/analysis/AdapterUtility.java, src/java/picard/analysis/AlignmentSummaryMetricsCollector.java, src/java/picard/analysis/CollectJumpingLibraryMetrics.java, src/java/picard/analysis/directed/TargetMetricsCollector.java, src/java/picard/cmdline/CommandLineParser.java, src/java/picard/illumina/IlluminaBasecallsConverter.java, src/java/picard/illumina/IlluminaBasecallsToSam.java, src/java/picard/illumina/parser/IlluminaFileUtil.java, src/java/picard/sam/AbstractAlignmentMerger.java, src/java/picard/sam/CompareSAMs.java, src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java, src/java/picard/util/ClippingUtility.java, src/java/picard/util/IntervalListTools.java, src/java/picard/vcf/GatherVcfs.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1066 - Collapsible "if" statements should be merged
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1066
M-Ezzat
=> squid:S1066 - Collapsible if statements should be merged

_includes/picard-metric-definitions.html
Added information to metricsdefinitions page to indicate that percent = fraction
=> Added text to metrics definitions percent = fraction

src/java/picard/util/ScatterIntervalsByNs.java, src/tests/java/picard/util/ScatterIntervalsByNsTest.java
This is purely an aesthetic commit.
=> sprucing-up ScatterIntervalsByNsTest

src/java/picard/fingerprint/FingerprintChecker.java, src/java/picard/fingerprint/HaplotypeProbabilitiesFromGenotype.java, src/java/picard/fingerprint/HaplotypeProbabilityOfNormalGivenTumor.java, src/tests/java/picard/fingerprint/FingerprintCheckerTest.java, src/tests/java/picard/fingerprint/HaplotypeProbabilityOfNormalGivenTumorTest.java
- added tests
I'm sorry for the need for this PR. The code was previous not properly tested and it was put in this project prematurely. I have now both added (good!) unit-tests, and separately tested this on a known LoH sample. Unfortunately I am not able to share the sample that I tested this on, but I see it is able to improve the LOD score when the tumor is identified correctly, and it does NOT do so when the normal is called 'tumor'. Also important to point out that if the sample is incorrect, none of the LOD scores are positive....
=> - fixed TN/NT bug in check fingerprints.

src/java/picard/analysis/directed/TargetMetricsCollector.java
When mapping to short amplicons, we care about the # of reads that map to the amplicon.  This commit counts the # of reads that have at least one base mapping to a given interval.
=> Output the read count per target.

src/java/picard/illumina/quality/CollectHiSeqXPfFailMetrics.java
=> Fixed documentation errors in XPFFAILMetrics

.travis.yml, README.md, build.xml
adds a badge too. (+some info to the build.xml which will eventually be copied to README)
@yfarjoun have a look
=> add coveralls report for test coverage

src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java
- Make some private members public.
- Add ctor that takes an instance of metrics object, so subclass can substitute a subclass of RnaSeqMetrics.
- Move some inline code into a protected method so it can be shared by subclass.
=> Make RnaSeqMetricsCollector more easily extensible.

explain-qualities.html, index.html
I have found this useful when I want to convert between ASCII and integer-values for base qualities.
=> Adding a page to help explain and transform Base Qualities.

src/main/java/picard/fingerprint/FingerprintChecker.java, src/main/java/picard/fingerprint/GenotypeReader.java, src/main/java/picard/vcf/GatherVcfs.java, src/main/java/picard/vcf/MakeSitesOnlyVcf.java, src/main/java/picard/vcf/MergeVcfs.java, src/main/java/picard/vcf/SortVcf.java, src/main/java/picard/vcf/SplitVcfs.java, src/main/java/picard/vcf/VcfFormatConverter.java, src/main/java/picard/vcf/processor/VariantIteratorProducer.java, src/test/java/picard/vcf/AbstractVcfMergingClpTester.java, src/test/java/picard/vcf/VariantContextComparatorTest.java
Replaced entire use of getChr() for getContig().
=> Replacing deprecated method entire use.

build.gradle, testdata/picard/vcf/FixVcfHeaderTest/header.vcf, testdata/picard/vcf/FixVcfHeaderTest/output.vcf
@kbergin I figured I'd just do this since I knew what the problem was.
=> updating to htsjdk 2.6.0

src/main/java/picard/analysis/CollectMultipleMetrics.java
in CollectMultipleMetrics.
For fragment runs, CollectSequencingArtifactMetrics does not do anything useful unless this option is set to true.
@tfenne or @yfarjoun want to take a look?
=> Expose the INCLUDE_UNPAIRED option for CollectSequencingArtifactMetrics

src/main/java/picard/analysis/CollectMultipleMetrics.java
For https://github.com/broadinstitute/picard/issues/609
=> The update of the docs for CollectMultipleMetrics.

src/main/java/picard/analysis/CollectRawWgsMetrics.java, src/main/java/picard/analysis/CollectWgsMetrics.java, src/main/java/picard/analysis/CollectWgsMetricsFromSampledSites.java, src/main/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverage.java, src/main/java/picard/analysis/MergeableMetricBase.java, src/test/java/picard/analysis/WgsMetricsTest.java
@yfarjoun want to take a look?
=> Make WgsMetrics mergeable.

src/main/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java, src/main/java/picard/sam/markduplicates/UmiAwareDuplicateSetIterator.java, src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java, src/main/java/picard/sam/markduplicates/UmiGraph.java, src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTest.java, src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java, src/test/java/picard/sam/testers/SamFileTester.java
@yfarjoun @nh13 If one of you could review this, that would be great!
=> UMI Aware Mark Duplicates with rudimentary error correction

src/main/java/picard/cmdline/PicardCommandLine.java
=> Fix usage docs: refer to `-h` instead of `--help`

src/main/java/picard/analysis/CollectWgsMetrics.java, src/main/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverage.java, src/main/java/picard/analysis/TheoreticalSensitivity.java, src/main/java/picard/vcf/filter/FilterVcf.java, src/main/resources/picard/analysis/wgsHistogram.R, src/test/java/picard/analysis/CollectWgsMetricsTest.java, src/test/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverageTest.java
=> SamFileHeader was not available causing a NPE

src/test/java/picard/analysis/TheoreticalSensitivityTest.java, src/test/java/picard/analysis/directed/CollectTargetedMetricsTest.java
- made index created during test get deleted in the end
- tightened TheoreticalHetSensitivity test intervals since it has been made deterministic.
=> A few small improvements to the tests.

src/main/java/picard/analysis/CollectWgsMetrics.java, src/test/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverageTest.java
@yfarjoun here are the fixups for #657.
=> Small fixups to WgsMetrics missed in #657.

README.md
Added a link in the README to a wiki page with full instructions on how to release Picard.
=> Add link to release instructions to README

build.gradle, src/main/java/picard/sam/AbstractAlignmentMerger.java, src/main/java/picard/sam/RevertSam.java, src/main/java/picard/sam/ValidateSamFile.java, src/main/java/picard/util/ClippingUtility.java, src/main/java/picard/vcf/RenameSampleInVcf.java, src/main/java/picard/vcf/processor/VariantIteratorProducer.java
also:
- removed usage of deprecated code
- added some java8 sugar
=> update htsjdk to 2.7.0

src/main/java/picard/illumina/ExtractIlluminaBarcodes.java
=> Add to the ExtractIlluminaBarcodes usage.

build.gradle
=> Upgrade HTSJDK to 2.8.0

src/main/java/picard/sam/SamToFastq.java
Case was incorrect in the usage example. This fixes it.
----
=> Fix case error in usage example of SamToFastq

build.gradle
=> Use htsjdk 2.9.0

src/main/java/picard/vcf/filter/FilterVcf.java
A small PR to fix a few aesthetic issues with FilterVcf and add a progress monitor to same program.
=> Yf filter vcf log progress

README.md
Added '[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://github.com/broadinstitute/picard/blob/master/LICENSE.txt)' to top of README.md. Clicking on the badge will open the specific Picard repo's license.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points …
=> Update README.md to show license badge

src/main/java/picard/illumina/CollectIlluminaLaneMetrics.java
@lbergelson can I trouble you for a quick review?  I was getting annoyed that the metrics coming out of this tool don't have a ".txt" or similar extension.  This change keeps the current behavior.
=> Allow an optional file extension for CollectIlluminaLaneMetrics.

.travis.yml
Added OpenJDK8 as a build configuration to be tested via Travis.
=> Adding OpenJDK to travis build.

build.gradle, src/main/java/picard/util/IntervalListTools.java
Depends on a release of htsjdk: https://github.com/samtools/htsjdk/pull/877
=> Adding the COVERED action to interval list tools.

src/main/java/picard/util/IlluminaUtil.java
=> Adding copyright notice to oligonucliotide sequences

src/main/java/picard/fingerprint/CrosscheckFingerprints.java, src/main/java/picard/fingerprint/FingerprintChecker.java, src/main/java/picard/fingerprint/FingerprintIdDetails.java, src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- mostly cosmetic changes
- removed ununsed "merge fingerprints by sample" (folks can use more general "mergeBy" in crosscheck if needed)
- split the merging and crosschecking into two separate functions in crosscheckFingerprints
- cleaned-up code around read with undefined RG tag.
=> Yf fingerprinting cleanup

src/main/java/picard/fingerprint/CrosscheckFingerprints.java, src/main/java/picard/fingerprint/FingerprintIdDetails.java
A few of these things were used in private and so needed to be exposed.
=> Exposing some methods from the new CrosscheckFingerprints.

src/main/java/picard/cmdline/CommandLineProgram.java
=> Revert default compression level to 5.

src/main/java/picard/util/ScatterIntervalsByNs.java
Updated the documentation for the reference argument in ScatterIntervalsByNs.
Also, we now explicitly check for an index and a dict for the reference file.
Addresses https://github.com/broadinstitute/picard/issues/802
=> Updated the documentation for the reference argument in ScatterIntervalsByNs

src/main/java/picard/vcf/AccumulateVariantCallingMetrics.java
I opted for optimizing speed over memory in the initial implementation of this tool (i.e. read all the tiny metrics into memory and then do a single merge at the end).  But it turns out that with 20K samples and 20K shards it uses a whole lot of memory! 
So this is an implementation of what @yfarjoun suggested originally to merge files as we read them in so that they don't need to be kept in memory.  It's a little slower, but definitely worth it.  Existing tests pass with the new implementation.  …
=> Update the algorithm in gathering metrics so that it does not use a lot of memory

src/main/java/picard/vcf/LiftoverVcf.java, testdata/picard/vcf/testLiftoverBiallelicIndels.vcf
@yfarjoun Because your earlier PR isnt committed I'm opening the merge to your branch, but if you want to merge yours and then make a separate PR to master that's fine.
This does two things: 1) tryToAddVariant() shouldnt stomp over the fixed genotypes using those from the source VC, 2) adds genotypes to the test VCF, which gives coverage over this scenario.  prior to this change, that updated VCF alone would trigger this error.
_You can delete …
=> Dont revert genotypes after fixing

src/main/java/picard/fingerprint/CrosscheckFingerprints.java, src/test/java/picard/fingerprint/CrosscheckFingerprintsTest.java, src/test/java/picard/fingerprint/CrosscheckReadGroupFingerprintsTest.java
compare with previous version to see actual changes.
=> Fixed tests that were removed from CrosscheckReadgroupFingerprints

src/main/java/picard/util/AlleleSubsettingUtils.java, src/test/java/picard/util/AlleleSubsettingUtilsTest.java
-- fixed code
-- added test
----
@davidbenjamin could you please look at this?
=> Allele subsetting code was broken when PL was missing. Got bad NPE.

src/main/java/picard/util/LiftoverUtils.java, src/main/java/picard/vcf/LiftoverVcf.java, src/test/java/picard/util/LiftoverVcfTest.java
1. Fixing the list arguments in LiftoverVcf so that they can be altered
2. Fix bug in liftover where reverse complement failures die unnecessarily
----
=> Fixes for LiftoverVcf

src/main/java/picard/sam/GatherBamFiles.java
Adds Javadoc to GatherBamFiles
=> Adds javadoc documentation to GatherBamFiles

src/main/java/picard/fastq/BamToBfq.java
Adds Javadoc documentation for BamToBfq.
=> Added Javadoc to BamToBfq.

src/main/java/picard/sam/SetNmAndUqTags.java, src/main/java/picard/sam/SetNmMdAndUqTags.java, src/main/java/picard/sam/SplitSamByLibrary.java, src/main/java/picard/sam/ViewSam.java, src/main/java/picard/vcf/VcfToIntervalList.java
The following tools are updated: 
ViewSam
SetNmAndUqTags
SetNmMdAndUqTags
SplitSamByLibrary
VcfToIntervalList
=> initial documentation updates

src/main/java/picard/sam/SortSam.java, src/main/java/picard/vcf/MakeSitesOnlyVcf.java, src/main/java/picard/vcf/RenameSampleInVcf.java
Documentation updates in the following tools for the GATK4 release.
- SortSam
- MakeSitesOnlyVcf
- RenameSampleInVcf
=> Documentation Updates

src/main/java/picard/util/LiftoverUtils.java, src/main/java/picard/vcf/LiftoverVcf.java, src/test/java/picard/util/LiftoverVcfTest.java, src/test/java/picard/vcf/VariantContextComparatorTest.java, src/test/java/picard/vcf/VcfTestUtils.java, testdata/picard/vcf/dummy.two.block.reference.dict, testdata/picard/vcf/testLiftoverMismatchingSnps.vcf, testdata/picard/vcf/vcfWithFlippedAlleles.lift.vcf, testdata/picard/vcf/vcfWithFlippedAlleles.reject.vcf, testdata/picard/vcf/vcfWithFlippedAllelesNegativeChain.lift.vcf, testdata/picard/vcf/vcfWithFlippedAllelesNegativeChain.reject.vcf
- Made tests for LiftOverVcf more thorough
- Added explicit tests for flipped SNP allele in reference (both on a positive and negative liftover block)
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation …
=> MOAR tests for  LiftOverVcf 

src/main/java/picard/util/IntervalListTools.java
When IntervalListTools is asked to open a file that isn't formatted correctly, 
---- …
=> Added a more informative error mesage to IntervalListTools.

build.gradle
=> Update GKL to 0.8.2

src/main/java/picard/illumina/parser/IlluminaFileUtil.java
Fix non deterministic check for tile counts per format.
----
=> Fix tile checking to ensure we are checking against a tile based format.

build.gradle
Up the version of htsjkd to 2.14.3
----
=> Update htsjdk version to 2.14.3

.pullapprove.yml
Adding a `.pullapprove.yml` file so that PRs can't be merged without approval from an admin
----
=> Add .pullapprove.yml file to picard public

src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java
Change order of iteration in pickTranscripts for speed, and create an overridable method so that OverlapDetector.getAll result can be cached.
For single-cell libraries, the number of transcripts in a library is much smaller than the global list of transcripts.  Therefore, when creating a list of genes in the library, it can be much faster to iterate over the transcripts in the library in order to arrive at a list of genes in the library, compared to iterating over the global list of transcripts and testing each transcript for its presence in the library.  
For conventional RNA-seq libraries, this change might not help as much, but it should not hurt performance because the number of transcripts in a library should never be larger than the global list of transcripts.
In addition, for …
=> Change order of iteration in pickTranscripts for speed.

src/main/java/picard/sam/DuplicationMetrics.java, src/test/java/picard/sam/DuplicationMetricsTest.java
- cleans whitespace
- fixes #1146 
- adds a test
=> Yf fix infinite loop md

src/main/java/picard/vcf/MakeVcfSampleNameMap.java, src/test/java/picard/vcf/MakeVcfSampleNameMapTest.java, testdata/picard/vcf/MakeVcfSampleNameMap/NA12878.vcf, testdata/picard/vcf/MakeVcfSampleNameMap/NA12891.vcf, testdata/picard/vcf/MakeVcfSampleNameMap/NA12892.vcf, testdata/picard/vcf/MakeVcfSampleNameMap/expected.sample_map
@yfarjoun here's my take on the tool we discussed. I manually tested against some gvcfs in the cloud, not sure what the story is for automated tests of NIO functionality.
----
=> DSDEGP-2199 Add new MakeVcfSampleNameMap tool.

src/main/java/picard/illumina/ExtractIlluminaBarcodes.java, src/main/java/picard/illumina/NewIlluminaBasecallsConverter.java, src/main/java/picard/util/ThreadPoolExecutorUtil.java
Check and report every 5… minutes. Will handle exceptions. There is no need for a global timeout. Fixes https://broadinstitute.atlassian.net/browse/DSDEGP-2276
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an …
=> Use the awaitThreadPool from new util class

src/main/java/picard/analysis/CollectWgsMetrics.java, src/main/java/picard/analysis/TheoreticalSensitivity.java, src/main/java/picard/analysis/directed/CollectTargetedMetrics.java, src/test/java/picard/analysis/TheoreticalSensitivityTest.java, src/test/java/picard/analysis/directed/CollectTargetedMetricsTest.java
The problem was a hidden random seed that was initialized from the system time and memory location.
=> Fixes intermittent failures in TheoreticalHetSensitivityTests.

build.gradle
This is what GATK has used since [4.0.2.0](https://github.com/broadinstitute/gatk/releases/tag/4.0.2.0). The new version has extra optimizations for compression level 2 (the level we use in our WGS pipeline).
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, …
=> Bump to Intel GKL version 0.8.5.

src/main/java/picard/sam/markduplicates/util/AbstractOpticalDuplicateFinderCommandLineProgram.java
This updates the MarkDuplicates documentation to improve clarity and correct an inaccuracy.
----
=> improves MarkDuplcates documentation, fixes #1087

src/main/java/picard/sam/markduplicates/UmiUtil.java, src/test/java/picard/sam/markduplicates/UmiUtilTest.java
=> Fixes bug so that isTopStrand now deals properly with unmapped reads

Dockerfile
=> Update our jdk base image

src/main/java/picard/sam/SortSam.java
=> Updated the documenation for SortSam where it was somewhat misleading

settings.gradle
Removing weird extraneous include in gradle.settings.  This seems like something that was added during the transition from ant -> gradle or maybe just by accident.
----
=> Removing strange import in gradle.settings

src/main/java/picard/vcf/MergeVcfs.java
Fix a typo in MergeVcfs documentation.
----
=> fix a typo

src/main/java/picard/arrays/GtcToVcf.java, src/main/java/picard/arrays/illumina/InfiniumDataFile.java, src/test/java/picard/arrays/illumina/IlluminaAdpcFileWriterTest.java, src/test/java/picard/arrays/illumina/InfiniumDataFileTest.java
Fix bug in unsignedShortToInt (and add tests)
----
For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-r …
=> Change default to not throw exception for a call on a zeroed out assay

src/main/java/picard/vcf/RenameSampleInVcf.java, src/main/java/picard/vcf/SplitVcfs.java
=> relaxing requirements for VCFIndex in tools that don't need one

README.md
Updating the README with up to date instructions for running single tests.
Provides a work around for https://github.com/broadinstitute/picard/issues/1211
=> Update instructions for running single tests

src/main/java/picard/sam/markduplicates/MarkDuplicates.java
=> Adding logging to help dispell a JVM core-dump

build.gradle
Update to the newest point release of htsjdk 2.20.1
=> bump to htsjdk 2.20.3

src/main/java/picard/illumina/IlluminaBasecallsToSam.java
=> Typo in documentation

build.gradle
* update htsjdk 2.20.3 -> 2.21.0
----
=> update htsjdk to 2.21.0

src/main/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigarIterator.java
=> Replaced int with long to avoid integer overflow in large files in MarkDuplicatesWithMateCigar

src/main/java/picard/analysis/CollectRnaSeqMetrics.java
- Modified the annotation for the IGNORE_SEQUENCE argument to mark it as optional which enables the GATK argument parser to operate correctly.
- Fixed truncated documentation for the IGNORE_SEQUENCE argument
- This fixes a GATK issue https://github.com/broadinstitute/gatk/issues/4427
----
Never delete this, it is our record that procedure was followed. If you find that …
=> CollectRnaSeqMetrics: Made IGNORE_SEQUENCE optional

build.gradle, src/main/java/picard/sam/AbstractAlignmentMerger.java, src/test/java/picard/sam/AbstractAlignmentMergerTest.java
Preview of htsjdk update for pre-emptive review
=> Update htsjdk preview

src/main/java/picard/arrays/GtcToVcf.java, src/main/java/picard/arrays/illumina/CompareGtcFiles.java, src/main/java/picard/arrays/illumina/InfiniumEGTFile.java, src/main/java/picard/arrays/illumina/InfiniumGTCFile.java
The tool CompareGtcFiles is a handy tool for comparing Illumina GTC files.
It previously lived in the picard private repo.  In this PR we migrate it to the
picard repo.
----
=> GL-859.  Ported CompareGtcFiles from Picard private repo

src/main/java/picard/sam/CreateSequenceDictionary.java
=> Cleanup CreateSequenceDictionary and provide better error messaging

build.gradle
=> Update to htsjdk 2.23.0

src/main/java/picard/cmdline/CommandLineProgram.java
Fixes https://github.com/broadinstitute/picard/issues/1546.
=> Update CREATE_INDEX arg javadoc.

build.gradle, src/main/java/picard/analysis/CollectMultipleMetrics.java, src/main/java/picard/cmdline/CommandLineProgram.java, src/main/java/picard/util/help/PicardHelpDocWorkUnitHandler.java, src/main/resources/properties.templates/barclayParserProperties.properties, src/main/resources/properties.templates/legacyParserProperties.properties, src/test/java/picard/analysis/CollectMultipleMetricsTest.java, src/test/java/picard/sam/RevertSamTest.java
=> Determine arg parser to use.

src/main/java/picard/fingerprint/CheckFingerprint.java, src/main/java/picard/fingerprint/CrosscheckFingerprints.java, src/main/java/picard/fingerprint/ExtractFingerprint.java
also
- tweaked documentation a little
fixes #1570 
----
For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-p …
=> Add support for CRAM reading in IdentifyContaminant and ExtractFingerprint

src/test/java/picard/pedigree/SexTest.java
Added a very simple unit test for (https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/pedigree/Sex.java
)
Motivation:  Sex.java had untested methods. 
----
=> Add testing for methods within sex enum

Dockerfile, build_push_docker.sh
Remove deprecated syntax that caused the build to warn and the push to fail
----
=> GL-1038 Fix docker build script

src/main/java/picard/sam/AbstractAlignmentMerger.java, src/test/java/picard/sam/AbstractAlignmentMergerTest.java
This is the alternate solution discuss in #1581.  I think it makes the code a bit cleaner and more understandable.
=> MBA deletion edge case alternate solution

src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java, src/main/java/picard/fingerprint/FingerprintChecker.java, src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
=> extra protection and messaging for the histogram of read lengths in CollectAlignmentSummaryMetrics

build.gradle
Updating htsjdk from 2.23.0 -> 2.24.0.
=> Update htsjdk 2.23.0 -> 2.24.0

src/main/java/picard/illumina/BasecallsConverter.java
We were trying to log the exception from all executors, should have only been logging for those that had an exception.
----
For more detailed …
=> Handle error case in interruptAndShutdownExecutors.

src/main/java/picard/illumina/CheckIlluminaDirectory.java, src/main/java/picard/illumina/CollectIlluminaBasecallingMetrics.java, src/main/java/picard/illumina/parser/NewIlluminaDataProvider.java, src/main/java/picard/illumina/parser/readers/CbclReader.java
=> Only read the cbcl header once the tile is about to be cached and then close the streams.

src/main/java/picard/sam/RevertSam.java
Minor spacing error in parameter/argument usage statement
----
=> Fix typo in usage

src/main/java/picard/arrays/GtcToVcf.java
Currently, GtcToVcf includes the call rate of a sample in the header of the VCF generated.
It takes this call rate directly from the GTC file.
This call rate does not take into account zeroed out SNPs (SNPs/assays that are marked as 'do not call' in the cluster file).
This PR recalculates the call rate and takes into account the number of zeroed out SNPs (the count is NOT included in the denominator of the call rate calculation).
----
=> Changed calculation of call rate to account for zeroed out SNPs.

src/main/java/picard/illumina/SortedBasecallsConverter.java
Added more logging to IlluminaBasecallsToFastq
Simplify implementation of awaitTileProcessingCompletion
----
=> GL-1761.  Added more logging to IlluminaBasecallsToFastq

src/main/java/picard/illumina/ExtractBarcodesProgram.java
Correct logic to have ExtractBarcodesProgram properly match for barcodes with ALL ns
---- …
=> Correct logic to have ExtractBarcodesProgram properly match for all Ns

src/test/java/picard/illumina/CollectIlluminaBasecallingMetricsTest.java, src/test/java/picard/illumina/ExtractIlluminaBarcodesTest.java, src/test/java/picard/illumina/IlluminaBasecallsToFastqTest.java, src/test/java/picard/metrics/CollectRrbsMetricsTest.java
This is a re-upload of https://github.com/broadinstitute/picard/pull/1821 with a fixup since I don't have permissions to write to the remote branch.
=> Fix temporary directory hijacking or temporary directory information disclosure

.gitignore
Add two new items to .gitignore that have been annoying me.
=> Add .DS_STORE and .java-version to .gitignore

.github/workflows/cloud_tests.yml, build.gradle, src/test/java/picard/util/GCloudTestUtils.java, src/test/java/picard/util/GCloudTestUtilsUnitTest.java
=> Lb add cloud tests

build.gradle
=> Update htsjdk to 4.0.2

src/main/java/picard/sam/MergeBamAlignment.java
Update MBA documentation to specify that either ALIGNED_BAM or READ1_ALIGNED_BAM/READ2_ALIGNED_BAM is required.
=> MBA documentation

.github/workflows/cloud_tests.yml
* update the use of setup-gcloud@v0 -> v2 since v0 is deprecated
=> Update setup_gcloud github action

build.gradle
=> update htsjdk to 4.1.1

build.gradle
I discovered an issue during publishing... of course I discovered it after I'd already tagged the release...
=> Fix duplicate publishing issue

build.gradle
Updating htsjdk to version 4.1.3
=> Update htsjdk to 4.1.3

.github/workflows/cloud_tests.yml, .github/workflows/tests.yml
Updating deprecated github actions upload-artifact from v3 -> v3
=> Updating GH actions upload artifact v3 -> v4

build.gradle
=> Update Htsjdk to 4.2.0

build.gradle
testing htsjdk release candidate
=> Update htsjdk to 4.3.0
