broadinstitute/picard

- src/java/picard/analysis/CollectMultipleMetrics.java
@nh13 Is this what you meant in issue #159 ? Couldn't find any other use of that name string. 
(Using this trivial case as a test first PR to Picard -- let me know if you have different process preferences)
> Fixed typo in output filename according to issue #159

- build.xml
- src/java/picard/vcf/LiftoverVcf.java
I realize there is already a GATK walker to liftover a VCF, however this tool has multiple advantages:
* It's *much* faster
* Does not require the reference sequence of the source genome in order to run
* It emits the target reference sequence's sequence dictionary in the header of the output VCF
* It sorts the output VCF 
* It indices the output VCF
* It emits a "reject" VCF that contains entries that could not be lifted over or who's reference alleles do not match the new reference post-liftover (there is a separate GATK walker to do the second half of this post-liftover too).
> Tool to liftover, sort and index a VCF in a single pass.

- src/java/picard/util/IntervalListScatterer.java
- src/java/picard/util/IntervalListTools.java
sizes of interval lists that have not been created.  This should produce
a more balanced set of interval lists, while fixing the maximum number
of scatters.
> Add a new method for scattering intervals whereby we try to estimate the

- src/java/picard/analysis/artifacts/ArtifactCounter.java
Deal with an edge case when non-standard (i.e. not ACGTN) bases are found in the reference.
> Fix NPE when nonstandard bases are found

- README.md
- build.xml
- src/java/picard/cmdline/CommandLineProgram.java
implementation of GA4GH API.
With this it will be possible to pass these urls as INPUT params. E.g.: 
java -jar dist/picard.jar ViewSam \
INPUT=https://www.googleapis.com/genomics/v1beta2/readgroupsets/CK256frpGBD44IWHwLP22R4/ \
GA4GH_CLIENT_SECRETS=../client_secrets.json
> Add support for reading data from Google Genomics

- src/java/picard/sam/PositionBasedDownsampleSam.java
- src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/java/picard/sam/util/PhysicalLocation.java
- src/java/picard/sam/util/ReadNameParsingUtils.java
- src/tests/java/picard/sam/PositionBasedDownsampleSamTest.java
- src/tests/java/picard/sam/markduplicates/util/OpticalDuplicateFinderTest.java
- testdata/picard/sam/PositionalDownsampleSam/header.dict
This is intended to mimic to a higher degree the results of sequencing less. The idea is to create a periodic mask of reads based on their location within their tile. The mask is setup in such a way so that the same percentage of reads is removed from the bulk and from the boundaries of each tile, and so that neighboring tiles agree on which part of their shared boundary to keep or remove. 
Since this is based on location, mates (and secondary alignments) are treated equally.
> New CLP for downsampling in a way that tries to keep neighboring reads together

- src/java/picard/cmdline/CommandLineParser.java
I don't know why this wasn't done originally.  The code dates back to 2009.  Who wrote this anyway???
> Print default value for option that is a collection.

- src/java/picard/annotation/RefFlatReader.java
The exons are closed intervals, so the test was rejecting an exon of length 1.
> Fix test for zero-length exon.

- src/java/picard/annotation/Gene.java
E.g. if you read the following with RefFlatReader, before this bug fix you would end up with only one Gene:
MIR1253	MIR1253-201	17	-	2651371	2651476	2651371	2651476	1	2651371,	2651476,
hsa-mir-1253	hsa-mir-1253.1-001	17	+	2651371	2651476	2651371	2651476	1	2651371,	2651476,
> Don't ignore strand when comparing Genes.

- src/java/picard/analysis/CollectAlignmentSummaryMetrics.java
- src/java/picard/cmdline/CommandLineParser.java
Done to enable use of HTML formatting in the documentation. Includes an example of what this allows us to do; see CollectAlignmentSummaryMetrics.java
For a preview of what the result looks like, build from source and see the raw html page in dist/html/program_usage
> Disable escaping html of preamble text in doc generation

- src/java/picard/analysis/CollectMultipleMetrics.java
Needs to notify a user if reference sequence is not specified but is needed. Also removes CollectGcBiasMetrics from the list of default programs. In response to #225.
> Fixing bugs in CollectMultipleMetrics

- src/java/picard/analysis/CollectGcBiasMetrics.java
This is needed when the jar isn't accompanied by the source code.
> allow the generation of charts using the r script within the picard.jar itself

- src/java/picard/illumina/parser/readers/BclReader.java
Track the files on disk that are used to create InputStreams. Then, if a stream fails, we can output the offending file within our exception.
> better error messaging for corrupt bcl.gz files

- src/java/picard/sam/CompareSAMs.java
- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigarTest.java
- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigarTester.java
DuplicateSetIterator.
Depends on: https://github.com/samtools/htsjdk/pull/225.
> Adding a tool SimpleMarkDuplicatesWithMateCigar that uses the new HTSJDK

- src/java/picard/sam/FastqToSam.java
- src/tests/java/picard/sam/FastqToSamTest.java
- testdata/picard/sam/fastq2bam/sequential-files/paired_end_R1_001.fastq
- testdata/picard/sam/fastq2bam/sequential-files/paired_end_R1_002.fastq
- testdata/picard/sam/fastq2bam/sequential-files/paired_end_R2_001.fastq
- testdata/picard/sam/fastq2bam/sequential-files/paired_end_R2_002.fastq
- testdata/picard/sam/fastq2bam/sequential-files/single_end_R1_001.fastq
- testdata/picard/sam/fastq2bam/sequential-files/single_end_R1_002.fastq
USE_SEQUENTIAL_FASTQS optionl.  Sometimes we have the Fastq records for
a one end of a read in multiple files with the suffix
<prefix>_001.fastq, <prefix>_002.fastq, ..., <prefix>_XYZ.fastq, and we
want to treat them all as one file.
> Add support for sequential FASTQ files in SamToFastq using the

- src/java/picard/analysis/directed/InsertSizeMetricsCollector.java
- src/tests/java/picard/analysis/CollectInsertSizeMetricsTest.java
this wasn't being set properly resulting in a bug
also renamed HistogramWidth -> histogramWidth and made it final
fixes #253
> fix HistogramWidth in InsertSizeMetricCollector

- src/java/picard/analysis/CollectWgsMetrics.java
- src/tests/java/picard/analysis/CollectWgsMetricsTest.java
- testdata/picard/sam/several.interval_list
@yfarjoun it turns out that this feature is incredibly useful for rapid QC because we're going to end up with whole genome bams that have been sampled down to a small number of sites and (critically) we only want them assessed at those exact positions (i.e. we do not want to include the rest of the bases in the reads).
> Added capability to CollectWgsMetrics to restrict to certain intervals.

- src/java/picard/analysis/CollectWgsMetricsFromQuerySorted.java
- src/tests/java/picard/analysis/CollectWgsMetricsFromQuerySortedTest.java
No longer necessary now that the function was added to htsjdk.
Also, renamed a variable as requested by Jay.
> Removed temporary method in CollectWgsMetricsFromQuerySorted

- Dockerfile
- src/scripts/picard/docker_helper.sh
Pull request as discussed with Sheila on the GATK mailing list.
Made small changes to Dockerfile and docker_helper.sh to enable the usage of the Picard docker container as an executable. With the image built from this context (`docker build -t custompicard .`) I can run, e.g.:
`docker run -i -t -v $(pwd):/usr/working custompicard MergeSamFiles I=first.bam I=second.bam O=merged.bam` 
successfully if the bam files are present in the current working directory.
> docker container as executable

- src/tests/java/picard/illumina/parser/IlluminaDataProviderTest.java
The provided data have 7 values, so the method needs 7 parameters (else the provided data should be reduced)
> Fix the number of parameters in a test method

- src/java/picard/cmdline/ClassFinder.java
This patch fixes the convertion from URL to path so that paths containing the '+' character are not converted to ' '.
Without it, picard.jar can't be placed in a path where one directory has a '+' in its name (and that happens on Debian builders)
> Fix a bug in path handling

- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/util/DiskBasedReadEndsForMarkDuplicatesMap.java
> use the correct codec when spilling read ends to disk within

- src/java/picard/vcf/GenotypeConcordance.java
- src/java/picard/vcf/GenotypeConcordanceContingencyMetrics.java
- src/java/picard/vcf/GenotypeConcordanceCounts.java
integer, which could happen for true negative sites for whole genomes
when using MISSING_SITES_HOM_REF=true.
> GenotypeConcordance could overflow if there were too many sites for an

- src/tests/java/picard/analysis/CollectGcBiasMetricsTest.java
#302 pointed out I forgot to delete On Exit a temp file. This has a fix. @mattsooknah
> Added 'deleteOnExit' to address Issue 302 where a temp file wasn't being deleted

- src/java/picard/analysis/CollectAlignmentSummaryMetrics.java
- src/java/picard/analysis/CollectInsertSizeMetrics.java
- src/java/picard/analysis/CollectMultipleMetrics.java
- src/java/picard/analysis/CollectRnaSeqMetrics.java
- src/tests/java/picard/analysis/CollectMultipleMetricsTest.java
Add support for passing METRIC_ACCUMULATION_LEVEL in CollectMultipleMetrics (see bug #305). Add a definition for CollectSequencingArtifactMetrics.
For reviewers:
* should METRIC_ACCUMULATION_LEVEL default to ALL_READS instead of empty? Defaulting to empty allows us to validate easily - we can check if the caller was explicit.
* the ProgramInterface interface, and its implementing classes, now need to override two methods (needsReferenceSequence and supportsMetricAccumulationLevel). Would it be better to make this an abstract class and specify concrete default implementations?
> Define Sequencing ArtifactMetrics in CollectMultipleMetrics, support metric accumulation level

- src/java/picard/analysis/CollectOxoGMetrics.java
CollectOxoGMetrics will happily run on alignments without a read group line, but it won't emit any informative output or a warning. This will at least alert the user that a read group line is required.
> Throw exception if no read group specified in CollectOxoGMetrics 

- src/tests/java/picard/analysis/CollectMultipleMetricsTest.java
GcBias doesn't need to be collected at multiple levels in CollectMultipleMetrics. The multilevel collection is addressed elsewhere in the pipeline workflows.
> CollectGcBias: singlepasssam, collectmultiplemetrics, and ready for picard_aggregation wkflw

- src/java/picard/analysis/GcBiasMetricsCollector.java
- src/java/picard/analysis/GcBiasSummaryMetrics.java
Ran into a bug in CollectGcBias with a 100X coverage genome, where the number of aligned reads was greater than MAX_INT. In the latest version, the gc detail and summary metrics were only calculated and written out if totalAlignedReads was >0. Because of the overflow, totalAlignedReads was a random negative number, and thus no metrics were output, but empty (except header) metrics files still were written and no errors were thrown.
To address this, I've changed totalAlignedReads to a long and I've changed the if statement to skip only if totalAlignedReads==0.
> AlignedReads int overflow bug in GcBias

- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicatesTest.java
> fixes a case where we have a fragment read and we want to use barcodes

- src/java/picard/analysis/CollectMultipleMetrics.java
With other metric tools, we can specify the output (and thus file extension) directly.  With `CollectMultipleMetrics` we cannot, but in some pipelines specifying the extension would be very handy.  For example, Illumina's BaseSpace doesn't support creating output files with extensions greater than 20 letters.
> adding a file extension to CollectMultipleMetrics is now possible

- src/java/picard/analysis/directed/InsertSizeMetricsCollector.java
- src/scripts/picard/analysis/insertSizeHistogram.R
The minimum percentage for a paired orientation should be greater than or equal, not greater than.  We have to be careful if there are no inserts, which `testHistogramWidthIsSetProperly` captures in `CollectInsertSizeMetricsTest`.
> Plot all insert size orientations in CollectInsertMetrics when MIN_PCT=0

- src/tests/java/picard/sam/markduplicates/MarkDuplicateWithMissingBarcodeTest.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicateWithMissingReadOneBarcodeTest.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicateWithMissingReadTwoBarcodeTest.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicateWithMissingSampleBarcodeTest.java
- Fixed a small bug in MarkDuplicates that would break running on non-paired reads.
- Added tests that check that the results remain the same when using one of
* SAMPLE_BARCODE_TAG
* READ_ONE_BARCODE_TAG
* READ_TWO_BARCODE_TAG
when the tags themselves are missing from the sam-records
> bugfix (non critical) and more testing in MarkDuplicates

- src/java/picard/analysis/artifacts/ArtifactCounter.java
- src/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
- src/java/picard/analysis/artifacts/ContextAccumulator.java
- src/java/picard/analysis/artifacts/Transition.java
DO NOT MERGE YET.  NEEDS SIGNIFICANT IN-PERSON REVIEW WITH YOSSI.
1. 40% of the runtime went to reading and parsing the original qualities from the BAM.
Given that it is only used as a quality cutoff, we can just use the standard (recalibrated)
quals and save this pain.
2. Get rid of the nested maps; there are a known number of possible transitions so use an array.
3. Stop doing String addition in the Transition class; array lookups are faster.
4. Cache the upper-cased string version of the reference; don't create a string for every
base in every read.
> Performance improvements to CollectSequencingArtifactMetrics to make it faster.

- src/java/picard/analysis/CollectWgsMetricsFromQuerySorted.java
- src/tests/java/picard/analysis/CollectWgsMetricsFromQuerySortedTest.java
This is useful because one may want to ignore Ns and other non-ideal bases.
> Allow the genome territory to be specified on the command-line if desired

- src/java/picard/analysis/CollectWgsMetricsFromQuerySorted.java
No code changes, just a comment for posterity.  I assume I can just merge w/out a review.
> Added note about why our PCT_EXC_UNPAIRED numbers are higher than non-RQC

- build.xml
CollectVariantCallingMetrics was never put into the package-commands ant target so it wasn't getting pulled into the online docs. This adds it so it can get documented properly.
See https://github.com/broadinstitute/picard/issues/290 for general problem description.
> Add CVCM tool to doc generation ant target

- src/java/picard/analysis/CollectInsertSizeMetrics.java
- src/java/picard/analysis/directed/InsertSizeMetricsCollector.java
This is helpful when working with deeply over-sequenced libraries as in that case the post-dedupe distribution is skewed towards the under-represented fragments.
> Added the ability to produce insert size metrics including duplicates.

- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
applied to the first duplicate set considered in
SimpleMarkDuplicatesWithMateCigar.
@eitanbanks this relates to the change in htsjdk: https://github.com/samtools/htsjdk/pull/440
> When using the non-default scoring strategy, the scoring strategy is not

- src/java/picard/analysis/CollectWgsMetricsFromQuerySorted.java
- src/tests/java/picard/analysis/CollectWgsMetricsFromQuerySortedTest.java
1. Ignore non-PF reads.
2. Add TOTAL_READS_ALIGNED to the metrics.
> Small updates to the RQC metrics collector.

- .travis.yml
adding a call to 'ant' before 'ant test' since ant with no targets does a different build than 'ant test'
this should catch problems like the jacoco build issue
> adding an explicit call to ant to travis.yml

- src/java/picard/vcf/LiftoverVcf.java
- src/tests/java/picard/vcf/LiftoverVcfTest.java
- testdata/picard/vcf/test.over.badContig.chain
- testdata/picard/vcf/testLiftoverUsingMissingContig.vcf
@yfarjoun This is a new branch (from mf_liftoverbug)
I'd like to kill the other pull request, and use this one instead.
Unfortunately I've lost your previous PR comments, but I have addressed the following:
"break this up into a test and a dataprovider" in LiftoverVcfTest.java
"long name should be descriptive: WARN_ON_MISSING_CONTIG.
as opposed to what? what happens if this is false?" 
"I don't think this should be an input option. make it a protected (for testing) static value."
"use
} else {  
(all in the same line)"
"here too } else {"
"reference -> target reference"
"What about the same protection for LiftOverIntervalList? there you'll see the same problem:
the add() in line 99 will throw an IllegalArgumentException if the contig isn't in the dictionary."
I will address this in a …
> Adds WMC (Warn on missing contig) option to LiftoverVcf

- src/java/picard/illumina/IlluminaBasecallsConverter.java
- src/java/picard/illumina/IlluminaBasecallsToFastq.java
- src/tests/java/picard/illumina/IlluminaBasecallsToFastqTest.java
- fixed IlluminaBaseCallsToFastq's dealing with UMI's. The problem was that the encoding for the sorting collection wasn't done right, but tests didn't have to spill-to-disk and so this wasn't exposed.
- changed tests so that spill-to-disk happens (now tests fail without code changes)
- java8 sugar
> Fixed IlluminaBaseCallsToFastq's dealing with UMI's

- src/java/picard/analysis/CollectRawWgsMetrics.java
- src/java/picard/analysis/CollectWgsMetrics.java
The signature of these pileups are several million copies of the same exact read which, when recorded in the locus iterator, spike our memory consumption.
What we lose by throwing these reads out is that the PCT_EXC_CAPPED will not be completely accurate.  However, I happen to know (from work on Rapid QC) that our lab at least does not look at that number at all. 
What we gain is the ability to always run CollectWgsMetrics and CollectRawWgsMetrics in under 2Gb of RAM, which greatly simplifies pipelines and also keeps compute costs way down.
Depends on: https://github.com/samtools/htsjdk/pull/456
> Protect against massive pileups so that we do not OOM even with several Gb of RAM

- src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigarIterator.java
- src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/java/picard/sam/markduplicates/util/ReadEnds.java
- src/java/picard/sam/util/PhysicalLocation.java
- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/tests/java/picard/sam/markduplicates/util/OpticalDuplicateFinderTest.java
First pass at some changes to MarkDuplicates to allow optical (co-localized?) duplicates to be annotated in the output file and/or excluded from the output file.  So far support is only included in MarkDuplicates, though with a little help from @nh13 or @bradtaylor I'd be happy to extend support to MarkDuplicatesWithMateCigar also.
@nh13, @yfarjoun : Could you take a first look at this please and let me know what you think of the direction I've taken?  I'm not ready (yet) for a detailed review, just looking to get some extra eyes on this before I sink more time into writing tests and shining it up.  Thanks!
> First pass at adding optical duplicate flagging/removal into MarkDupes

- build.xml
The build.xml page has been modified and now contains a comprehensive list of the Picard tools.  
However, there are six additional doc changes that ended up in this PR that I was planning on saving for a different PR.  That was unintentional, as I could not figure out how to select specific changes prior to rebasing against the master.
> Add missing tools to build.xml file so they get documented

- src/java/picard/analysis/MeanQualityByCycle.java
- src/java/picard/cmdline/CommandLineParser.java
- src/java/picard/illumina/IlluminaBasecallsToFastq.java
- src/java/picard/illumina/IlluminaBasecallsToSam.java
- src/java/picard/illumina/MarkIlluminaAdapters.java
- src/java/picard/illumina/parser/TileIndex.java
- src/java/picard/sam/SamAlignmentMerger.java
- src/java/picard/sam/SamToFastq.java
- src/java/picard/util/AdapterMarker.java
- src/java/picard/vcf/processor/VcfFileSegment.java
- src/java/picard/vcf/processor/VcfFileSegmentGenerator.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2974 - Classes without public constructors should be final
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2974
M-Ezzat
> squid:S2974 - Classes without public constructors should be final

- stylesheets/styles.css
Adjusted wrapper from 740 to 1000px, which enables the adapter oligonucleotides to fit within the wrapper of the Tool Documentation page hen viewed in standard conditions.  Moreover, this change reduces the amount of scrolling required to navigate from the top to the bottom of the pages.
This is an ad-hoc fix; ideally we'd introduce some responsive web design elements (as done on GATK website) but time is the fire in which we burn.
> Minor change to stylesheet to widen the viewport

- build.xml
- src/java/picard/analysis/CollectWgsMetrics.java
- src/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverage.java
- src/scripts/picard/analysis/wgsHistogram.R
@yfarjoun this pull request is not complete, as it requires updating and adding tests, as well as one final pass.  What I wanted to do prior to putting any more effort into this change, is to get a :+1: that if I fix current tests and add some more tests, and respond to all the comments, that this will get merged.  If not, I can move the version of this tool elsewhere.  My reasoning is that this commit changes `WgsMetrics`, which may impact folks who rely on this class having a certain format, so it could be a painful change for some.  Nonetheless, I think the plot that is produced is useful, and the QC metrics (for non-zero coverage regions) are useful for folks doing low-coverage sequencing for technology development.
If you agree that this PR will be included in Picard, I will go back …
> Adding a category and plot to WgsMetrics

- src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
It seems that increment of the variable 'recordsRead' was accidentally deleted during the following refactoring:
git show ee98947 -- **/EstimateLibraryComplexity.java
This pull request uses progress.getCount() instead of the variable to calculate meanGroupSize.
> use progress getCount instead of recordsRead

- src/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/tests/java/picard/sam/markduplicates/util/OpticalDuplicateFinderTest.java
Resolves #472 by slowing *down* and providing "safe points" to the code (I guess)...
This seems to make the problem go away..
@nh13 @tfenne It seems that you are the authors of this code, would one of you be able to take a look? I didn't change anything functional, just added a few logging and progress statements when the duplicate set are large. These cases should be _very_ rare (duplicate sets greater than 1000)
> Adding logging to opticalDuplicateFinder when duplicate set is large

- src/java/picard/vcf/LiftoverVcf.java
Fixed LiftoverVcf to check target contig names against the _names_ in the target genome instead of the `byte[]`s of sequences.
> Fixed LiftoverVcf to contig name checking.

- src/java/picard/sam/SamToFastq.java
I've been running into problems where:
a) Some aligners (e.g. STAR) don't like having large strings of Ns at the ends of reads, and also don't like having adapter sequences present _unless_ you let them to the adapter trimming
b) Hard-clipping (using `CLIPPING_ACTION=N`) causes some arguably invalid fastq records to be omitted because the reads are being entirely clipped, so I get a header then a blank line, and that makes the aligner unhappy.
This change introduces an option (turned off to retain backward compatibility) to establish a minimum length to which to clip, that will preserve some minimum number of bases when doing adapter-based clipping in `SamToFastq`.
> Added an option to require a minimum read length after applying adapter clipping to reads.

- src/java/picard/analysis/directed/TargetMetricsCollector.java
Previously %selected was calculated over all reads, and in the changes introduced in or around e6d54be it was moved to be calculated on only unique reads.  For most experiments the values calculated on all reads and unique reads only are very similar.  However, for experiments at extremely deep coverage, and thus with very high on-target duplication, if the rate of duplicate off-target is sufficiently different the %selected values calculated on all reads vs. just unique reads can diverge quite dramatically.
This change restores the old behaviour of calculating on all reads, which I think is more correct in that it is a more accurate estimate of the fraction of molecules/sequencing reads that were _selected_ for, vs. those that are off-target.
> Moved calculation of values for %selected back to before filtering to unique reads.

- src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
EstimateLibraryComplexity.PairedReadComparator returns System.identityHashCode(lhs) - System.identityHashCode(rhs) when lh and rhs are equal.
This leads to slightly different results in different sequential launches of the metric. It makes difficult to run  regression tests.
We propose to replace the returned expression with zero to provide the results' consistency.
> Return 0 when lhs and rhs are identical in EstimateLibraryComplexity.PairedReadComparator

- src/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
Fix log.warn when omitting group because of group size exceeds expected mean number of read pairs.
It outputs prs.read1 twice instead of prs.read1 and prs.read2.
> Fix typo in log.warn in EstimateLibraryComplexity

- src/java/picard/vcf/GenotypeConcordance.java
- src/java/picard/vcf/GenotypeConcordanceStates.java
- src/java/picard/vcf/PairedVariantSubContextIterator.java
- src/tests/java/picard/vcf/GenotypeConcordanceTest.java
`GenotypeConcordance` is a very useful tool to assess the sensitivity and specificity (and PPV) of variant calls.  Nonetheless, I would like to access some methods in `GenotypeConcordance` in tools that filter and inspect variant calls relative to truth.   As always, I am open to a change in naming as I am admittedly not good at that and would like constructive criticism to get better.
`GenotypeConcordance` methods that are exposed include `determineState` and `classifyVariants`.  I did not refactor `determineState` to use `Optional`s as it relies on some heavy "is something `null`" logic.  I also made the `PairedVariantSubContextIterator` public so that others can iterate through variant contexts similar to `GenotypeConcordance`.   I did not refactor the tests to test `classifyVariants` …
> Exposing variant classification methods in GenotypeConcordance.

- src/java/picard/sam/AbstractAlignmentMerger.java
- src/java/picard/sam/FixNmAndUqTags.java
- src/java/picard/sam/SamAlignmentMerger.java
- src/tests/java/picard/sam/FixNmAndUqTagsTest.java
It does it in the same way that MergeBamAlignment does. Since MergeBamAlignment does not update the UQ and NM tags when the output is not set to 'coordinate', this allows setting these tags further downstream once the data is sorted.
> Added a new CLP which will traverse a sorted sam/bam and fix the UQ and NM tags

- src/java/picard/sam/AbstractAlignmentMerger.java
- src/java/picard/sam/SamAlignmentMerger.java
- src/java/picard/sam/SetNmAndUqTags.java
- src/tests/java/picard/sam/SetNmAndUqTagsTest.java
I merged yf_add_CLP_FixNmAndUqTags too quickly and failed to incorporate some reviewer comments.
@nh13:  Sorry about that. I'm addressing your comments here.
I didn't change the issue regarding the sort order because I think that if the input file is valid then the output should be valid...please correct me if I'm missing something. I agree that if the input has "coordinate" in the header, but is not actually sorted, then it will fail...but that's true for other programs too, no?
> addressing review comments for yf_add_CLP_FixNmAndUqTags 

- src/java/picard/cmdline/StandardOptionDefinitions.java
- src/java/picard/sam/DuplicationMetrics.java
- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigar.java
- src/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigarIterator.java
- src/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesCodec.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
- src/tests/java/picard/sam/markduplicates/QuerySortedMarkDuplicatesTest.java
- src/tests/java/picard/sam/markduplicates/QuerySortedMarkDuplicatesTester.java
- src/tests/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/tests/java/picard/sam/testers/SamFileTester.java
Additionally, if the input is query-sorted it will mark the supplementary and secondary reads in the same manner as their primary counter-parts (with the same query-name). Furthermore, in this case a unmapped read will be duplicate-marked as its mapped mate (assuming, it is mated of-course).
Some tests had to be changed slightly to accommodate for the different behaviors. Tests have been added to test for the expected functionality around supplementary and secondary reads (which was untested), in both query and coordinate-sorted inputs.
I think that it should be possible (and correct) to mark unmapped-records the same as their mapped mates even in coordinate-sorted inputs, but I will leave that for a future discussion.
**NOTE:**
This commit includes an API change regarding the CLP …
> This commit enables MarkDuplicate to process query-sorted input.

- src/java/picard/illumina/parser/MultiTileBclParser.java
- src/java/picard/illumina/parser/PerTileCycleParser.java
Please do not merge yet, as the real-world test case is in progress, but reviews are welcome (@jacarey).
When `PerTileCycleParser` seeks to a tile, it would call `close()` on the
underlying `cycleFilesParser`, which is fine if the parser parses only a
single tile.  When seeking to a new tile with `MultiTileBclParser`, we
want to re-use the underlying `cycleFileParser`, so the `close()` call on the
underlying iterator was commented out.  This leads to an error with "too
many open files", even when setting `ulimit` to 800K files.
The solution is to only call close on the underlying iterator if the
base class' (`PerTileCycleParser`) `close()` method was called, not when the
`seekToTile()` method is called.
> Fix an error with too many open files for Multi-Tile BCLs.

- src/java/picard/util/IntervalListTools.java
In the log message, in the end of the run, when scattering to multiple files, the total number of bases was actually the number of bases in the last intervalList.
There is no test for this since we rarely (if ever?) test the log output values. The CLP produced correct output, just incorrect log-message.
> fixed number of bases in output (missing a + sign)

- src/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigarIterator.java
- src/java/picard/sam/markduplicates/util/LibraryIdGenerator.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
There are cases when there is header with no libraryName. For example:
```
@HD VN:1.0  SO:coordinate
@SQ SN:chr1 LN:101
@SQ SN:chr2 LN:101
@SQ SN:chr3 LN:101
@SQ SN:chr4 LN:101
@SQ SN:chr5 LN:101
@SQ SN:chr6 LN:101
@SQ SN:chr7 LN:404
@SQ SN:chr8 LN:202
@RG ID:1AAXX.1  SM:Hi,Mom!  PL:ILLUMINA
@PG ID:MarkDuplicates   PN:MarkDuplicates   VN:1    CL:MarkDuplicates merge1.sam    PP:bwa
@PG ID:bwa  PN:bwa  VN:1    CL:bwa aln
```
In such situations picard.sam.markduplicates.util.LibraryIdGenerator constructor creates new DuplicationMetrics and puts it to metricsByLibrary Map by key null.  But when MarkDuplicates works it uses getLibraryName method that returns not null but "Unknown Library" value. As a result, when picard.sam.markduplicates.util.AbstractMarkDuplicatesCommandLineProgram::finalizeA …
> Fix null library name problem in LibraryIdGenerator constructor

- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicates.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesWithBarcodes.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
- src/tests/java/picard/sam/markduplicates/AsIsMarkDuplicatesTester.java
- src/tests/java/picard/sam/markduplicates/BySumOfBaseQAndInOriginalOrderMDTester.java
- src/tests/java/picard/sam/testers/SamFileTester.java
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndCoordinateSortedv1.sam
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndCoordinateSortedv2.sam
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndCoordinateSortedv3.sam
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndCoordinateSortedv4.sam
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndv1.sam
- testdata/picard/sam/MarkDuplicates/sameUnclipped5primeEndv2.sam
- Fixed an edge-case that had non-consistent behavior. Added a test that covers it.
- Removed a redundant call to "buildReadEnds" by cloning the fragmentEnd instead.
- Clarified code by changing some variable names.
@nh13 @tfenne
> Bug fix for tiny edge-case in MarkDuplicates

- build.sbt
I found this change necessary in order to do a successful sbt release.
See the discussion at https://github.com/sbt/sbt-testng-interface/issues/9
> Allow sbt TestNG plugin to be resolved on systems that don't have it cached already

- src/java/picard/sam/markduplicates/MarkDuplicates.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicates.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesTagRepresentativeRead.java
- src/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesTagRepresentativeReadCodec.java
- src/java/picard/sam/markduplicates/util/RepresentativeReadCodec.java
- src/java/picard/sam/markduplicates/util/StringCodec.java
- src/java/picard/sam/util/RepresentativeReadName.java
- src/tests/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicatesTagRepresentativeReadTest.java
- src/tests/java/picard/sam/markduplicates/MarkDuplicatesTagRepresentativeReadTester.java
Optional flag added to MarkDuplicates. If true, each record that is part of a duplicate set is tagged with the representative read that is chosen by MarkDuplicates. This is accomplished with the ReadEndsForMarkDuplicatesTagRepresentativeRead class that retains read name information for each read pair examined. The RepresentativeReadName class stores the representative read name and set size for each duplicate set, spilling to disk if necessary. This functionality is tested by MarkDuplicatesTagRepresentativeReadTest that also executes the tests in AbstractMarkDuplicatesCommandLineProgramTest.
> Tag reads in duplicate sets with the representative read and the duplicate set size

- src/java/picard/vcf/MergeVcfs.java
For example, VALIDATION_STRINGENCY=SILENT will be cleared!
> MergeVcfs should not clear options be default.

- src/java/picard/vcf/GatherVcfs.java
If the VCF header spans multiple Gzip blocks and there are no variants,
then an Exception could be thrown:
- java.lang.IllegalStateException: Could not read available bytes from BlockCompressedInputStream
Not adding tests since the fix is obvious, and the issue breaks a production pipeline.  Thanks for reviewing: @yfarjoun @jacarey @ktibbett.
> Fixing bug in GatherVcfs.

- README.md
To document how to deal with the Picard-HTSJDK out-of-sync state (pending Jay's fix).
> Add note on HTSJDK version expectations to README

- src/main/java/picard/sam/BuildBamIndex.java
- src/main/java/picard/sam/FastqToSam.java
This pull request is focused on resolving occurrences of Sonar rule pmd:UseIndexOfChar - Use Index Of Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar
M-Ezzat
> Cleanup - pmd:UseIndexOfChar - Use Index Of Char

- build.gradle
this lets picard be built against artifactory snapshots of htsjdk
picard MUST NOT be released if using an artifactory snapshot (and probably cannot be)
also letting htsjdk version be specified on the command line (fixes #611 )
ex:
```
./gradlew test -Dhtsjdk.version=2.6.0
```
> adding the broad artifactory as a repository

- README.md
Added instructions to the README for building Picard with gradle, including building against custom snapshots of HTSJDK.
Resolves #590
> Add gradle build instructions to README

- settings.gradle
this sets the project name so that jars will have consistent names
without the settings.gradle file, the project name is taken from the folder name which is not ideal
> adding settings.gradle file

- src/main/java/picard/sam/FilterSamReads.java
- src/test/java/picard/sam/FilterSamReadsTest.java
- testdata/picard/sam/FilterSamReads/filter1.interval_list
- testdata/picard/sam/FilterSamReads/filter2.interval_list
Adds an interval filter to filter sam reads that filters over intervals while keeping paired reads together.
> Adding Paired Interval Filter to Filter Sam Reads

- README.md
- build.gradle
I added a currentJar target which is invoked by default if you run `/.gradlew`
It copies the most recent shadowJar into build/libs/picard-current.jar
fixes #617
> creating a picard.jar when running ./gradlew

- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/main/java/picard/analysis/ChimeraUtil.java
- src/main/java/picard/analysis/CollectOxoGMetrics.java
- src/main/java/picard/analysis/CollectRawWgsMetrics.java
- src/main/java/picard/analysis/CollectWgsMetrics.java
- src/main/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
- src/main/java/picard/analysis/directed/CalculateHsMetrics.java
- src/main/java/picard/analysis/directed/CollectHsMetrics.java
- src/main/java/picard/analysis/directed/CollectTargetedMetrics.java
- src/main/java/picard/analysis/replicates/CollectIndependentReplicateMetrics.java
- src/test/java/picard/sam/RevertSamTest.java
A small PR that makes use of predefined strings rather than using "SA" and "MQ". 
Aesthetic only. Has no performance effects.
> Using predefined version of MQ (two different kinds) and SA.

- src/main/java/picard/analysis/MergeableMetricBase.java
- src/main/java/picard/analysis/replicates/IndependentReplicateMetric.java
- src/main/java/picard/sam/DuplicationMetrics.java
- src/main/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
- src/main/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/test/java/picard/analysis/MergeableMetricBaseTest.java
- src/test/java/picard/sam/DuplicationMetricsTest.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
@yfarjoun want to take a look since you wrote `MergeableMetricBase`? 
Also, I am not sure if it is too late, but the metric names in `IndependentReplicateMetric` (the first class to use `MergeableMetricBase`) are camel-case rather than upper-case+underscore, with the latter being the convention of all other picard metrics that I know of.
> DuplicationMetrics are now mergeable.

- src/main/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
Off by default, but I wanted to be able to view all reads vs. duplicates and didn't really want to have to rewrite the entire BAM just to toggle the duplicate flags.  I found this useful because I use CSAM not only to detect artifact metrics but as a general source of information on error rates after screening out bases by quality and from sites thought to be variant.
> Added the ability to include duplicate reads in CollectSequencingArtifactMetrics

- src/main/java/picard/analysis/CollectOxoGMetrics.java
- src/main/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
I've been trying to tie out results between CollectOxoGMetrics and CollectSequencingArtifactMetrics, which I believe should produce near-identical values for a specific subset of metrics, if given the same inputs.  I was getting results that were different enough (off by Q=3-4 for several contexts) that I tracked down what was going on.  The difference is that CollectOxoGMetrics includes non-PF reads and CollectSequencingArtifactMetrics doesn't.  Neither exposed an option to control this.
I've added options to both, but retained the original behaviour of each by default.
> Added options to CollectOxoGMetrics and CollectSequencingArtifactMetrics to include/exclude non-PF reads.

- src/main/java/picard/analysis/directed/InsertSizeMetricsCollector.java
- src/test/java/picard/analysis/CollectInsertSizeMetricsTest.java
There are currently several issues in the master branch that causes Picard to generate wrong results on Histogram bin width values when using `CollectInsertSizeMetrics` tool, and since the unit test in `CollectInsertSizeMetricsTest` is not catching it, this subtle bug slipped through the watching eyes.
Specifically, this PR addressed the following issues:
1. Added several `MetricAccumulationLevel` values so unit tests now could catch errors (master branch currently only test `MetricAccumulationLevel::ALL_READS`).
2. Corrected several expected values in the unit tests that were from running production Picard on the test bam file (see git diff for which values are changed).
3. The proposed correction on line 152 in `InsertSizeMetricsCollector` now generates "correct" bin width values for …
> Issue with InsertSizeMetricsCollector and CollectInsertSizeMetricsTest  [Please review, DON'T MERGE]

- src/main/java/picard/analysis/GcBiasMetricsCollector.java
- src/main/java/picard/analysis/GcBiasSummaryMetrics.java
Previously it was an integer, which could be an issue if we have many
clusters.
> Total clusers is now a long in GcBiasSummaryMetrics.

- src/main/java/picard/analysis/CollectQualityYieldMetrics.java
Changing TOTAL_READS and PF_READS to a long instead of an int.
> QualityYieldMetrics may overflow with many reads.

- src/main/java/picard/util/DbSnpBitSetUtil.java
- src/main/java/picard/vcf/CollectVariantCallingMetrics.java
This can be quite slow for some DBSNP files, so it is nice to see some
progress.
> Add logging for loading in dbSNP in CollectVariantCallingMetrics.

- src/main/java/picard/analysis/directed/TargetMetricsCollector.java
I find that I'm using the `HsMetricCollector` and related classes programmatically a lot, and it would be really nice to be able to access the per-base and per-target coverage information that is accumulated without having to write it out to a file and parse it back in again.  This PR adds a one-line accessor to make the information available to other classes.
> Added a public accessor for the per-target coverage information.

- src/main/java/picard/fingerprint/FingerprintChecker.java
SAMFileReader has been deprecated for years
replacing it with a SamReader generated from a SamReaderFactory
fixes #653
> remove uses of SAMFileReader to fix #653

- src/main/java/picard/analysis/artifacts/CollectSequencingArtifactMetrics.java
- src/main/java/picard/analysis/artifacts/ErrorSummaryMetrics.java
- src/main/java/picard/analysis/artifacts/SequencingArtifactMetrics.java
- src/test/java/picard/analysis/artifacts/CollectSequencingArtifactMetricsTest.java
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/no_bq_cutoff.error_summary_metrics
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/no_mq_cutoff.error_summary_metrics
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/unmapped_mate.error_summary_metrics
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/with_context.error_summary_metrics
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/with_dbsnp.error_summary_metrics
- testdata/picard/analysis/artifacts/CollectSequencingArtifactMetrics/ExpectedMetricsOutput/with_intervals.error_summary_metrics
@yfarjoun This is the PR I promised a few weeks ago.  The result is a new metrics file from CollectSequencingArtifactMetrics with six rows that look something like this:
```
REF_BASE  ALT_BASE  SUBSTITUTION  REF_COUNT  ALT_COUNT  SUBSTITUTION_RATE
A         C         A>C           207358     28         0.00014
A         G         A>G           207358     52         0.00025
A         T         A>T           207358     36         0.00017
C         A         C>A           181950     20         0.00011
C         G         C>G           181950     14         0.00008
C         T         C>T           181950     17         0.00009
```
I've been finding this super-useful to just get a summary of the different kinds of errors that are predominant in a library before diving into _how_ of _where_ …
> Added in an summary error rate by substitution type to CollectSequencingArtifactMetrics

- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
A move out of GenotypeReader uses the default VCFFileReader which requires an index, this is a break from the previous behaviour, and non-needed since the usecase is to iterate through the entire file, not query for a particular location.
This PR uses the version of VCFFileReader that doesn't require an index, and changes the tests so that an index isn't created...
> Do not require an index when checking fingerprints

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
this should help ease some development pains by allowing use of composite builds and other new gradle features
Composite builds are a feature that makes it easier to develop across multiple repos simultaneously.  The intellij experimental branch has support for using composite builds.  See https://blog.jetbrains.com/idea/2016/10/intellij-idea-2016-3-eap-gradle-composite-builds-and-android-studio-2-2/ for more information.
> updating gradle from 2.13 -> 3.1

- build.gradle
- src/main/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
A few tools were are not in the web docs because the doc system is dumb and requires tools to be explicitly added to the gradle build file:
- SetNmMdAndUqTags
- FindMendelianViolations
- UmiAwareMarkDuplicatesWithMateCigar
This adds them. 
Also contains a few doc tweaks for two flavors of the MarkDups tools.
> Add tools to be documented + minor tweaks to MD docs

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This adds github templates to help ensure that new issues and pull request messages are informative and requirements for merging are clearer. These templates are modeled after those used in htsjdk and gsa-unstable, which are already proving quite helpful.
> Issue and pull-request templates

- build.gradle
- src/main/java/picard/sam/CreateSequenceDictionary.java
- src/test/java/picard/sam/CreateSequenceDictionaryTest.java
- testdata/picard/reference/csd_dict.dict
We introduce two pull requests to Htsjdk (https://github.com/samtools/htsjdk/pull/744) and Picard Tools to resolve the issue https://github.com/broadinstitute/picard/issues/432 .
Original version of CreateSequenceDictionary creates and stores all reference sequences entirely in memory in a SAMHeader object and then writes it to a file.
In order to check sequence's names for uniqueness, they are added to a HashSet. This might lead to "Out of memory" exceptions for files with a large number of sequences .
**Changes in Htsjdk:**
In our implementation we introduce a new "on fly" codec SAMSequenceDictionaryCodec, which encodes each sequence and directly writes it to the Dictionary file. This allows us not to store sequences in memory.
**Changes in Picard Tools:**
CreateSequenceDictionary now …
> Fix for issue #432 CreateSequenceDictionary stalls indefinitely with large genomes 

- src/main/java/picard/illumina/CollectIlluminaLaneMetrics.java
- src/test/java/picard/illumina/IlluminaLaneMetricsCollectorTest.java
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/130318_SL-HBB_0226_BFCC1WYMACXX/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/130321_SL-MAK_0035_FC000000000-A306B/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/130401_SL-HAC_0022_BH07PBADXX/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/tileRuns/A67HY/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/tileRuns/A7LE0/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/tileRuns/C2MFAACXX/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/tileRuns/H7BATADXX/RunInfo.xml
- testdata/picard/illumina/IlluminaLaneMetricsCollectorTest/tileRuns/H7H7RADXX/RunInfo.xml
Solves issue https://github.com/broadinstitute/picard/issues/688
The phasing and pre-phasing metrics need all template cycles, including those that are marked as skips or molecular barcodes when the latter two are in-line in the reads.  I have not solved the case where we have both skips/molecular-barcodes in the index reads AND inline in the templates.  I added an option (`INCLUDE_SKIPS_AND_MOLECULAR_BARCODES`) that converts each skip or molecular barcode descriptor to a template descriptor for the purposes of `CollectIlluminaLaneMetrics`.
@yfarjoun want to take a look?
> Support in-line skips and molecular barcodes.

- src/main/java/picard/fingerprint/CheckFingerprint.java
This should allow fingerprinting CRAM files directly.
----
…s should allow fingerprinting CRAM files directly.
> Use SEQUENCE_REFERENCE when opening files in CheckFingerprints. 

- src/main/java/picard/sam/CreateSequenceDictionary.java
- src/test/java/picard/sam/CreateSequenceDictionaryTest.java
`CreateSequenceDictionary` requires always to specified the output name, but GATK programs assumes that the file name is the FASTA name without the extension and ending in __.dict__. Thus, I included the following changes:
* Optional output argument with updated documentation for default behavior.
* Sets the output name as in the GATK framework (port of https://github.com/broadinstitute/gatk/pull/2243) if no one is provided.
* Test for default output name.
----
> Default output for CreateSequenceDictionary

- src/main/java/picard/sam/AbstractAlignmentMerger.java
- src/test/java/picard/sam/AbstractAlignmentMergerTest.java
Fixed the clipping of overlapping reads which is currently broken in the case where the reads _already_ contain soft-clipping.  If the reads contain softclipping at their 3' ends the overlapping read clipping should _add_ to that soft-clipping in order to stop the reads alignment's extending past each other's 5' ends.  Prior to the change, the existing soft-clipping was ignored, and hence the result was incorrect.
> Fix to handle overlapped read clipping in MergeBamAlignment when clipping already present

- src/main/java/picard/analysis/CollectWgsMetrics.java
Moved a O(maxCoverage * nLoci) sanity test which significantly increases run-time for CollectWgsMetrics when the maxCoverage is large, as it is by default for CollectRawWgsMetrics. This test was moved to the end of the iteration over loci, making it essentially an O(maxCoverage) test---much less of a burden.
----
Never delete this, it is our record that procedure was …
> Reverse increase in runtime which results from a sanity test when maxCoverage is large.

- src/main/java/picard/vcf/GenotypeConcordance.java
- src/test/java/picard/vcf/GenotypeConcordanceTest.java
Change to genotype concordance when `OUTPUT_VCF` is true, to change the output filename to include `.genotype_concordance`.  The other output files have more meaningful names so if you use `O=foo.concordance` you end up with `foo.concordance.genotype_concordance_summary_metrics` etc. which seems redundant.  But if you use `O=foo` you get `foo.vcf.gz` out.  This is a problem if, like me, you tend to run things like `picard CollectGenotypeConcordanceMetrics OUTPUT_VCF=true TV=truth.vcf CV=foo.vcf.gz O=foo`.
> Added '.genotype_concordance' into the output VCF name.

- src/main/java/picard/util/LiftOverIntervalList.java
LiftOverIntervalList called `toIntervals.sorted()` and discarded the result, and then continued to write out the unsorted `toIntervals`.  This fixes that.
> Fix sorting of lifted intervals in LiftOverIntervalList

- src/main/java/picard/analysis/RnaSeqMetrics.java
- src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java
- src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java
Added two metrics that measure the fraction of observed reads that
support R1 being on the strand of transcription versus the opposite
strand of transcription.  For paired end reads, R2 is assumed to be on
the opposite strand of that of R1.
> Adding metrics for estimating strand specificity.

- src/main/java/picard/vcf/MergeVcfs.java
just like in GatherVcfs I've added 
```
INPUT = IOUtil.unrollFiles(INPUT, IOUtil.VCF_EXTENSIONS);
for (final File f: INPUT) IOUtil.assertFileIsReadable(f);
```
in MergeVcfs to support the 'list' extension
- [x ] All tests passing on Travis
> add IOUtil.unrollFiles(INPUT, IOUtil.VCF_EXTENSIONS); to MergeVcfs

- src/main/java/picard/analysis/MergeableMetricBase.java
- src/main/java/picard/sam/MergeBamAlignment.java
- src/main/java/picard/vcf/CallingMetricAccumulator.java
- src/main/java/picard/vcf/CollectVariantCallingMetrics.java
- src/main/java/picard/vcf/filter/FilterVcf.java
- src/test/java/picard/analysis/MergeableMetricBaseTest.java
- src/test/java/picard/vcf/CollectVariantCallingMetricsTest.java
- converting VariantCallingMetircs to mergable metrics
- added tests
- extended MergableMetricsBase so that it can deal with private and protected members of the superclass
- cleaned up alignment/typos in FilterVcf and MergeBamAlignment (unrelated)
@nh13 you has said that you'd like to see this framework used for something other than IndependentReplicates...so, here's your chance!  😄
> Converted VariantCallingMetrics to using mergableMetricsBase 

- src/main/java/picard/sam/SamToFastq.java
LazyInitializer is getting deprecated in htsjdk, so I'm premptively removing any references to it here as lambda notation is enough.
----
> Removed explicit reference to LazyInitializer.

- build.gradle
The gradle task `createMetricsDoclet` wasn't actually doing anything.  This fixes it so that it runs and creates the appropriate html.
Fixes https://broadinstitute.atlassian.net/browse/PO-7497?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
----
> fix createMetricsDoclet gradle task

- src/main/java/picard/vcf/UpdateVcfSequenceDictionary.java
- src/test/java/picard/vcf/UpdateVcfSequenceDictionaryTest.java
Implements the handling of stdout in https://github.com/broadinstitute/picard/issues/507.
If `stdout` is the output file, set to write to a stream instead of a file.
----
> UpdateVcfSequenceDictionary handles stdout

- src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java
- src/main/java/picard/util/MathUtil.java
- src/test/java/picard/util/MathUtilTest.java
When the threePrimeCoverage value is 0, the median of the histogram can end up being infinity.  This change makes the result a 0 instead.
> PO-7741, make the fiveToThree value in histogram zero if the denominator is zero

- src/main/java/picard/sam/CreateSequenceDictionary.java
- src/test/java/picard/sam/CreateSequenceDictionaryTest.java
The changes introduced in #712 where ported to HTSJDK, making some code duplication between the two repositories (see #714). This PR removes the duplicated code in Picard.
__WARNING: this requires a new realease of HTSJDK. The last commit includes the artifactory snapshot to prove that it is working.__
----
> Use default HTSJDK method in CreateSequenceDictionary 

- src/main/java/picard/analysis/CollectRnaSeqMetrics.java
- src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java
- src/test/java/picard/analysis/CollectRnaSeqMetricsTest.java
Fixes #728 
If the RIBOSOMAL_INTERVALS option is not given and RRNA_FRAGMENT_PERCENTAGE=0, then [this if statement](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L164) is always true and [rec.getReadLength()](https://github.com/broadinstitute/picard/blob/master/src/main/java/picard/analysis/directed/RnaSeqMetricsCollector.java#L167) will throw an `NullPointerException` since there no records in the input SAM file.
Fixed by throwing and exception if `RRNA_FRAGMENT_PERCENTAGE=0` and `RIBOSOMAL_INTERVALS` is not set or the file is empty.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it …
> Must use a RIBOSOMAL_INTERVALS file if RRNA_FRAGMENT_PERCENTAGE = 0.0

- src/main/java/picard/analysis/MergeableMetricBase.java
This is kindof technical. MergableMetrics uses a parallelStream to merge a collection of MergableMetrics, this fails quite horribly in FindMendelianViolations with multiple threads. there is no reason for this as merging metrics is not typically a time-sensitive task, and so this PR changes it to a serial stream..seems to solve the problem. 
----
> - parallel map in MergableMetric fails since merge is not synchronized.

- src/main/java/picard/sam/markduplicates/ElcHashBasedDuplicatesFinder.java
- src/main/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
We introduce additional improvements in ELC algorithm, which are directed to increase diversity of hash value of PairedReadSequences.
About the potential problem:
If we look at the group which contains about 100k PairedReadSequence and many of them have similar parts, according to current algorithm we will have reads which are similar to many other reads, and in this case we will lose main profit of current approach.
In this example using current approach all 4 reads would be considered similar and eventually would undergo complete check, while actually they can have a lot of difference in other parts.
For example, this file is a group which contains PRS which are very similar in the one of parts but aren't duplicates
[0_241500.zip](https://github.com/broadinstitute/picard/files/652042/0_2 …
> New approach to splitting on sub-group in EstimateLibraryComplexity 

- src/main/java/picard/vcf/GenotypeConcordance.java
- src/test/java/picard/vcf/GenotypeConcordanceTest.java
This addresses #768. If the truth or call VCF has a no call genotype, GenotypeConcordance can still calculate the metrics, but breaks if you try to write a new VCF. This fixes the variant context that is written, to get the allele from the site rather than the genotypes.
----
> Fix in GenotypeConcordance for writing VCFs with no-call genotypes

- README.md
Regular users can't clone the repository with the git link
---- …
> replace git link with https link

- src/main/java/picard/sam/UmiMetrics.java
- src/main/java/picard/sam/markduplicates/UmiAwareDuplicateSetIterator.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiMetrics.java
- src/main/java/picard/util/MathUtil.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTest.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
This PR adds several metrics to UmiAwareMarkDuplicatesWithMateCigar.
These metrics will provide users concise statistics about the UMIs in their data.
The metrics added include:
UMI_LENGTH - the length of the UMIs in bases
OBSERVED_UNIQUE_UMIS - the number of observed UMIs in the deduplicated bam
INFERRED_UNIQUE_UMIS - the number of UMIs observed in the deduplicated bam after error correction
DUPLICATE_SETS_WITHOUT_UMI - the number of duplicate sets that would be identified without using UMIs
DUPLICATE_SETS_WITH_UMI - the number of duplicate sets identified by taking the UMIs into account
INFERRED_UMI_ENTROPY - entropy of inferred (error corrected) UMIs in base 4
OBSERVED_UMI_ENTROPY - entropy of all observed UMIs in base 4
UMI_BASE_QUALITIES - Phred scaled estimate of base qualities in …
> Adds a couple of metrics computed on UMIs

- src/main/java/picard/illumina/ClusterDataToSamConverter.java
- src/main/java/picard/illumina/CustomAdapterPair.java
- src/main/java/picard/illumina/IlluminaBasecallsToFastq.java
- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
- src/main/java/picard/illumina/MarkIlluminaAdapters.java
- src/test/java/picard/illumina/IlluminaBasecallsToSamAdapterClippingTest.java
See discussion https://github.com/broadinstitute/picard/issues/790
Majority of the code lifted over from `MarkIlluminaAdapters`.  Other custom adapter marking options, by way of consensus, have not been lifted over.
@yfarjoun care to take a look?
> Adding custom adapter pairs to IlluminaBasecallsToSam

- src/main/java/picard/analysis/directed/HsMetrics.java
- src/main/java/picard/analysis/directed/TargetMetricsCollector.java
- src/main/java/picard/analysis/directed/TargetedPcrMetrics.java
- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
Also adds the metric to HsMetrics and TargetedPcrMetrics.
> Adding MAX_TARGET_COVERAGE to targeted metrics

- settings.gradle
- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicates.java
- src/main/java/picard/sam/markduplicates/util/ReadEndsForMarkDuplicatesCodec.java
- src/main/java/picard/sam/markduplicates/util/RepresentativeReadIndexerCodec.java
- src/main/java/picard/sam/util/RepresentativeReadIndexer.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTagRepresentativeReadIndexTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTagRepresentativeReadIndexTester.java
This commit re-applies the changes to enable tagging of representative reads. The summary of this behavior is as follows: 
Optional flag added to MarkDuplicates. If true, each record that is part of a duplicate set is tagged with the representative read that is chosen by MarkDuplicates. This is accomplished with the ReadEndsForMarkDuplicatesTagRepresentativeRead class that retains read name information for each read pair examined. The RepresentativeReadName class stores the representative read name and set size for each duplicate set, spilling to disk if necessary. This functionality is tested by MarkDuplicatesTagRepresentativeReadTest that also executes the tests in AbstractMarkDuplicatesCommandLineProgramTest.
This reverts commit 934b217c96ba553910b90a8d3721f35ae7585364.
> Tag reads in duplicate sets with the representative read and the duplicate set size (v2)

- src/main/java/picard/analysis/AlignmentSummaryMetrics.java
- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
Picard has no tool that collects metrics pertaining to properly-paired sam records. Given that some SV tools look to the (lack of a) properly-paired flag as a signal that an SV might be  underfoot, it seems reasonable to collect this metrics somewhere. Given that this flag can be set by the aligner and by MergeBamAlignment, it seem reasonable to put this metric in CollectAlignmentSummaryMetrics. This is what this PR does.
> Yf add proper pairs to asm -- DO NOT MERGE (YET)

- src/main/java/picard/fingerprint/CheckFingerprint.java
- src/main/java/picard/fingerprint/CrosscheckReadGroupFingerprints.java
Two tools that are currently available have discordant descriptions for this option and one description refers to the option as an output instead of an input. #783 describes the discordance. I also wrote up a GATK article to better describe the format, including a format that the next release of Picard should allow (VCF). The article is public [here](http://gatkforums.broadinstitute.org/dsde/discussion/9526).
> Shl doc update description of Picard haplotype_map option

- src/main/java/picard/analysis/directed/TargetMetricsCollector.java
- src/test/java/picard/analysis/directed/CollectTargetedMetricsTest.java
This affects `CollectHsMetrics`, `CollectTargetedMetrics`, and `CollectTargetedPcrMetrics`.  
I have included a test that fails, and then the bugfix. 
The depths per-base for a target is stored as an `int`, but the `total depth` across all bases as a target is returned as an `int`, which for very high (think 20M reads over a short target) coverage, can cause the total to overflow.
> Overflow in TargetMetricsCollector.Coverage

- src/main/java/picard/vcf/GenotypeConcordance.java
- src/test/java/picard/vcf/GenotypeConcordanceTest.java
- testdata/picard/vcf/normalize_no_calls_call.vcf
- testdata/picard/vcf/normalize_no_calls_truth.vcf
There are a couple of fixes when running GenotypeConcordance with `OUTPUT_VCF=true`:
1. #785 ensured that the VCF builder used the original site alleles instead of the genotype alleles in order to prevent the writing of no calls. Unfortunately, this meant that the site alleles were not being normalized by `normalizeAlleles`, which is needed when you are merging two variant contexts with different REF alleles (due to indels). This is now fixed by using the normalized genotype alleles, but removing no calls from the set before making the builder.
2. When a no call site is normalized the new genotype allele would add the surplus bases after the `.`. For example if the ref allele was changing from `A` to `ACCC`, the no call genotype would change from `.` to `.CCC`. This is fixed/tested in the …
> A couple of fixes for writing VCFs in GenotypeConcordance

- build.gradle
- src/test/java/picard/util/FifoBufferTest.java
This brings picard to htsjdk 2.9.1 and fixes a small ambiguity in a constructor in one of the tests.
> Yf rev  htsjdk

- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
CollectAlignmentSummaryMetrics fails with this exception when run on data that includes unpaired reads:
Exception in thread "main" java.lang.IllegalStateException: Inappropriate call if not paired read
This fix checks that each read is paired before trying to check the proper pair flag.
----
> PO-8928: Don't calculate improper pair metrics on unpaired reads

- src/main/java/picard/util/BedToIntervalList.java
Small documentation update to make it clear that the `SD` argument can take one of many files from which a dictionary can be extracted.  Since this capability is there, it would be nice to have it documented.
----
> Small documentation update to BedToIntervalList.

- src/main/java/picard/analysis/CollectQualityYieldMetrics.java
- src/main/java/picard/sam/DownsampleSam.java
In many cases, I'd like to know the exact # of reads after downsampling, while I am piping the output to other tools that will consume the reads.  It would be nice to have `DownsampleSam` output some metrics, so I repurposed `QualityYieldMetrics` to do so.  @yfarjoun or @tfenne thoughts?
> DownsampleSam can optionally yield QualityYieldMetrics.

- src/main/java/picard/vcf/CallingMetricAccumulator.java
- src/test/java/picard/vcf/CollectVariantCallingMetricsTest.java
- testdata/picard/vcf/allHomRef.vcf
This ensures that CollectVariantCalling Detail Metrics will include samples that are only HomRef. Currently it doesn't output a line for them in the detail metrics. Note that the counts for that sample will all be 0 since there are no non-HomRef calls. 
This addresses #797 
----
> Include entirely HomRef Sample in CollectVariantCallingMetrics

- src/main/java/picard/sam/RevertSam.java
- src/test/java/picard/sam/RevertSamTest.java
Fixes #849.
Fixes a NullPointerException when RevertSam is run with SANITIZE=true, The NPE is due to trying to find a specific read group format for an input SAM/BAM file without read groups (RG) . Though this file fails `ValidateSamFile`, it should still be processed.
----
> Fix RevertSam to SANITIZE output when RG is missing

- src/main/java/picard/fingerprint/CrosscheckReadGroupFingerprints.java
In a previous change I mistakenly renamed option EXPECT_ALL_READ_GROUPS_TO_MATCH. This PR restores that option.
> - oops broke the old option EXPECT_ALL_READ_GROUPS_TO_MATCH. Sorry.

- .travis.yml
- build.gradle
Propose to publish a snapshot build to artifactory for each commit to master to make it easy for downstream projects (picard-private, gatk) to depend on interim builds.
@lbergelson I modeled this on htsjdk, which doesn't include encrypted artifactory credentials in the travis yaml, but still seems to work. Do you know how it publishes without those env settings ?
> Publish every snapshot build to artifactory.

- .gitignore
- build.gradle
- src/main/java/picard/cmdline/CommandLineProgram.java
- src/test/java/picard/IntelInflaterDeflaterLoadTest.java
- src/test/java/picard/analysis/CollectMultipleMetricsTest.java
- src/test/java/picard/analysis/CollectWgsMetricsTest.java
- src/test/java/picard/sam/FilterSamReadsTest.java
This mirrors what was done for GATK in broadinstitute/gsa-unstable#1572.
Comwell workflow ID in gotc-dev: 7012caa5-ea19-4f99-82f3-a1f2ca200ad6
----
> DSDEGP-454 Enable the IntelDeflater by default in all invocations of Picard

- src/main/java/picard/illumina/parser/IlluminaDataProviderFactory.java
IlluminaDataProviderFactory is a handy way to get the list of tiles in a flowcell.  Knowing the order in which Picard processes tiles is important if one wants to parallelize basecalling by processing subsets of tiles.  Picard's tile order is idiosyncratic, and the ordering is implemented in a method in a package-private class.  For CBCLs, the availableTiles list is sorted, so this change merely makes it so that availableTiles is always sorted regardless of which ctor was called.
----
Note: There do not appear to be any tests for IlluminaDataProviderFactory for me to …
> Sort IlluminaDataProviderFactory.availableTiles consistently in all ctors

- src/main/java/picard/sam/DownsampleSam.java
DownsampleSam recently gained the ability to output metrics on how many reads were retained etc.  The code checks all over the place for `METRICS_FILE == null`, but the `METRICS_FILE` option was never set to `optional=true`.  This fixes that.
> Made METRICS_FILE optional in DownsampleSam, which was fairly clearly the original intent.

- src/main/java/picard/fingerprint/FingerprintIdDetails.java
Previous versions of the fingerprint code were resilient to the PU attribute of the RG tag being unpopulated, but the newest version throws an exception if it is not populated in the format D047KACXX110901.1.ACCAACTG.  Removing the else branch that throws the exception restores the previous functionality, populating runBarcode, lane, and molecularBarcode with non-meaningful defaults (?/-1/?). 
> Allow @RG PU tag to be unpopulated.

- src/main/java/picard/sam/RevertSam.java
For RevertSam, the user may want to keep reads that fail the SAM validation criteria. Documentation was added to change the VALIDATION_STRINGENCY if the tool stops processing due to a  SAM file validation error.
----
> Add a doc note to change VALIDATION_STRINGENCY if validation error

- build.gradle
This should fix #886. Before this change, the `IntelInflaterDeflaterLoadTest` failed on our CentOS box. With the upgraded dependency, that test passes.
----
> Bump GKL version to avoid hanging in AVX support check.

- src/main/resources/log4j2.xml
Fix for #883 
With the intel deflator added, we get a message when a picard tool starts up:
`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.`
I added a log4j2.xml file in src/main/resources to suppress this error message as done in GATK.
> DSDEGP-1440: added config file to suppress error message

- src/test/java/picard/cmdline/CommandLineProgramStartupErrorLogTest.java
We wanted to get #891 released quick, so we merged it without a regression test. Adding one here. I confirmed it fails on the commit before #891.
----
> Add regression test for #883.

- src/main/java/picard/sam/markduplicates/util/AbstractOpticalDuplicateFinderCommandLineProgram.java
- src/main/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/test/java/picard/sam/markduplicates/util/OpticalDuplicateFinderTest.java
The algorithm for determining optical duplicates is n^2, which is fine when handling normal samples.  But when you hit a sample that has one or more duplicate sets with over 1 million read pairs, it's really bad (yup, that's over a trillion comparisons made in that algorithm; we're seeing that take over a week to run!).  While it may be worth making the algorithm more efficient one day, really once we have a duplicate set with that many reads we're okay just skipping the optical dup check.
In this PR I've added a max set size for the optical dup check.  I've set it to 300K because that's already ~10 billion comparisons.  A user can always disable this maximum (at his/her own peril) on the command-line.
Never delete this, it is our record that procedure was followed. If you find that for …
> Adding the ability to set a maximum size of duplicate sets for checking optical dups

- src/main/resources/log4j2.xml
- src/test/java/picard/cmdline/CommandLineProgramStartupErrorLogTest.java
A recent change sent logging output from the intel deflator to STDOUT.  This unexepected output has caused problems for CLPs that use picard's stdout. 
This PR changes the log4j configuration to send all output to STDERR.
----
> Change log4j logging to send all logging to stderr.

- src/main/java/picard/sam/AbstractAlignmentMerger.java
- src/main/java/picard/sam/SetNmMdAndUqTags.java
- src/test/java/picard/sam/SetNmMdAndUqTagsTest.java
The idea for this is to run on a bam created from cram -> bam using Samtools.  Samtools adds the MD/NM tag to each record on the fly so there is no need to redo those calculations.  This makes it possible to only set the UQ tag.  
> Add set UQ only option to SetNmMdAndUqTags

- .dockerignore
- Dockerfile
This is a fix to get the docker build working again with gradle.
https://github.com/broadinstitute/picard/issues/857
> Fixed docker build for gradle

- src/main/java/picard/sam/AbstractAlignmentMerger.java
- src/main/java/picard/sam/MergeBamAlignment.java
- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/main/java/picard/sam/markduplicates/util/AbstractOpticalDuplicateFinderCommandLineProgram.java
- src/main/java/picard/sam/markduplicates/util/LibraryIdGenerator.java
- src/main/java/picard/sam/util/ReadOutputCommandLineProgram.java
- src/test/java/picard/sam/MergeBamAlignmentTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
- src/test/java/picard/sam/testers/SamFileTester.java
Adding the option to not write out PG tags for MarkDuplicates and MergeBamAlignment.  Default behavior is kept the same as it was before but you can get speed increases if you set them appropriately.
> Add PG tag to every read option

- src/main/java/picard/cmdline/PicardCommandLine.java
- src/test/java/picard/cmdline/PicardCommandLineTest.java
Extract CommandLineProgram finding/processing code for reuse, as requested [here](https://github.com/broadinstitute/picard-private/pull/987);
- [ x] Added or modified tests to cover changes and any new functionality
- [x ] All tests passing on Travis
> Extract CommandLineProgram finding/processing code for reuse.

- src/main/java/picard/vcf/GenotypeConcordance.java
- src/main/java/picard/vcf/MendelianViolations/FindMendelianViolations.java
- src/main/java/picard/vcf/VcfUtils.java
- src/main/java/picard/vcf/filter/FilterVcf.java
Replaced hard-coded uses of .vcf, .bcf, and .vcf.gz with static variables
(Didn't touch the tests or comments though)
Addresses https://github.com/broadinstitute/picard/issues/854 
> Replaced hard-coded uses of .vcf, .bcf, and .vcf.gz with static variables

- src/test/java/picard/TestDataProviders.java
- src/test/java/picard/illumina/parser/readers/MMapBackedIteratorFactoryTest.java
And makes sure that the do not error out. This will avoid scenarios where due to some change a data-provider fails to complete and the tests are silently skipped.
Found two cases of methods that were "marked" as data-providers, but were not, so I removed their annotation.
----
> Added code that tests all the @DataProviders in the package

- src/main/java/picard/fingerprint/FingerprintIdDetails.java
Makes the Fingerprint code more robust to data  that has non-conforming (or missing!) PU fields
----
While At Broad we use sequencing data consisting of reads with RG tags that point to RG records with PU records, populated with well, formed strings (FLOWCELL.LANE, or FC.LANE.BARCODE), this is hardly the case everywhere
Currently the fingerprinting code breaks if it cannot find the PU field or if the lane "part" is not an integer. This PR protects against that eventuality....
For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull …
> Makes the Fingerprint code more robust to data 

- src/main/java/picard/sam/AddOrReplaceReadGroups.java
As said in [issue](https://github.com/broadinstitute/picard/issues/763) **AddOrReplaceReadGroups** doesn't support tags **FO** *(Flow order)* and **KS** *(Key sequence)* from the SAM specification.
Add possibility to pass **KS** and **FO** command line options to **AddOrReplaceReadGroups** tool.
----
> Add support for KS and FO in AddOrReplaceReadGroups

- src/main/java/picard/vcf/LiftoverVcf.java
- src/test/java/picard/vcf/LiftoverVcfTest.java
- testdata/picard/vcf/testLiftoverBiallelicIndels.vcf
LiftOverVcf didn't do a good job lifting over genotypes in simple (non-flipped indel, and all SNPs) cases. 
This was discovered thanks to @bbimber who opened a pr #929 which I closed since the stack trace shown was out-of-date. I hope that this PR revoles the issue, but if not, @bbimber is invited to re-open that PR, or open a new issue documenting the issue at hand.
@bbimber's original description, that I neglected to copy here:
...while picard tries to update the alleles in genotypes for reverse complementation, it does not update the alleles in VariantContextBuilder to reflect any of those changes. This PR applies similar logic to the set of Ref/Alt alleles as already happens for the genotype alleles.
Never delete this, it is our record that procedure was followed. If you find that for …
> Fixing lift-over (again) WRT genotypes

- src/main/java/picard/sam/SamToFastq.java
- src/test/java/picard/sam/SamToFastqTest.java
Improves the Test of DataProviders to use a @DataProvider which will show all the tests separately so that in case of failures it will not abort after the first failure.
(@yfarjoun rebased this to reflect the changes in the commandline parser)
----
> Prk samtofastq compressed

- build.gradle
Pull request for build.gradle update: htsjdk version 1.11->1.12. The change was added manually mid-release yesterday, but we're having issues with the picard.jar, so I'm retracing steps with a proper branch/tests. PO-10277
----
(no updates needed for tests, README)
> updated htsjdk version to 2.12 for snappy changes

- src/main/java/picard/vcf/VcfToIntervalList.java
- src/test/java/picard/vcf/VcfToIntervalListTest.java
- testdata/picard/vcf/small_m2_more_variants.vcf
Added INCLUDE_FILTERED arg to VcfToIntervalList. Backported from https://github.com/broadinstitute/gatk/pull/3250.
> Backport VcfToIntervalList INCLUDE_FILTERED argument from GATK.

- explain-flags.html
I have added a catch in explain-flags.html that will send up a warning **Invalid flag: read not paired** in the case of invalid flag values like 128. I ran into this in issue #955, where I had visited the explain flags page, but had no indication that the flag was invalid. 
> Website: add catch for invalid flags in explain-flags.html

- README.md
The h4 tags were broken on the README. I fixed them by making sure they follow the format specified here https://guides.github.com/features/mastering-markdown/
----
> Fixed H4 tags in README

- src/main/java/picard/illumina/ExtractIlluminaBarcodes.java
The column header names in `ExtractIlluminaBarcodes` are private constants that cannot be used to check if a file has this header names programmatically.  This PR makes them public to allow re-usage for similar kind of data.
In addition, this constants are added to the documentation annotations to avoid possible inconsistencies with the actual value.
----
> Make column names in ExtractIlluminaBarcodes public

- src/test/java/picard/TestDataProviders.java
- src/test/java/picard/util/TestNGUtil.java
Improves the Test of DataProviders to use a @DataProvider which will show all the tests separately so that in case of failures it will not abort after the first failure.
----
> Converted the tests of @DataProviders to using....a @DataProvider!

- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
This adds a usage statement to UmiAwareMarkDuplicatesWithMateCigar that informs the user that this tool should not be used with RNAseq, or other sequencing technologies that have large alignment gaps.  Addressing issue #953 
----
> Adds usage statement to UmiAwareMarkDuplicatesWithMateCigar that it shouldn't be used with RNAseq or other technologies with long gaps.

- src/main/java/picard/illumina/parser/IlluminaFileUtil.java
- src/test/java/picard/illumina/parser/IlluminaFileUtilTest.java
@jacarey want to take a look?
Exception:
```
Exception in thread "main" java.lang.NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
at java.util.Arrays.asList(Arrays.java:3800)
at picard.illumina.parser.IlluminaFileUtil.hasCbcls(IlluminaFileUtil.java:270)
at picard.illumina.ExtractIlluminaBarcodes.customCommandLineValidation(ExtractIlluminaBarcodes.java:447)
at picard.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:323)
at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:196)
at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:98)
at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:108)
```
> ExtractIlluminaBarcodes throws a NullPointerException in the case of an empty lane directory

- src/main/java/picard/analysis/artifacts/Transition.java
- src/test/java/picard/analysis/artifacts/TransitionTest.java
As described in https://github.com/broadinstitute/gatk/issues/3632, this enum may be useful in downstream projects. Thus, this PR adds a class javadoc and makes public the enum.
----
> Make Transition enum public

- src/main/java/picard/sam/DownsampleSam.java
- src/test/java/picard/sam/DownsampleSamTest.java
- src/test/java/picard/sam/PositionBasedDownsampleSamTest.java
- src/test/java/picard/sam/util/SamTestUtil.java
- src/test/java/picard/util/TestNGUtil.java
- testdata/picard/sam/DownsampleSam/header.dict
Fixes #935 so that RANDOM_SEED=null is a working option that results in random results.
----
> Fix random seed in down sample

- src/main/java/picard/sam/markduplicates/UmiAwareDuplicateSetIterator.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiGraph.java
- src/main/java/picard/sam/markduplicates/UmiMetrics.java
- src/main/java/picard/sam/markduplicates/UmiUtil.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTest.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
This fixes (https://github.com/broadinstitute/picard/issues/960), where UmiAwareMarkDuplicatesWithMateCigar saw dashes and Ns in the UMIs as unique bases. Dashes are now ignored in the UMI length calculation. UMIs that contain Ns are still kept in duplicate sets, if edit distance allows, but no longer contribute to the UMI metrics associated with each record. A new metric, PCT_UMI_WITH_N, was added to give a sense of how frequent N containing UMIs are. 
> Bugfix 960 - Handle dashes and Ns in UmiAwareMarkDuplicatesWithMateCigar

- build.gradle
- src/main/java/picard/sam/ValidateSamFile.java
I've added an option to ValidateSamFile that allows it to skip mate validation for edge case samples with high rates of duplication or chimerism (because they require a ton of memory for the mate validation).
As part of this, we need to update picard to use the latest htsjdk
----
> Adds option to validator to skip mate validation

- src/main/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverage.java
- src/main/java/picard/analysis/replicates/CollectIndependentReplicateMetrics.java
- src/main/java/picard/fingerprint/CrosscheckReadGroupFingerprints.java
- src/main/java/picard/sam/SetNmAndUqTags.java
- src/main/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
Added `@DocumentedFeature` and `@BetaFeature` tags appropriately to six tool docs that were not showing up in gatkDocs. 
- Three tools categorized under "Alpha Tools" got the BETA and (Experimental) labels, consistent with how we treat GATK tools.
- Two of these are deprecated tools.
- One is a unit testing tool.
In https://github.com/broadinstitute/dsde-docs/issues/2639, @vdauwera asks that we tag _all_ tools for documentation.
Related issues:
https://github.com/broadinstitute/gatk/issues/3847
https://github.com/broadinstitute/gatk/pull/3850
> Tag for 6 tools for documentation and add beta and experimental categorization to 3

- src/main/java/picard/util/AdapterMarker.java
In a multi-threaded environment there is a chance that basecalls to sam is not deterministic depending on which adapters it sees prior to adapter selection and which adapter it selects. This PR is mean to cache all read seen pre adapter selection and then go back and remove XT tags from reads that were clipped due to adapters other than the selected on being found. …
> Fix up adapter clipping tags after an adapter is selected

- build.gradle
this includes a critical fix for every tool that uses a sorting collection
see https://github.com/samtools/htsjdk/releases/tag/2.13.1
> incorporate htsjdk 2.13.1

- src/main/java/picard/sam/RevertSam.java
- src/test/java/picard/sam/RevertSamTest.java
In some cases, the same record may be found multiple times in a BAM
file.  This option allows the user to remove the duplicate record,
whereas the default behavior is to discard the records (and mates if
present).
> Add DEDUPLICATE_RECORDS option to RevertSam.

- src/main/java/picard/vcf/filter/FilterApplyingVariantIterator.java
- src/test/java/picard/vcf/filter/TestFilterVcf.java
- testdata/picard/vcf/filter/testFilteringSitesOnly.vcf
Currently, FilterVcf will filter entirely a sites-only vcf since "all" the genotypes are filtered (as there are no genotypes) and when a sites has all the genotypes filtered it filters out the site...This modification changes behavior so that a sites only VCF will not be filtered due to "all" its (non-existent)  genotypes.
----
> Enable FilterVcf to filter "sites only" VCFs

- src/test/java/picard/util/LiftoverVcfTest.java
- testdata/picard/vcf/testLiftoverBiallelicIndels.vcf
In #947 I refactored LiftOverVcf to improve performance. This just adds more test coverage, specifically around lifting symbolic and no-call alleles. I also changed a couple variables within the test DataSources to be static constants so they could be shared across tests.
----
> Add additional LiftoverVcf tests

- src/test/java/picard/fingerprint/CheckFingerprintTest.java
- testdata/picard/fingerprint/fingerprinting_detail_metrics.example
- testdata/picard/fingerprint/fingerprinting_summary_metrics.example
Added:
- CheckFingerprintTest class;
- fingerprinting_detail_metrics.example & fingerprinting_summary_metrics.example files in /testdata/picard/fingerprints as correct examples.
> added test class for CheckFingerprint

- src/main/resources/picard/analysis/wgsHistogram.R
- src/test/java/picard/analysis/CollectWgsMetricsWithNonZeroCoverageTest.java
when there is zero coverage.
Also fixed up a few warnings.
> Bug fix: CollectWgsMetricsWithNonZeroCoverage fails to produce a plot

- src/main/java/picard/analysis/InsertSizeMetrics.java
- src/main/java/picard/analysis/directed/InsertSizeMetricsCollector.java
- src/test/java/picard/analysis/CollectInsertSizeMetricsTest.java
I find that I parse the histogram often for these metrics, and so I figured I should just go ahead and add them officially.
> Adding mode and 95th percentile to InsertSizeMetrics.

- src/main/java/picard/analysis/directed/HsMetricCollector.java
This minor change is needed so that a class that extends HsMetricsCollector can update these metrics differently.  Nothing is really changed in this PR.
> Pull out some of the metrics being fixed in HsMetricsCollector into a separate method

- src/main/java/picard/sam/FastqToSam.java
Add javadoc user documentation to the FastqToSam tool.
> Adds FastqToSam javadoc documentation

- src/main/java/picard/illumina/CheckIlluminaDirectory.java
DSDEGP-1626
This PR fixes the bug described here: https://gatkforums.broadinstitute.org/gatk/discussion/comment/42610
This ensures that cbcls are only checked for output cycles.
----
> DSDEGP-1626: Only check expected output cycles

- build.gradle
We plan to release a new Barclay version sometime today, and then will request a Picard release containing that, plus https://github.com/broadinstitute/picard/pull/1043 and as many doc update PRs as possible, to package with the GATK release.
- [x ] All tests passing on Travis
> Upgrade Barclay dependency.

- src/main/java/picard/util/IntervalListTools.java
> Remove extra newline in IntervalListTools summary line.

- build.gradle
- src/main/java/picard/fingerprint/CheckFingerprint.java
- src/main/java/picard/sam/SamAlignmentMerger.java
- src/main/java/picard/util/BedToIntervalList.java
- src/main/java/picard/vcf/CollectVariantCallingMetrics.java
- src/main/java/picard/vcf/UpdateVcfSequenceDictionary.java
- src/test/java/picard/analysis/CollectGcBiasMetricsTest.java
- src/test/java/picard/analysis/CollectWgsMetricsTest.java
- src/test/java/picard/analysis/CollectWgsMetricsTestUtils.java
- src/test/java/picard/analysis/directed/CollectTargetedMetricsTest.java
- src/test/java/picard/sam/MergeBamAlignmentTest.java
- src/test/java/picard/vcf/UpdateVcfSequenceDictionaryTest.java
This htsjdk update includes  updated nio support for vcfs (more convenient), FilterTag modifications to Pass or Filter Reads, Negative/Zero protection against Histogram::getPercentile, and query parameter stripper before block compresed extension.
**Breaking Changes**
new abstract method SamReaderFactory.getFileHeader(Path samFile)
**Deprecations**
SAMSequenceDictionaryExtractor.extractDictionary(File) has been deprecated, use SAMSequenceDictionaryExtractor.extractDictionary(Path) instead
All calls to newly deprecated function have replaced in this PR as well.
Link for 2.14.0 release notes - https://github.com/samtools/htsjdk/releases/tag/2.14.0
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't …
> update htsjdk version to 2.14.0

- src/main/java/picard/util/IntervalListTools.java
- src/test/java/picard/util/IntervalListToolsTest.java
Currently IntevalListTools wants to validate that on certain actions SECOND_INPUT is null or empty. However this check was never implemented.
----
> Added missing validation for SECOND_INPUT that was causing errors.

- src/main/java/picard/sam/FilterSamReads.java
- src/test/java/picard/sam/FilterSamReadsTest.java
- fixed this bug
- added positive and negative tests
fixes #1070
---- …
> FilterSamReads has a bug and can't filter read by read name.

- src/main/java/picard/vcf/LiftoverVcf.java
LiftOver in HTSJDK defaults to logging every single time an interval falls below the minimum match threshold.  This becomes excessive when lifting a large VCF file.  I recently had a PR approved in HTSJDK to add a setter on Liftover to turn this off (samtools/htsjdk#995).  
This PR stems from that.  I'd like to add a command line option in LiftOverVcf that enables/disables this logging behavior.  This is a really straightforward patch.
----
> Allow command line option to suppress LiftOver logging of every failed interval

- src/main/java/picard/util/LiftOverIntervalList.java
- enable REJECT option in LiftoverIntervalList
- summary results log in LiftoverIntervalList
Add option to emit rejected intervals from LiftOverIntervalList
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an …
> Add reject output to liftover intervals

- src/main/java/picard/illumina/parser/PerTileFileUtil.java
- src/main/java/picard/illumina/parser/PerTileOrPerRunFileUtil.java
- src/test/java/picard/illumina/CheckIlluminaDirectoryTest.java
Per run file check still looks for the lane base directory which doesn't exist in most cases. This change fixes the check to look at the run files parent directory instead.
----
> Jc base dir fix

- src/main/java/picard/sam/FilterSamReads.java
- src/test/java/picard/sam/FilterSamReadsTest.java
A debugging option for FilterSamReads is set to true by default, this changes it to be false so not everyone gets the "debugging use only" *.reads file with read names.
This is a change that breaks how the command runs by default.
----
> set debug argument WRITE_READS_FILES in FilterSamReads to false by default

- src/main/java/picard/vcf/LiftoverVcf.java
When performing liftovers, especially from more dissimilar genomes, it can be useful to understand liftover success/failure by contig.  This patch adds fairly simple tracking within LiftoverVcf based on source/target contig for variants that pass/failed liftover, and then logs this information on completion.  we already logged total passing/failed variants - this is just slightly more information.
----
> Simple tracking/logging of liftover success by contig

- build.gradle
This PR updates the version of htsjdk to 2.14.2
This pulls in a fix from htsjdk which should fix an issue with IlluminaBasecallsToSam not cleaning up a lot of sortingcollection.tmp files on completion.
----
> Update htsjdk version to 2.14.2

- src/main/java/picard/illumina/CheckIlluminaDirectory.java
- src/test/java/picard/illumina/CheckIlluminaDirectoryTest.java
`CheckIlluminaDirectory` currently returns the number of errors encountered as its return code. The problem with this is that the standard is that only 8 bits (255) are used for return codes, and some return codes have special meanings. For example, there was recently a situation where the return code, modulus 255, meant that Sun GridEngine retried the job thousands of times because a failing return code was interpreted as something else. 
This PR changes `CheckIlluminaDirectory` to return `1` on error and `0` on success. If there are errors, the number of errors is written to `errors.count` in the current working directory. 
While I was in there, I replaced some unsafe operations with try with resources to make things safer.
----
Never delete this, it is our record that procedure was …
> Tl dsdegp 1641 check illumina directory return code

- src/main/java/picard/sam/RevertSam.java
- src/test/java/picard/sam/RevertSamTest.java
RevertSam had a bug in the sanitation step where unpaired records would fall through to code blocks that required paired records, which caused sanitation to fail. This PR fixes that.
----
> Made unpaired reads not fall through to paired read checks

- build.gradle
google-cloud-nio is currently being included in the shadowJar (picard.jar) but should only be included in the cloudJar configuration. Before this change the two jars (picard.jar and picardcloud.jar) were the about the same size. With this:
-rw-r--r--  1 cnorman  CHARLES\Domain Users  13257211 Mar 22 11:34 picard.jar
-rw-r--r--  1 cnorman  CHARLES\Domain Users  30166495 Mar 22 11:34 picardcloud.jar
> Include google-cloud-nio only in the cloudJar, not in the shadowJar.

- build.gradle
This change works around a known issue in the auth lib used by Google's NIO wrapper, which causes the error:
```
java.io.IOException: Error code 404 trying to get security access token from Compute Engine metadata for the default service account. This may be because the virtual machine instance does not have permission scopes specified.
```
The replacement dependency is the one used in GATK to avoid the same problem.
I ran `CrosscheckFingerprints` in a Cromwell task, using NIO for the inputs, and it worked :tada:
---- …
> DSDEGP-2199 Switch NIO dependency to the patched version used by GATK.

- Dockerfile
- build_push_docker.sh
- src/main/resources/picard/docker_helper.sh
The cloud version of Picard should be accessible from the docker image. By using the `-c` option when invoking the docker image, the picardcloud jar is now run instead of the normal picard jar
----
> Make picardcloud accessible in docker image

- build.gradle
Due to the usage of the git repository to get the version, Picard fails to build if the zipped source is downloaded. Based on the same strategy as GATK, this commit adds a check for the build pre-requisites.
This provides a better error message for cases like https://github.com/broadinstitute/picard/issues/604#issuecomment-380765514, being a temporary solution until https://github.com/broadinstitute/picard/issues/605 is implemented (adding better logging for the user).
----
For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-r …
> Add to gradle build pre-requisites check

- src/main/java/picard/util/LiftoverUtils.java
- src/main/java/picard/vcf/LiftoverVcf.java
- src/test/java/picard/util/LiftoverUtilsTest.java
- src/test/java/picard/util/LiftoverVcfTest.java
Relatively recently LiftoverVcf has a feature added to automatically recover lifted variants with swapped REF/ALT alleles.  See #1149 for some discussion around this.  This PR:
1) Adds an argument to LiftoverVcf to allow users to disable that feature, due to the problems it can cause with allele-based annotations.
2) Adds a new opt-in feature to record the ORIGINAL_ALLELES, in addition to ORIGINAL_START and ORIGINAL_CONTIG.  This is something not directly related to the swapping feature, but as the allele-level modifications get more complicated, simply stashing the original alleles can be useful.  For example, reverse complemented indels might get left-aligned, and reversing that whole process isnt simple.  
3) This is perhaps the one controversial thing I propose: I'd like to see the …
> Add arguments and reporting around recovering REF/ALT swapped alleles

- src/main/java/picard/illumina/NewIlluminaBasecallsConverter.java
- src/main/java/picard/util/ThreadPoolExecutorWithExceptions.java
Previously if there were any uncaught exceptions the completion executor would sit around forever waiting. Now it will shutdown and print an error.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation …
> Jc fix executor exception handling

- src/main/java/picard/cmdline/CommandLineProgram.java
This ensures that java.io.tmpdir is set (which is used when checking if we have space for using the intel deflater/inflater). Currently it will always check system temp dir.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but …
> Move setting of TMP_DIR prior to inflater/deflater check. 

- src/main/java/picard/illumina/ExtractIlluminaBarcodes.java
For instruments like NovaSeq, total number of reads in a lane can be greater than will fit into a 32-bit signed int, causing count of reads to be negative.  This causes various PCT metrics in BarcodeMetric to be 0.  Changing these counters from int to long solves the problem.
----
> Avoid overflow when computing barcode metrics.

- src/main/java/picard/analysis/MergeableMetricBase.java
- src/test/java/picard/analysis/MergeableMetricBaseTest.java
or they can be annotated but not with @MergeByAdding...
fixes #1172
> Allowing static fields in MergableMetrics to be not annotated 

- src/test/java/picard/sam/markduplicates/MarkDuplicatesTestQueryNameSorted.java
This shows that in this case the program marks all the reads (umapped mates, secondary and supplementary) from the same template (i.e. with the same queryname) in the same way. This is possible to do when the input is queryname sorted, and thus it is done.
> Added forgotten (test) class that tests MarkDuplicates on queryname sorted input

- src/main/java/picard/util/LiftoverUtils.java
* Removing an accented `ç` character and replacing it with an ASCII `c`
* This character is causing problems downstream in GATK.  There's some system setup which results in exceptions when they encounter this.  See https://github.com/broadinstitute/gatk/issues/4434.
---
> remove non-ascii character from comment

- build.gradle
upgrade htsjdk from 2.15.0 -> 2.15.1 
this fixes an issue that was preventing opening Pipes as inputs when using the htsjdk `Path` api
----
> upgrade htsjdk to 2.15.1

- src/main/java/picard/illumina/CollectIlluminaLaneMetrics.java
- src/main/java/picard/illumina/parser/TileMetricsUtil.java
- src/test/java/picard/illumina/parser/TileMetricsUtilTest.java
TileMetricsUtil was relying on a hierarchy in the Illumina directory structure to determine which TileMetricsOut.bin to use when collecting lane metrics. This hierarchy has turned out to be unreliable. The correct TileMetricsOut.bin to use should be the one with cluster records. This change has the collector parse all of the TileMetricsOut.bin files in hierarchical order until it finds one with cluster records.
----
> DSDEGP-2354 id correct tile metrics file in parser for novaseq

- build.gradle
upgrade htsjdk from 2.15.1 -> 2.16.0
the new version has useful new features and bug fixes
----
> upgrading htsjdk 2.15.1 -> 2.16.0

- src/main/java/picard/vcf/LiftoverVcf.java
- src/test/java/picard/util/LiftoverVcfTest.java
- In LiftoverVCF, checking if dictionary associated with reference .fast exists.  If not, logging error and returning 1 from doWork().
- Fixes Issue #1157 
- Adding tests for nonexistent dictionary, and non-readable dictionary  
----
> Adding error in LiftoverVcf if reference dictionary does not exist (Issue #1157)

- src/main/java/picard/sam/markduplicates/UmiAwareDuplicateSetIterator.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiMetrics.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTest.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
Adds a LIBRARY field to the UMI_METRICS file.  This allows for the metrics in UMI_METRICS to be stratified by library.
----
> Adding a LIBRARY field to the umi metrics file in UmiAwareMarkDuplicatesWithMateCigar

- src/main/java/picard/illumina/parser/readers/TileMetricsOutReader.java
Tidy TileMetricsOutReader up.
Fix File Format comment description for byte 0 now there is version 3.
Remove asymmetric spaces from PicardException messages.
Remove unused metricValue2 field from IlluminaTileMetrics.
I noticed these while debugging something else.
There should be no operational differences or change in function.
> Tidy up TileMetricsOutReader a bit.

- src/main/java/picard/util/IntervalListScatterer.java
- src/test/java/picard/util/IntervalListScattererTest.java
- src/test/java/picard/util/IntervalListToolsTest.java
- testdata/picard/util/scatterable_with_overflow.interval_list
While refactoring the scattering code in a different branch I noticed this bug. it seems that sometime OVERFLOW mode "forgets" to overflow.
fixed and  added some tests. 
Not sure if there's a point in merging this, but it can serve as an explanation for my other PR (coming up)
> Yf fix scatter with overflow mode

- src/main/java/picard/illumina/ExtractIlluminaBarcodes.java
- src/main/java/picard/util/TabbedTextFileWithHeaderParser.java
ExtractIlluminaBarcodes throws undiagnosed NPEs when the content of a BARCODE_FILE
disagrees with the READ_STRUCTURE specified on the command line.
Instead of throwing a NullPointerException, report a null barcode field in some row
and fail from customCommandLineValidation().
This change adds no new function. It just replaces a generic NPE with a diagnostic.
> Diagnose missing barcodes in ExtractIlluminaBarcodes instead of throwing NPE.

- src/test/java/picard/vcf/VcfTestUtils.java
The method `createTemporaryIndexedVcfFromInput(File, String)` was changed to `deprecated` but the referenced method is not a valid substitute.
- removed deprecated tag from `createTemporaryIndexedVcfFromInput(File, String)`
- added javadoc
- other minor cleanups
----
> Un-deprecate method VcfTestUtils.createTemporaryIndexedVcfFromInput(File, String)

- src/main/java/picard/sam/CreateSequenceDictionary.java
- src/test/java/picard/sam/CreateSequenceDictionaryTest.java
this PR add a new option **AN** in **CreateSequenceDictionary** to support the alternative name in a dictionary, as defined in the sam spec  https://github.com/samtools/hts-specs/blob/master/SAMv1.tex#L212
```
ALT_NAMES=File
AN=File                       Optional file containing the alternative names for the contigs. First column is the
original name, the second column is an alternative name. One contig may have more than one
alternative name.   Default value: null. 
```
In the code, I added a` Map<String,Set<String>>`  mapping the contigs to a set of aliases. This map is then used when a SamSequenceRecord is serialized.
a test was added in CreateSequenceDictionaryTest
Related PR  in htsjdk : https://github.com/samtools/htsjdk/pull/956/files
----
Never delete this, it is our record that …
> CreateSequenceDictionary support for alternative names (@SQ-AN)

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/main/java/picard/cmdline/CommandLineSyntaxTranslater.java
Once we determine a target transition date, we'll need to decide at what point we want to include this. Proposed warning message about upcoming command line syntax transition. Displays an informational message with a link to a wiki page (under construction):
Edit: A couple of people have suggested that we do something like this warning, but it looks like it breaks PipedDataTest.testSortSam.
> Warning message about upcoming command line syntax transition.

- Dockerfile
A number of the Picard Metrics tools generate R code and run it by calling picard RExecutor method. That method runs  ```Rscript``` to generate graphics/PDFs.  This would work fine in many installations since R/Rscript is available on the user's PATH, but the docker image distributed at docker.io (broadinstitute/picard) does not include R, and nor does the image that one can build using the Dockerfile distributed here on github.  When invoked using a regular docker run command, the tools that use RExecutor crash and do not generate the requested graphics if they are run.
All this patch does is add ```r-base``` to the ```apt-get install ...``` command in the Dockerfile.  It does increase the size of the image by about 214 MB at the moment, which is ~22% larger.  On the other hand, it …
> Installation of r-base in Docker Image allows RExecutor to work

- src/main/java/picard/sam/ValidateSamFile.java
This addresses #258 https://github.com/broadinstitute/picard/issues/258.
Gives warning if REFERENCE_SEQUENCE is null.
> Fix to ValidateSamFile to warn when NM validation occurs without reference (#258)

- src/main/java/picard/sam/SplitSamByNumberOfReads.java
- src/test/java/picard/sam/SplitSamByNumberOfReadsTest.java
This adds a test to the PR #1207. 
When a `0` is included in OUTPUT_PREFIX the file names get messed up. The included test fails with the current version but will now pass.
----
> Fix for SplitSamByNumberOfReads when OUTPUT_PREFIX has a zero

- build.gradle
- src/main/java/picard/vcf/GatherVcfs.java
upgrading htsjdk to 2.16.1 which includes some new features and bug fixes needed by GATK and Disq
> upgrade to htsjdk 2.16.1

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/main/java/picard/cmdline/CommandLineSyntaxTranslater.java
CommandLineSyntaxTranslater no longer throws when seeing KEY=VALUE_with_=_in_it options.
Also simplified the deprecation warning and formatted the code so the message is easier to edit.
Also renamed 2 CommandLineSyntaxTranslater methods to be more descriptive.
See Issue#1225 for more information about the problem.
----
> DSDEGP-2749: too many tokens exception in download genotypes

- src/main/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/main/java/picard/sam/util/ReadNameParser.java
- src/test/java/picard/sam/util/ReadNameParserTests.java
In tie-out for MarkDuplicatesSpark we found there were issues passing the proper read name regex arguments to the `OpticalDuplicateFinder` because the owned fields are private and the classes themselves aren't serializable resulting the fields being reset to their default value whenever they are passed around. In order to work around this it is easiest and most future proof to make the corresponding classes in Picard (which MarkDuplicatesSpark calls into) `Serializable`so the default java field serializer will take care of the fields for us.
> Made OpticalDuplicateFinder Serializable

- src/main/java/picard/sam/RevertSam.java
In the documentation of the ``REMOVE_DUPLICATE_INFORMATION`` option in ``RevertSam``, it currently says "Note that if this is true and REMOVE_ALIGNMENT_INFORMATION==false,  the output may have the unusual but sometimes desirable trait of having unmapped reads that are marked as duplicates."  This is incorrect (the true and false have been swapped).  This PR fixes that.
> Fixing small mistake in documentation of RevertSam

- src/main/java/picard/util/GraphUtils.java
- src/test/java/picard/util/GraphUtilsTest.java
The documentation claims that all nodes in the same cluster will have the same representative read as output. As it turns out this would not have been the case for certain graphs with many branching edges and pathological input ordering. I have added a test that demonstrates this problem on the old branch and added an extra step to resolve transitive node parenthood so that we are consistent with the stated behavior.
> Fixed order dependance bug in graphUtils.cluster() algorithm. 

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTagRepresentativeReadIndexTester.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTestQueryNameSorted.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigarTester.java
- src/test/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigarTester.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
I enabled tests for the DT field for all MarkDuplicate family tools for which it is relevant, and added a test that triggered the issue (was miscounting specifically in the case where optical duplicate indexes for a group were next to each-other in the file for querygrouped files).
> Fixed bug in MarkDuplicates where it was mismarking which reads were optical duplicates when TAGGING_POLICY is set. 

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/UmiAwareDuplicateSetIterator.java
- src/main/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/UmiGraph.java
- src/main/java/picard/sam/markduplicates/UmiUtil.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTest.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
- src/test/java/picard/sam/markduplicates/UmiUtilTest.java
- src/test/java/picard/sam/testers/SamFileTester.java
Adds DUPLEX_UMI as an argument to MarkDuplicates and UmiAwareMarkDuplicatesWithMateCigar.  This allows MarkDuplicates and UAMDWMC to properly mark duplicates using duplex strand UMIs.
When using the DUPLEX_UMI argument, the bam will contain an additional tag specified by MOLECULAR_IDENTIFIER_TAG which is "MI" by default.  The contents of this tag uniquely identify the fragment the read comes from, and labels them as having come from the top "/A" or bottom "/B" strand.
This resolves the issue in #1192.
---- …
> Adds DUPLEX_UMI argument to UmiAwareMarkDuplicatesWithMateCigar

- src/main/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/main/java/picard/sam/util/ReadNameParser.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTest.java
Fixed an exception I introduced when supplying a null regex for optical duplicate finding, also made the OpticalDuplicateFinder quit out of duplicate finding faster when the readname regex is disabled.
> Fixed a NullPointerException in the OpticalDuplicateFinder

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/main/java/picard/sam/markduplicates/util/LibraryIdGenerator.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesSetSizeHistogramTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesSetSizeHistogramTester.java
- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
- src/test/java/picard/sam/testers/SamFileTester.java
This change tracks the size of read pairs sets that are found by MarkDuplicates to be mapped to the same location. The feature performs as follows:
- only sets of mapped read pairs are counted in the histogram
- a set size of 1 indicates a read pair was not a duplicate
- set size of 2 indicates two read pairs were mapped to the same location
- set size of 3 indicates three read pairs were mapped to the same location... and so on
Design choices where I'd welcome feedback:
- optional flag to write the set size counts: I could add this if need be. 
- addSingletonToCount: this function directly counts each read pair that does not appear as duplicate. The overall count of these non-duplicate pairs could also be inferred from READ_PAIRS_EXAMINED - READ_PAIR_DUPLICATES. In one sense, I see it as …
> Histogram of duplicate set sizes to be reported in the MarkDuplicates metrics file

- src/main/java/picard/sam/markduplicates/util/OpticalDuplicateFinder.java
- src/test/java/picard/sam/markduplicates/util/OpticalDuplicateFinderTest.java
This change should fix optical duplicate mismatching with the gatk MarkDuplicatesSpark tool. Before, the algorithm for optical duplicate finding did not cluster the reads properly which resulted in the number of optical duplicates found to be input order dependent. To get around this problem I updated the algorithm to use union-find to cluster the optical duplicates and select a single representative non-optical duplicate from each cluster. 
This solves the order dependent count issue while still leaving open the issue of tie-breaking, since the read in each cluster that gets selected is still order dependent. This could be solved with some better tiebreaking but I was not sure the best metric to use at this stage. If we don't fix the problem now it shouldn't affect markDuplicatesSpark …
> Changed the OpticalDuplicateFinder to rely on a clustering algorithm to find duplicate groups

- src/main/java/picard/sam/util/PGTagArgumentCollection.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
PGTagArgumentCollection.ADD_PG_TAG_TO_READS was a `Boolean` which allowed it to be null, changing it to a` boolean` primitive instead 
This fixes https://github.com/broadinstitute/picard/issues/1261
----
> changing ADD_PG_TAG_TO_READ to boolean

- src/main/java/picard/analysis/directed/CollectHsMetrics.java
- src/main/java/picard/analysis/directed/CollectTargetedMetrics.java
- src/main/java/picard/analysis/directed/CollectTargetedPcrMetrics.java
- src/main/java/picard/analysis/directed/HsMetricCollector.java
- src/main/java/picard/analysis/directed/TargetMetricsCollector.java
- src/main/java/picard/analysis/directed/TargetedPcrMetricsCollector.java
- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
When the INCLUDE_INDELS parameter is set to true:
1. Deletions within reads are treated as covering the reference bases if the preceding base is high quality
2. Inserted bases are counted as "on-target" but don't contribute coverage to any target base(s)
There are two motivations for this change:
1. I want to be able to use CollectHsMetrics' per-base coverage output to assess how well an assay is covering target bases.  If the sample being sequenced has one or more short deletions within the targets this results in a precipitous drop in target coverage.  However, I'd argue that those bases in the reference/target are covered, and if covered sufficiently will allow for a deletion to be called in variant calling.
2. When the het sensitivity code was introduced a bug was introduced that …
> Added handling for indels within CollectHsMetrics and CollectTargetedPcrMetrics.

- src/main/java/picard/illumina/ClusterDataToSamConverter.java
- src/main/java/picard/illumina/IlluminaBasecallsConverter.java
- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
- src/main/java/picard/illumina/parser/ReadStructure.java
Currently, IlluminaBasecallsToSam always demultiplexes. We should only demultiplex when the read structure indicates we should.
----
> demultiplex only when we should

- src/main/java/picard/util/IntervalListTools.java
- src/test/java/picard/util/IntervalListToolsTest.java
Adds a COUNT action to IntervalListTools.  This action behaves identically to CONCAT, but including it as a duplicate provides an intuitively named way to count the bases or intervals in an interval list.
----
> Add IntervalListTools COUNT action

- src/test/java/picard/sam/markduplicates/UmiAwareMarkDuplicatesWithMateCigarTester.java
This is a simple bug fix to fix an assert statement in UmiAwareMDWMC tester.
> Fixes assert statement in UmiAwareMDWMC tester

- src/main/java/picard/analysis/directed/TargetedPcrMetrics.java
- src/test/java/picard/metrics/MetricBaseTest.java
Resolving naming collisions by removing fields that are duplicated in the TargetedPCRMetrics class and its base class (TargetMetricsBase).
----
> GL-143 remove fields defined in base class

- src/test/java/picard/analysis/CollectInsertSizeMetricsTest.java
Fixes the remaining issue from https://github.com/broadinstitute/picard/issues/660.
> Fix CollectInsertSizeMetrics temporary file creation.

- src/main/java/picard/vcf/LiftoverVcf.java
- src/test/java/picard/util/LiftoverVcfTest.java
I'm trying to liftover gnomad/genome to hg38 but it takes to much time and memory. I'd rather have the resulting VCF file without sorting and then  possibly sort later with bcftools.
I added an option DISABLE_SORT to liftover vcf:  
- now the `sorter` miight be null if DISABLE_SORT=true
- I moved the variable `out` to a class member `accept`
- I added a test that just write with/without DISABLE_SORT
now vcfliftover can write to stdout, variants are not sorted:
```
$ java -jar build/libs/picard.jar  LiftoverVcf INPUT=testdata/picard/vcf/LiftOver/testLiftoverBiallelicIndels.vcf OUTPUT=/dev/stdout CHAIN=testdata/picard/vcf/LiftOver/test.over.chain REJECT=/dev/null  REFERENCE_SEQUENCE=testdata/picard/vcf/LiftOver/dummy.reference.fasta DISABLE_SORT=true 2> /dev/null 
##fileformat=VCFv4.2 …
```
> liftovervcf without sorting the variants

- src/main/java/picard/analysis/directed/HsMetrics.java
- src/main/java/picard/analysis/directed/PanelMetricsBase.java
- src/main/java/picard/analysis/directed/TargetMetrics.java
- src/main/java/picard/analysis/directed/TargetMetricsBase.java
- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
**Move the probe metrics into TargetMetrics and add a test for HsMetrics**
The probe metrics (ON_PROBE_BASES, NEAR_PROBE_BASES, and OFF_PROBE_BASES) were being inherited by TargetedPCRMetrics and HsMetrics as well as TargetMetrics. These metrics are duplicated as ON_AMPLICON_BASES (etc.) in TargetedPCRMetrics and ON_BAIT_BASES (etc.) in HsMetrics. The probe metrics were moved into TargetMetrics to address the issue. 
Additionally, prior to the refactor that created TargetMetricsBase, HsMetrics did not contain the field PF_BASES. Since we would like to capture this metric for hybrid selection, I have added a check to the CollectHsMetrics test class to check that this metric is being calculated now. 
----
Never delete this, it is our record that procedure was followed. If you find that for …
> GL-143 Move the probe metrics into TargetMetrics and add a test for HsMetrics

- src/main/java/picard/vcf/LiftoverVcf.java
- src/test/java/picard/util/LiftoverVcfTest.java
after liftovervcf ,  the previous vcf header `##reference=file://.../previous-old.build.fa` persists while the new one is not set, which is misleading. This PR removes the previous `##reference` (if any) when building the new VCFheader and set a new `##reference=`.
in the test, I check that there is non-null "reference" header line. 
- [x ] Added or modified tests to cover changes and any new functionality
- [ x] Edited the README / documentation (if applicable)
- [x ] All tests passing on Travis …
> liftovervcf: remove last '##reference=...' and set the new one.

- testdata/picard/fingerprint/NA12891.over.fingerprints.shifted.for.crams.r1.sam
- testdata/picard/fingerprint/NA12891.over.fingerprints.shifted.for.crams.r2.sam
- testdata/picard/fingerprint/NA12892.over.fingerprints.shifted.for.crams.r1.sam
- testdata/picard/fingerprint/NA12892.over.fingerprints.shifted.for.crams.r2.sam
The next release of htsjdk will reject attempts to create an index on a CRAM that is not coordinate sorted. This updates CrossCheckFingerprint test sams that are used to create CRAMs, which were already sorted, but the sort order was  not reflected in the header (the updated files were run through SortSam).
> Sort test files that are used in tests that assume they're indexable.

- src/main/java/picard/sam/SamErrorMetric/CollectSamErrorMetrics.java
Added @DocumentedFeature to the CLP declaration -- otherwise it won't show up in the web docs.
> Make CollectSamErrorMetrics show up in docs

- build.gradle
Improving the error message produced when building fails because of a missing tools.jar
- Adding the detected java version and path to the error message
- This makes problems like https://github.com/broadinstitute/picard/issues/1335 easier to diagnose
> Improving missing tools.jar error message.

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/main/java/picard/cmdline/PicardCommandLine.java
- src/main/java/picard/vcf/GenotypeConcordance.java
- src/test/java/picard/cmdline/PicardCommandLineTest.java
Picard part of https://github.com/broadinstitute/gatk/issues/5421.
Before:
After:
> Trim descriptions to shorten --list display width.

- src/main/java/picard/util/LiftoverUtils.java
- src/test/java/picard/util/LiftoverVcfTest.java
This is a fix to a bug that causes the liftover of spanning deletions to fail.
> Fixes bug that prevented liftover of spanning deletions.

- src/main/java/picard/analysis/CollectMultipleMetrics.java
- src/main/java/picard/cmdline/CommandLineProgram.java
- src/main/java/picard/cmdline/CommandLineSyntaxTranslater.java
- src/test/java/picard/analysis/CollectMultipleMetricsTest.java
Adding the ability to specify individual arguments to programs in CollectMultipleMetrics.
This has been requested several times. for example #1333 
@cmnbroad you might get a kick from this PR...:-)
----
> Yf provide arbtrary inputs to cmm

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/test/java/picard/analysis/replicates/CollectIndependentReplicatesMetricTest.java
This fix is needed as a prerequisite to upgrade Picard to the next version of htsjdk.
`CollectIndependentReplicatesMetricTest` has an `@BeforeTest` method that runs `MergeSamFiles` as a command line program, with CREATE_INDEX=true. `CommandLineProgram` in turn has a side effect that leaves htsjdk's global SAMFileWriterFactory state mutated with non-default values. The next version of htsjdk has code that rejects attempts to create an index for a CRAM file that isn't coordinate sorted. `RevertSamTest.testOutputByReadGroupWithOutputMap` creates CRAM files that are queryname sorted, and usually succeeds because it doesn't attempt to write an index, but fails intermittently with the new htsjdk code if it happens to be run after the `CollectIndependentReplicatesMetricTest` `@BeforeTest` method …
> Recover from side effects introduced in CollectIndependentReplicatesMetric tests.

- README.md
Update the build badge to use travis.com instead of travis.org
----
> Fix travis build badge

- src/main/java/picard/analysis/directed/PanelMetricsBase.java
- src/main/java/picard/analysis/directed/TargetMetricsCollector.java
- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
- testdata/picard/analysis/directed/CollectHsMetrics/chrM_100bp.interval_list
The summary statistics provided by HsMetrics are helpful in determining how well a hybrid selection experiment worked, however currently they do not provide an indication if any target(s) achieved lower depth than the mean. While ZERO_CVG_TARGETS can help with this in extreme cases, it does not apply to instances when one target had very low non-zero coverage.
I think MIN_TARGET_COVERAGE is a natural addition to MAX_ and MEAN_ for summarizing a hybrid-selection experiment’s results.
Any thoughts?
---- …
> Add MIN_TARGET_COVERAGE to HsMetrics

- build.gradle
- src/main/java/picard/analysis/CollectWgsMetrics.java
- src/main/java/picard/analysis/FastWgsMetricsCollector.java
- src/test/java/picard/analysis/CollectWgsMetricsTestUtils.java
- src/test/java/picard/analysis/FastWgsMetricsCollectorTest.java
There was a small bug in the "Fast" WGS collector that assumed that "position" is equal to "refPosition". This assumption is broken in the newest htsjdk which allows a EdgeRead object to appear at the base prior to the read start, meaning that position is refPos-1. This lead to all sorts of interesting small inaccuracies. 
- fixed the above
- modified tests to use the proper place for "expected" and "actual"
- modified tests to be more expansive. …
> Yf debug sam collector error

- build.gradle
Updating htsjdk 2.19.0 -> 2.20.0.  This has new features like vcf 4.3 reads support and the ability to write indexed gzipped fasta files.
> updating htsjdk to 2.20.0

- Dockerfile
- build_push_docker.sh
Dockerhub can't seem to pull google managed images, so we need to change back to the usual dockerhub image for now.
Also remove dockerhub image push from build_push script now that it's done by an automated build
----
> GL-46: Revert base image change due to issues building on dockerhub

- src/main/java/picard/fingerprint/FingerprintChecker.java
This makes reading the index over a network possible, which in turn, fixes #1175.
----
> Adds a buffer to the index stream

- src/main/java/picard/analysis/CollectInsertSizeMetrics.java
- src/main/java/picard/analysis/directed/InsertSizeMetricsCollector.java
Adds a new option to CollectInsertSizeMetrics to specify a _minimum_ width for the histogram.  This differs from `HISTOGRAM_WIDTH` which _always_ sets the width to the given value.
The motivation for this is that I have a process and pipeline that yields libraries with a very predictable insert size distribution most of the time, and for those libraries I've been using `HISTOGRAM_WIDTH` so that all the plots come out with the same X-axis scaling, making visual comparisons much easier and less error-prone.  However, occasionally odd-ball libraries come through which have significantly larger insert sizes, and the plots are then un-usable.
My intention with this option is to allow usage that uses the `DEVIATIONS` argument in combination with `MIN_HISTOGRAM_WIDTH` in such a way that _most_ …
> Added a MIN_HISTOGRAM_WIDTH to CollectInsertSizeMetrics.

- src/main/java/picard/sam/CreateSequenceDictionary.java
- src/main/java/picard/sam/ReorderSam.java
- src/main/java/picard/sam/ValidateSamFile.java
- src/main/java/picard/util/SequenceDictionaryUtils.java
- src/test/java/picard/sam/CreateSequenceDictionaryTest.java
- src/test/java/picard/sam/ReorderSamTest.java
- src/test/java/picard/sam/testers/ValidateSamTester.java
....and input type is BAM.
Also fixed logical problem that Reference was used both to open input (e.g. for cram) and to use as dictionary for new file.
Added a required input SEQUENCE_DICTIONARY and made REFERENCE_SEQUENCE not required.
This changes the API!
Added tests (was untested).
Refactored the code that writes a dictionary (using it in the test)
fixes #974.
supercedes #1073 
_You can delete these instructions once you have written your PR …
> ReorderSam was having trouble when new dictionary is larger than old one

- src/main/java/picard/sam/DuplicationMetrics.java
- src/test/java/picard/sam/DuplicationMetricsTest.java
Fixes NaN error causing weird aggregation metrics. This fix prevents a divide by zero NaN error as a value for `PERCENT_DUPLICATION` by defaulting to zero if it looks like it will be a NaN (`UNPAIRED_READS_EXAMINED` and `READ_PAIRS_EXAMINED`== 0). If even one library was empty, it would cause there to be 0s for values such as `Mean Coverage`.
----
> PO-18867 Catch NaN Percent_Duplcation edge case

- .travis.yml
- build.gradle
Separate the Barclay tests from the legacy tests in the build matrix as suggested [here](https://github.com/broadinstitute/picard/issues/950) so that both always run. This makes the failure reason clear in the case where a test failure is parser-sensitive. This was tested using a forced failure [here](https://travis-ci.org/broadinstitute/picard/builds/285173742).
- [ X] All tests passing on Travis
> Extend travis build matrix to separate Barclay tests from legacy tests.

- build.gradle
- src/main/java/picard/nio/GoogleStorageUtils.java
* Updating NIO dependency from 81 -> 106
* Updating the configuration code to include new code backported from gatk.
* This adds a hook where requester pay's support can be plugged in in a future pr.
* Fixing a bug where we were accidentally importing the non-shaded google dependencies as well as the shaded ones
> fix google cloud import and update to new version

- src/main/java/picard/vcf/UpdateVcfSequenceDictionary.java
- src/test/java/picard/vcf/UpdateVcfSequenceDictionaryTest.java
Fixes https://github.com/broadinstitute/picard/issues/863
**DO NOT MERGE** until using a version of htsjdk with https://github.com/samtools/htsjdk/pull/933. https://github.com/samtools/htsjdk/pull/933 fixes an NPE when writing to stdout and UpdateVcfSequenceDictionaryTest.testUpdateVcfSequenceDictionary will no longer fail. Reverted the code changes and fixed the test from https://github.com/broadinstitute/picard/pull/741. This PR did not properly implement the outputting to stdout and and interpreted a .vcf.gz  as a VCF rather than a BLOCK_COMPRESSED_VCF. The stdout testing was fixed because file descriptor was interpreted as a VCF rather than VCF_STREAM by VariantContextBuilder.determineOutputTypeFromFile.
----
Never delete this, it is our record that procedure was followed. If you find …
> Revert UpdateVcfSequenceDictionary handles stdout logic and repair test - DO NOT MERGE

- src/main/java/picard/illumina/IlluminaBasecallsToFastq.java
* Removing import of com.sun.xml.internal.rngom.parse.host.Base which was unused.
I noticed this because it causes a warning when gatk builds it's doc.
> Remove an unused import which points to a java internal class

- src/main/java/picard/sam/markduplicates/util/LibraryIdGenerator.java
* Change a HashMap in LibraryIdGenerator to a TreeMap so that the resulting metrics files are sorted.
* Fixes #1397 
> Order the MarkDuplicatesMetric file

- src/main/java/picard/sam/AbstractAlignmentMerger.java
- src/main/java/picard/sam/MergeBamAlignment.java
- src/test/java/picard/sam/MergeBamAlignmentTest.java
Currently, MergeBamAlignments will run through without complaint and produce a merged bam if a bam with mapped reads is used in the UNMAPPED_BAM argument.  However, any read which was aligned to the reverse strand in both the UNMAPPED_BAM and the ALIGNED_BAM will have its bases reverse complemented, resulting in a record with alignment on the reverse stand but with bases recorded for the forward strand.  See `MergeBamAlignmentTest.testReverseStrandMappedReadInUnmappedBam()` on branch [ck_Test_MBA_ReverseStrandMappedReadInUnmappedBam](https://github.com/broadinstitute/picard/tree/ck_Test_MBA_ReverseStrandMappedReadInUnmappedBam) for example.
This PR adds a check that all records in UNMAPPED_BAM are unmapped, and throws an exception if it finds any that are mapped. 
For more detailed …
> Throw exception in MergeBamAlignments if UNMAPPED_BAM has mapped reads

- src/main/java/picard/sam/SamErrorMetric/CollectSamErrorMetrics.java
* Adds in a progress meter to `CollectSamErrorMetrics`.
* Now will jump to the next read or variant rather than iterating through each position even if it does not exist in either.  This saves time for the use case that doesn't cover a whole genome / exome.
> Improvements to the locus iteration

- src/main/java/picard/fingerprint/CrosscheckFingerprints.java
- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/test/java/picard/fingerprint/CrosscheckFingerprintsTest.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- testdata/picard/fingerprint/emptyNA12892.vcf
For Jointcalling we re-sample on-the-fly to remove duplicate sample-names that exist in the callset. A samplename->File map is provided to the tools (VariantDB) and the resulting callset has the new sample names. In order to crosscheck the fingerprints against the original gvcfs (or bams) one would need to remap the samples again. doing this on tens-of-thousands of files is expensive, so this PR enables to remap the gvcfs sample names on the fly. 
In addition, this PR makes the dictionary comparison (for fingerprinting) less stringent in the following way: The dictionary checking only happens on the subset of sequence indices from 0 to the maximum one _that appears in the haplotype database file_
> Yf add more sample mapping options to crosscheck + make dictionary checking more lenient

- src/test/java/picard/sam/markduplicates/MarkDuplicateWithMissingBarcodeTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
This resolves issue, https://github.com/broadinstitute/picard/issues/1375.
A data provider in MarkDuplicatesTest was private which resulted in the tests not being run.  When the provider was changed to public, this caused some of the tests to fail.  This fixes the data provider and resulting failing tests.
----
> Fixing up tests in MarkDuplicates so that tests with duplex umis are handled properly

- build.gradle
Updated versions of plugins used to automatically update the documentation on gh-pages.
For each release, we run the command `./gradlew updateGhPages` to update the documentation at https://broadinstitute.github.io/picard/, but this command has been broken for a while. Updating the plugin versions fixes this. 
Note that this PR allows us to update the documentation in the 'newdocs' directory which is not rendered as part of the public facing documentation. Additional work/coordination will need to be done before we can update the docs at http://broadinstitute.github.io/picard/. 
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an …
> Update plugin versions for github-pages documentation

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/util/MemoryBasedReadEndsForMarkDuplicatesMap.java
MarkDuplicates is glacially slow when operating on `queryname` sorted input.  The reason for this is that it continues to use the `DiskBasedReadEndsForMarkDuplicatesMap` which does a bunch of disk-based IO every time it sees a record mapped to a different chromosome than the last record it saw - which is essentially every other record when operating in queryname order.
I was testing with 2m random reads from an exome BAM, and it was taking ~15 minutes to go through the first phase or calculating the read ends.  Subbing in the in-memory map reduced this to < 10 seconds.  This should be entirely safe because when operating on queryname sorted data the read ends map will generally only ever have 1 read in it at a time!
----
Never delete this, it is our record that procedure was followed. If …
> Speeds up MarkDuplicates on queryname input by using the in memory read-ends map.

- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
...in the absence of a REFERENCE_SEQUENCE
- A pathway remains for those who wish to retain the old way of collecting only TOTAL_READS, PF_READS, and NOISE_READS
- fixed #1373
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but …
> Modified CollectAlignmentSummaryMetric to collect more metrics

- src/main/java/picard/illumina/CheckIlluminaDirectory.java
It is useful for `CheckIlluminaDirectory` to log faked files if the `FAKE_FILES` parameter is set to `true`. 
----
> Make CheckIlluminaDirectory log if faking files

- src/main/java/picard/analysis/replicates/CollectIndependentReplicateMetrics.java
- src/main/java/picard/analysis/replicates/IndependentReplicateMetric.java
CollectIndependentReplicateMetrics was using a non-optimized query which led to be slow runtimes...this significantly improves runtime, enables running on single-ended reads and also makes the code little nicer.
----
> Yf optimize query for independent replicate metrics

- src/main/java/picard/analysis/CollectMultipleMetrics.java
- src/main/java/picard/analysis/SinglePassSamProgram.java
- src/main/java/picard/cmdline/argumentcollections/EmptyOutputArgumentCollection.java
- src/main/java/picard/cmdline/argumentcollections/OptionalReferenceArgumentCollection.java
- src/main/java/picard/cmdline/argumentcollections/OutputArgumentCollection.java
- src/main/java/picard/cmdline/argumentcollections/ReferenceArgumentCollection.java
- src/main/java/picard/cmdline/argumentcollections/RequiredOutputArgumentCollection.java
- src/main/java/picard/cmdline/argumentcollections/RequiredReferenceArgumentCollection.java
- src/main/java/picard/sam/markduplicates/CollectDuplicateMetrics.java
- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/MarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/SimpleMarkDuplicatesWithMateCigar.java
- src/main/java/picard/sam/markduplicates/util/AbstractMarkDuplicatesCommandLineProgram.java
- src/test/java/picard/sam/markduplicates/AbstractMarkDuplicatesCommandLineProgramTester.java
- src/test/java/picard/sam/markduplicates/AsIsCollectDuplicateMetricsTest.java
- src/test/java/picard/sam/markduplicates/AsIsMarkDuplicatesTest.java
- src/test/java/picard/sam/markduplicates/AsIsMarkDuplicatesTester.java
- src/test/java/picard/sam/markduplicates/CollectDuplicateMetricsTest.java
- src/test/java/picard/sam/markduplicates/CollectDuplicateMetricsTester.java
- src/test/java/picard/sam/testers/SamFileTester.java
A CLP to collect MarkDuplicate Metrics on a file that already has had its duplicate marked. Useful when you want to have the duplicate metrics of a file but do not want to re-preprocess it. Does NOT calculate OPTICAL_DUPLICATES.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't …
> Yf collect duplicate metrics

- src/main/java/picard/fingerprint/CheckFingerprint.java
A change was introduced last year to `CheckFingerprint` which made it only add a period to the end of the `OUTPUT` argument if it did not already end with a period. This causes errors in our pipeline when sample aliases end in a period, because we derive our cromwell outputs based on the sample alias concatenated with "fingerprinting_summary_metrics" and "fingerprinting_detail_metrics". If sample_alias is `MyCoolSampleG.T.`, the output files should be `MyCoolSampleG.T..fingerprinting_summary_metrics` and `MyCoolSampleG.T..fingerprinting_detail_metrics`
----
For more …
> Don't not add a period to output basenames

- .travis.yml
- README.md
- build.gradle
Changes to the build.gradle to support building on java 11.  This involved relaxing checks for java 8 being installed, as well as some changes to how javadoc is run because the location of doclet code has changed between 8 and 11.
A minor additional change is to understand directories created with git worktree as git directories during the build.
Adding openjdk11 to the test matrix.
----
> Getting things to compile on 11

- src/main/java/picard/arrays/GtcToVcf.java
We want to continue not having comma separators in Floats in GtcToVcf, but we still want to round the decimal to 3 places. This means re-adding the DecimalFormat, but setting it to not group the places.
----
> Re-add DecimalFormat, but get rid of comma

- src/main/java/picard/util/LiftOverIntervalList.java
Corrected LiftOverIntervalList documentation error that states that it works for VCFs.
@yfarjoun Could you kindly review this?
> Corrected LiftOverIntervalList documentation

- src/main/java/picard/fingerprint/Fingerprint.java
- src/main/java/picard/fingerprint/HaplotypeBlock.java
- src/main/java/picard/fingerprint/HaplotypeProbabilities.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromContaminatorSequence.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromGenotype.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromGenotypeLikelihoods.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromSequence.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesUsingLogLikelihoods.java
- src/main/java/picard/fingerprint/HaplotypeProbabilityOfNormalGivenTumor.java
- src/test/java/picard/fingerprint/CrosscheckFingerprintsTest.java
- src/test/java/picard/fingerprint/CrosscheckReadGroupFingerprintsTest.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- src/test/java/picard/fingerprint/FingerprintingTestUtils.java
- src/test/java/picard/fingerprint/HaplotypeProbabilitiesTest.java
- src/test/java/picard/util/MiscTest.java
The original list of fingerprints leading to incorrect results in the self-LOD case when using Crosscheck without SECOND_INPUT.
HT: David Wine and David Loginov for reporting.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but …
> Fixed a bug where the merging of fingerprints changes

- src/main/java/picard/arrays/illumina/CompareGtcFiles.java
- src/main/java/picard/arrays/illumina/InfiniumGTCFile.java
Fixed two problems in CompareGtcFiles
1) Minor typo in list of excluded methods
2) Added back a bunch of getters in InfiniumGTCFile to allow for CompareGtcFiles to compare their values.
----
> Fixed two problems in CompareGtcFiles

- src/main/java/picard/analysis/CompareMetrics.java
- src/test/java/picard/analysis/CompareMetricsTest.java
Have CompareMetrics consider two NaN metrics equal
----
> GL-970.  Have CompareMetrics consider two NaN metrics equal

- src/main/java/picard/sam/AbstractAlignmentMerger.java
* Someone on the forum reported an issue with a bam tag that was a long string instead of 2 characters.  This is a fix, but not a test because i'm not sure how to build a bam that triggers isContaminant.
----
> Fix for corrupted CO tag issue

- src/main/java/picard/sam/RevertSam.java
- src/test/java/picard/sam/RevertSamTest.java
> Change default in RevertSam for restoring hard-clips to true

- build.gradle
Update to htsjdk 2.22.0.  This release includes a rewrite of the CRAM code which improves performance and fixes many issues.  
> Update htsjdk to 2.22.0:

- src/main/java/picard/fingerprint/CappedHaplotypeProbabilities.java
- src/main/java/picard/fingerprint/CrosscheckFingerprints.java
- src/main/java/picard/fingerprint/ExtractFingerprint.java
- src/main/java/picard/fingerprint/Fingerprint.java
- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/main/java/picard/fingerprint/FingerprintUtils.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromContaminatorSequence.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesUsingLogLikelihoods.java
- src/main/java/picard/fingerprint/IdentifyContaminant.java
- src/main/java/picard/fingerprint/MatchResults.java
- src/main/java/picard/util/MathUtil.java
- src/test/java/picard/fingerprint/CheckFingerprintTest.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- src/test/java/picard/util/MathUtilTest.java
- testdata/picard/fingerprint/fingerprinting_summary_metrics.example
- IdentifyContamiant wrote an incorrect VCF (gasp!) when the minor allele in the haplotype_map matches the reference (as opposed tot he major allele). This PR fixes that. (with a test too!)
- IdentifyContaminant can also be used to simply extract the fingerprint (in VCF format) from a bam. I've created a new CLP called ExtractFingerprint that does essentially the same as IdentifyContaminant but with the opposite intent (extracting a fingerprint for the intended sample as opposed to the contaminating sample)
- The fingerprinting code couldn't function when reads don't have an RG tag, but a lot of data in the wild misses the RG tag and so this PR also enables the user to work with these non-compliant inputs.
- Another bug was found in the Tumor-aware part of the code..fixed in this PR
> Bugfix for IdentifyContamiant + small improvements to Fingerprinting

- build.gradle
Most changes in this Barclay release only affect the new command line parser. However, it does contain some new annotations that can be used to target Picard tools for GATK [WDL auto-gen](https://github.com/broadinstitute/gatk/wiki/How-to-Prepare-a-GATK-tool-for-WDL-auto-generation) once https://github.com/broadinstitute/gatk/pull/6504 goes in.
> Upgrade to Barclay 3.0.0.

- src/main/java/picard/sam/MergeBamAlignment.java
Discovered by running autogenerated tests for autogenerated WDL - MergeBamAlignment MATCHING_DICTIONARY_TAGS is currently initialized to a list that cannot be mutated by the CLP.
> Use a mutable list to initialize MergeBamAlignment MATCHING_DICTIONARY_TAGS arg.

- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- testdata/picard/fingerprint/aligned_unsorted.sam
- fix fingerprintChecker test
- make sure that fingerprint checker fails on sam file with "unsorted" sort order if it fails to find any information.
- add test.
- add logging to inform whether (sam) file is being read using an index or not.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist …
> Make Fingerprint checking fail when run on a truly unsorted file (currently it returns a non-informative fingerprint)

- src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java
In the recently added read-length histogram & chart (added to AlignmentSummaryMetrics) there was a typo in the histogram label and the plot. 
This PR fixes both and refactors out the repetitive part that was responsible for the typo.
> Yf fix typo in histogram column name asm

- src/main/java/picard/sam/AbstractAlignmentMerger.java
- src/main/java/picard/sam/MergeBamAlignment.java
- src/test/java/picard/sam/AbstractAlignmentMergerTest.java
It has been noted in #1569 that #1484 changed the behavior of MBA when soft clipping overhanging reads.  This PR reverts the behavior when soft clipping so that it is the same as "old" (pre #1484) MBA.  The behavior when hard clipping is also adjusted slightly.  The behavior implemented here is as follows:
1. overlapping reads are soft clipped so that the 3' aligned end does not extend past the 5' aligned end of the mate. This reverts to the "old" MBA behavior when soft clipping
2. if using hard clipping, reads are additionally hard clipped so that the 3' unclipped end of the read does not extend past the 5' unclipped end of the mate. This implements the "new" MBA behavior when hard clipping.
The result of this behavior is that:
- When running in soft clipping mode, the results are …
> Adjust MBA read overhang clipping to be consistent with past behavior

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/main/java/picard/sam/DownsampleSam.java
- src/test/java/picard/sam/DownsampleSamTest.java
If DownsampleSam is run twice on the same file, the results can end up being incorrect.  This is because the ConstantMemory and Chained strategies both employ a hash based sampling which is initialized with a random seed.  If the seed used in two runs is the same, then the hashes associated with each read pair will be the same.   
As an example of the problem this causes, consider a case where we have Downsampled with the ConstantMemory strategy and a probability of 0.5.  What this means is that a hash is calculated for each read pair, and the hashes are (with appropriate normalization) uniformly distributed between 0 and 1.  All read pairs which hash to values less than 0.5 will pass the downsampling and be included in the output.  We now attempt to downsample the output a second time …
> Safely run DownsampleSam multiple times

- src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java
There was a buggy interaction between CollectMultipleMetrics and CollectAlignmentSummaryMetrics with regards to the collection and emission of the read-length histogram. This PR fixes it.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it …
> Fix CollectMultipleMetrics -- CollectAlignmentSummaryMetrics interaction

- src/main/java/picard/analysis/CollectWgsMetrics.java
- src/test/java/picard/analysis/CollectWgsMetricsTest.java
When a user passes in a reference sequence and an input bam that don't have the same sequence dictionary in `CollectWgsMetrics`, they get an `ArrayIndexOutOfBoundsException`. This is uninformative to the user so it was requested to create a clear error message in this issue: #366 
Changes Made:
- Throw an error in `CollectWgsMetrics` when the sequence dictionaries don't match
- Add a unit test to cover this case
> Check Sequence Dictionaries Match in CollectWgsMetrics

- src/main/java/picard/sam/util/SAMComparisonArgumentCollection.java
- src/main/java/picard/sam/util/SamComparison.java
- src/test/java/picard/sam/CompareSAMsTest.java
- If the argument OUTPUT_MQ_CONCORDANCE is provided, CompareSAMs will produce a histogram that reflects concordance of mapping qualities between two alignment files.
- Added separate tests for all CompareSAM test cases to check the mapping quality concordance.
----
> Add optional mapping quality concordance feature to CompareSAMs

- Dockerfile
The trivvy security check failed, flagging issues with the openjdk:8 docker image we are using for a base.  This PR updates this to adoptopenjdk:8
----
> Change docker base image for security reasons.

- build.gradle
This update to the newest htsjdk 2.24.1 release which fixes several bugs including one introduced in 2.24.0 which caused htsjdk to list JUNIT as a dependency.  
> Update to htsjdk 2.24.1

- src/main/java/picard/illumina/ExtractIlluminaBarcodes.java
The threaded pool executors for `ExtractIlluminaBarcode` never actually checks to see if there was an error. This would cause the run to incorrectly return success when in fact one more more of the extractor threads may have had an error.
----
> Throw an exception if one of the pooled threads has an error.

- src/main/java/picard/illumina/IlluminaBasecallsToFastq.java
- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
If an invalid directory was provided to IlluminaBasecallsTo[Sam|Fastq] the resultant error was uninformative.
This PR changes the behavior to have the program report a more useful error message.
----
> Add validation of existence of input directories

- src/main/java/picard/illumina/CheckIlluminaDirectory.java
- src/main/java/picard/illumina/parser/NewIlluminaDataProvider.java
- src/test/java/picard/illumina/ExtractIlluminaBarcodesTest.java
ExtractIlluminaBarcodes is throwing an Ecxception in which it reports it can't find any barcode files in the basecalling directory.  This bug was introduced when we fixed another bug in IlluminaBasecallsToSam.  The issue here is that the NewIlluminaDataProvider is used by both tools, and the case where it's used by ExtractIlluminaBarcodes, it is perfectly valid that there are no barcode files found there.
This PR removes the exception that was thrown in this case.
----
For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-reques …
> NewIlluminaDataProvider should allow for no barcode files found in the basecalling directory

- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
- src/main/java/picard/illumina/SortedBasecallsConverter.java
`MAX_RECORDS_IN_RAM` was not being passed to the `BasecallsConvereter` in `IlluminaBasecallsToSam`.  Prior to this fix it would have always been set to default.
Also the deprecated `MAX_RECORDS_IN_RAM_PER_TILE` should be multiplied by the number of tile processing threads.
Additionally, we set the writer threads to numThreads instead of the number of samples (to avoid oversubscribing threads when there is high plexity)
----
> [bugfix] Pass MAX_RECORDS_IN_RAM to BasecallsConverter

- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
- src/main/java/picard/illumina/SortedBasecallsConverter.java
- src/main/java/picard/util/ThreadPoolExecutorWithExceptions.java
Thread pool executors often say they are done when in fact there is lingering processing being done in a worker thread. This causes issues with race conditions when tile data is tiny (unit tests)
The performance hit is negligible for using a different pool for each tile and then shutting it down and cleaning it up to ensure that a race condition can not occur.
----
> Jc fix small data race condition

- src/main/java/picard/fingerprint/CalculateFingerprintMetrics.java
- src/main/java/picard/fingerprint/ExtractFingerprint.java
- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/main/java/picard/fingerprint/FingerprintUtils.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromContaminatorSequence.java
- src/main/java/picard/fingerprint/IdentifyContaminant.java
- src/main/java/picard/util/MathUtil.java
feat: Enable NIO access for three other CLPs (ExtractFingerprint, CalculateContamination, and CalculateFingerprintMetrics).
fix: A bug in ExtractFingerprint & CalculateContamination were in the resulting vcf the REF and ALT allele counts in AD were swaped (doesn't affect LOD scores since the downstream tools only looked at PL) 😌 
(https://www.conventionalcommits.org/en/v1.0.0/)
> bugfix and nio access in Fingerprinting code (no need to panic)

- src/main/java/picard/fingerprint/FingerprintUtils.java
- src/main/java/picard/fingerprint/HaplotypeProbabilitiesFromContaminatorSequence.java
- src/test/java/picard/fingerprint/FingerprintCheckerTest.java
- src/test/java/picard/util/TestNGUtil.java
This PR fixes an underflow (reported to me in private by @sidwekhande) which affects both IdentifyContamination and ExtractFingerprint in deep coverage. This was leading to non-informative sites in RNA and similar sequencing data.
The problem was that internally the code was using linear likelihood to collect the information about the possible combinations of contamination and this quickly led to underflows. 
Here I added tests (that initially failed!) and moved the entire calculation to log10 space.
> fix: underflow in HaplotypeProbabilitiesFromContaminatorSequence

- src/main/java/picard/analysis/AlignmentSummaryMetrics.java
- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/test/java/picard/analysis/AlignmentSummaryMetricsCollectorTest.java
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
Added some other statistics relating to the read lengths, with documentation and tests. 
----
> Added read length statistics

- src/main/java/picard/analysis/AlignmentSummaryMetrics.java
- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
This small revision reorders some declarations/methods for consistency across classes, as well as using a better naming convention for the longer variable names (e.g. STANDARD_DEVIATION -> SD_READ_LENGTH). 
----
> Cleaned up some variable names and order in the alignment metrics code.

- LICENSE.txt
- README.md
I noticed some links pointed to old Sourceforge pages that are described as outdated. I tried to find the best current equivalent of that URL and updated the README to link directly to them. I also noticed a few spots using HTTP when HTTPS is supported, so switched those over. 
The goal is to make the README and License more useful and accurate.
----
> Minor updates: https, new urls, license year

- src/main/java/picard/arrays/illumina/CompareGtcFiles.java
Updated CompareGtcFiles to do an up-front existence check for the Illumina bead pool manifest (.bpm) file.
----
> Added validation for existence of .bpm file to CompareGtcFiles

- src/main/java/picard/illumina/IlluminaBasecallsToFastq.java
- src/main/java/picard/illumina/IlluminaBasecallsToSam.java
- src/test/java/picard/illumina/IlluminaBasecallsToFastqTest.java
Recently, the parameter 'ADAPTERS_TO_CHECK' in IlluminaBasecallsToFastq was set to be on (trim known adapter sequence from output fastq files). After further discussion, it was decided to leave this parameter off by default in order to prevent unexpected changes in output data.
----
> Set ADAPTERS_TO_CHECK to be null by default

- .travis.yml
- build.gradle
I noticed that running `/gradlew picardDoc` crashes on java 11.  This seems to be happening because of a mixup between the gradle daemon working directory and the project working directory.  Files were being creating using `new File()` in the `build.gradle` and not the `file()` function which accounts for this discrepancy.  
See [this build](https://app.travis-ci.com/github/broadinstitute/picard/builds/241886299) to see how it fails on 11 when you run `./gradlew` 
The following commit fixes it. …
> Fix picard doc on java 11

- .travis.yml
- build.gradle
This PR changes the jar packaging to be multi-release.  This addresses the issues surfaced with the upgrade to gkl 0.8.8
----
> Make the shadowJar multi-release.

- src/test/java/picard/illumina/IlluminaBasecallsToSamTest.java
This PR fixes a data type mismatch in the IlluminaBasecallsToSamTest.
fix provided by pgrt.
----
> Gg pgrt fix illumina basecalls to sam test

- src/main/java/picard/vcf/GatherVcfs.java
This very very short PR clarifies the purpose of the `GatherVcfs` tool, changing the phrase "totally discrete" to the more accurate "nonoverlapping." Compare with the Picard documentation [here](https://broadinstitute.github.io/picard/command-line-overview.html#GatherVcfs) to see this is the intended purpose. The reason this confused me a bit was that technically you could have two vcfs with discrete sets of intervals which _do_ overlap (e.g. chr1:100-101 + chr2:100-101 and chr1:100-101 + chr3:100-101), which certainly should not be used as input into this tool. Changing it here should eventually change the corresponding text on the [GATK documentation](https://gatk.broadinstitute.org/hc/en-us/articles/360037422071-GatherVcfs-Picard-) page as well, once it's incorporated into GATK. 
---- …
> Clarified comment for purpose of GatherVcfs

- build.gradle
Looks like we never upgraded Picard to Barclay 4.0. This change upgrades to Barclay 4.02, which version uses the log4j 2.15.
> Upgrade Barclay.

- build.gradle
This PR updates Picard to Log4J 2.16.0. 
Previously was at 2.15.0 but that was found to be an incomplete solution to 
CVE-2021-44228
----
> Update Picard to Log4J 2.16.0

- build.gradle
Previously was at 2.17.0 but that was found to potentially allow remote code execution (RCE) using the JDBC Appender if the attacker is able to control the Log4j logging configuration file. The issue has been given a “Moderate” severity rating, lower than the vulnerability that started it all
----
Never delete this, it is our record that procedure was followed. If you …
> Update log4j to v2.17.1

- src/main/java/picard/util/ThreadPoolExecutorUtil.java
If a worker thread has an exception, the program is going to fail.  However, the ThreadPoolExecutor continues to execute the other workers, which can take quite a while.  See #1770.  
To fix, check for failed worker threads in the code that reports on thread pool progress every 5 minutes.
----
> Detect worker thread exception sooner, and stop other workers.

- src/main/java/picard/arrays/GtcToVcf.java
- src/main/java/picard/arrays/VcfToAdpc.java
https://broadinstitute.atlassian.net/browse/GL-1941
In GtcToVcf, set infinite values to missing ('.') in the VCF.
In VcfToAdpc, if value is a '?' (which was what had been encoded for infinite) treat as missing.
----
> GL-1941. Handle Out of Range Values in GTC metrics

- src/main/java/picard/nio/PicardHtsPath.java
- src/main/java/picard/sam/BuildBamIndex.java
- src/main/java/picard/util/DbSnpBitSetUtil.java
- src/main/java/picard/vcf/AccumulateVariantCallingMetrics.java
- src/main/java/picard/vcf/CollectVariantCallingMetrics.java
- src/main/java/picard/vcf/FixVcfHeader.java
- src/main/java/picard/vcf/GatherVcfs.java
- src/main/java/picard/vcf/GenotypeConcordance.java
- src/main/java/picard/vcf/MergeVcfs.java
- src/main/java/picard/vcf/SplitVcfs.java
- src/main/java/picard/vcf/processor/VariantIteratorProducer.java
- src/main/java/picard/vcf/processor/VariantProcessor.java
- src/main/java/picard/vcf/processor/VcfFileSegment.java
- src/main/java/picard/vcf/processor/VcfFileSegmentGenerator.java
- src/main/java/picard/vcf/processor/VcfPathSegment.java
- src/main/java/picard/vcf/processor/VcfPathSegmentGenerator.java
- src/test/java/picard/sam/BuildBamIndexTest.java
- src/test/java/picard/vcf/AccumulateVariantCallingMetricsTest.java
- src/test/java/picard/vcf/CollectVariantCallingMetricsTest.java
- src/test/java/picard/vcf/FixVcfHeaderTest.java
- src/test/java/picard/vcf/GatherVcfsTest.java
- src/test/java/picard/vcf/GenotypeConcordanceGA4GHSchemeTest.java
- src/test/java/picard/vcf/GenotypeConcordanceGA4GHSchemeWithMissingTest.java
- src/test/java/picard/vcf/GenotypeConcordanceTest.java
- src/test/java/picard/vcf/MergeVcfsTest.java
- src/test/java/picard/vcf/SplitVcfsTest.java
- src/test/java/picard/vcf/VcfTestUtils.java
- src/test/java/picard/vcf/processor/ThreadsafeTest.java
- src/test/java/picard/vcf/processor/VcfPathSegmentGeneratorTest.java
Changed to treat all input as a `Path` and use `IOUtil` to choose the path type so that paths with schemes handled by SPI providers are correctly handled as well as paths that have no scheme and are local files.
----
> Simplify handling of paths for input in BuildBamIndex.java

- build.gradle
- src/main/java/picard/nio/GoogleStorageUtils.java
This upgrade the google-cloud-nio version to match the one that GATK is using (well, the one gatk is moving too).  It also switches from using the shaded version -> standard version.  We initially used the shaded version because of horrible downstream dependency issues in GATK, but those have been resolved so we can switch to the unshaded version now.  
When using the shaded version we ignored transitive dependencies since the actual dependencies were included in the shaded jar and the transitive ones imported additional unnecessary things.  Switching to unshaded means we need the transitive ones.  
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but …
> Upgrade google-cloud-nio to fix broken requester pays support

- build.gradle
- src/main/java/picard/util/SequenceDictionaryUtils.java
- src/test/java/picard/analysis/artifacts/CollectSequencingArtifactMetricsTest.java
- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
- src/test/java/picard/analysis/replicates/CollectIndependentReplicatesMetricTest.java
- src/test/java/picard/fastq/BamToBfqTest.java
- src/test/java/picard/illumina/CheckIlluminaDirectoryTest.java
- src/test/java/picard/illumina/IlluminaLaneMetricsCollectorTest.java
- src/test/java/picard/illumina/parser/BclParserTest.java
- src/test/java/picard/illumina/parser/IlluminaFileUtilTest.java
- src/test/java/picard/sam/CramCompatibilityTest.java
- src/test/java/picard/sam/DownsampleSamTest.java
- src/test/java/picard/sam/PositionBasedDownsampleSamTest.java
- src/test/java/picard/sam/SamErrorMetric/CollectSamErrorMetricsTest.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesTest.java
- src/test/java/picard/sam/testers/SamFileTester.java
- src/test/java/picard/util/IntervalListToolsTest.java
- src/test/java/picard/util/LiftoverVcfTest.java
- src/test/java/picard/vcf/GenotypeConcordanceTest.java
- src/test/java/picard/vcf/SplitVcfsTest.java
- src/test/java/picard/vcf/UpdateVcfSequenceDictionaryTest.java
- testdata/picard/sam/smallIntervals.interval_list
~- [ ] Added or modified tests to cover changes and any new functionality~
~- [ ] Edited the README / documentation (if applicable)~
> Update htsjdk to 3.0.1

- src/main/java/picard/vcf/LiftoverVcf.java
* One of the filters that LiftoverVcf outputs was misspelled:  Should be "Intervals" instead of "Intevals" IndelStraddlesMultipleIntevals -> IndelStraddlesMultipleIntervals 
* fixes https://github.com/broadinstitute/picard/issues/1841
> Fix typo in a filter name output by LiftoverVcf

- src/main/java/picard/analysis/CollectMultipleMetrics.java
- src/main/java/picard/fingerprint/CheckFingerprint.java
`CollectMultipleMetrics` currently strips a trailing period from the `OUTPUT` parameter. This behavior is unexpected and causes problems in our cloud pipelines. Metrics files, by convention, are names `${sample_alias}.${metrics_suffix}`. In removing a trailing `.` from the `OUTPUT`, `CollectMultipleMetrics` writes unexpected file names, causing problems when our cloud pipelines try to delocalize files. When supplied an `OUTPUT` of `foo.bar.`, the resulting metrics files should look like `foo.bar..pre_adapter_detail_metrics`. This is still a valid path in all filesystems.
----
Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation …
> Stop removing periods from the end of output names

- build.gradle
- src/main/java/picard/arrays/CollectArraysVariantCallingMetrics.java
- src/main/java/picard/arrays/GtcToVcf.java
- src/main/java/picard/arrays/VcfToAdpc.java
- src/main/java/picard/arrays/illumina/Build37ExtendedIlluminaManifest.java
- src/main/java/picard/arrays/illumina/Build37ExtendedIlluminaManifestRecord.java
- src/main/java/picard/arrays/illumina/CreateExtendedIlluminaManifest.java
- src/main/java/picard/arrays/illumina/IlluminaManifestRecord.java
- src/main/java/picard/fingerprint/FingerprintUtils.java
- src/main/java/picard/illumina/parser/IlluminaFileUtil.java
I noticed that we have both commons lang and lang3.  I removed all lang uses so we only need lang3 now.
The only thing that might change for users is replacing a deprecated `NotImplementedException` with the standard  `UnsupportedOperationException`
> Remove commons.lang dependency because it is redundant with commons lang3

- src/main/java/picard/cmdline/CommandLineProgram.java
* The Google Genomics API was turned off years ago. This removes a global argument (GA4GH_CLIENT_SECRETS) which was used with it and several initialization steps in CommandLineProgram which are no longer meaningful.
> Remove obsolete references to Google Genomics API

- src/main/java/picard/analysis/CollectAlignmentSummaryMetrics.java
- src/main/java/picard/sam/FastqToSam.java
- src/main/resources/picard/analysis/readLengthDistribution.R
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
- src/test/java/picard/sam/FastqToSamTest.java
- testdata/picard/sam/AlignmentSummaryMetrics/summary_alignment_stats_test_empty.sam
Currently, if input files to the tools have 0 reads, various exceptions are thrown by CollectAlignmentSummaryMetrics and FastqToSam.  This PR adds an option to allow FastqToSam to produce an empty Sam when passed an empty fastq instead of throwing an exception, and does not try to plot readlength distribution in CollectAlignmentSummaryMetrics when there are 0 reads (which currently hits an r error).
> Allow empty input files for CollectAlignmentSummaryMetrics and FastqToSam

- src/main/java/picard/fingerprint/Fingerprint.java
Deleting an unused and untested method that was last modified in 2016.    Noticed this when rebasing #1826 
I'm under the impression that picard doesn't intend to act as a stable api for downstream projects so we're free to delete locally unused public methods?
> Remove unused method Fingerprint.filterSuspectSites()

- src/main/java/picard/analysis/AlignmentSummaryMetricsCollector.java
- src/test/java/picard/analysis/CollectAlignmentSummaryMetricsTest.java
- testdata/picard/sam/AlignmentSummaryMetrics/null.sam
----
Create a (mostly) empty metrics file instead of giving a stacktrace if no reads pass Illumina filters.
Related to the following issue: https://github.com/broadinstitute/picard/issues/1862
----
> Fix crash on PF_READS == 0 for AlignmentSummaryMetricsCollector

- src/main/java/picard/analysis/CollectOxoGMetrics.java
- src/main/java/picard/analysis/CollectWgsMetrics.java
- src/main/java/picard/analysis/SinglePassSamProgram.java
- src/main/java/picard/analysis/directed/CollectTargetedMetrics.java
- src/main/java/picard/analysis/replicates/CollectIndependentReplicateMetrics.java
- src/main/java/picard/fingerprint/CheckFingerprint.java
- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/main/java/picard/reference/ExtractSequences.java
- src/main/java/picard/util/BaitDesigner.java
- src/main/java/picard/util/SequenceDictionaryUtils.java
- src/main/java/picard/vcf/GenotypeConcordance.java
- src/test/java/picard/analysis/CollectWgsMetricsTest.java
- src/test/java/picard/util/SequenceDictionaryUtilsTest.java
Addresses common complaint about opaque error messages when sequence dictionaries don't match, by specifying which files the mismatched sequence dictionaries are coming from.  
A recent example of this issue is #1869
> More informative error messages when dictionaries don't match

- src/main/java/picard/cmdline/CommandLineProgram.java
- src/test/java/picard/IntelInflaterDeflaterLoadTest.java
Fixes a long standing bug where we were accidentally not using the intel inflator when decompressing even when it was requested.  Includes a horrible test using brittle reflection.
> Enable IntelInflater

- src/main/java/picard/cmdline/PicardCommandLine.java
- src/main/java/picard/sam/MergeBamAlignment.java
- src/test/java/picard/TestDataProviders.java
- src/test/java/picard/cmdline/PicardCommandLineTest.java
- src/test/java/picard/sam/CramCompatibilityTest.java
Replace instances of `newInstance()`  which is deprecated with `getDeclaredConstructor().newInstance()` which is the drop in replacement.
> Fix deprecated uses of newInstance()

- src/main/java/picard/sam/FastqToSam.java
- Issue #1081 raised that help message for FastqToSam.java's --USE_SEQUENTIAL_FASTQS was not very intuititive.  When I used this tool for the first time today, I also found the documentation confusing.  Therefore, I made a PR.
- Updated help message with more explicit usage (specific text on how to use the option and example commands).
> Fix #1081. Make --USE_SEQUENTIAL_FASTQS help message more user friendly

- build.gradle
> Fix the dependency issue causing dsp-appsec-trivy workflow to fail.

- build.gradle
Remove the cloud jar and make google cloud dependencies part of the standard release.
> make cloud jar mandatory

- src/main/java/picard/nio/DeleteRecursive.java
- src/main/java/picard/nio/GATKBucketUtils.java
- src/main/java/picard/nio/GATKIOUtils.java
- src/main/java/picard/nio/GATKUtils.java
- src/main/java/picard/util/IntervalListTools.java
- src/test/java/picard/util/IntervalListToolsTest.java
- Update Files to PicardHTSPath to support files stored in the cloud
Also see #1804. 
----
> Support cloud input/output for IntervalListTools

- src/main/java/picard/illumina/parser/readers/FilterFileReader.java
This corrects a typo encountered while working with a sequencing run containing a corrupt cluster filter file.
`FilterFileReader.java`:
"Didn't recogniz**ed** PF Byte" -> "Didn't recognize PF Byte"
----
> typo correction "Didn't recognized" -> "Didn't recognize"

- build.gradle
Fixes `gradle publish` after changes in #1903
----
> Fix gradle 8 publishing issue

- src/main/java/picard/nio/PicardHtsPath.java
- src/main/java/picard/sam/FastqToSam.java
- src/test/java/picard/sam/FastqToSamTest.java
Allow `FastqToSam` to take input from stdin or a named pipe.
* If input is not a regular file, don't autodetect the quality format, and use the same opened reader throughout.
* If input is not a regular file and `QUALITY_FORMAT` is not specified, that's an argument validation error.
Addresses #915
----
> FastqToSam stdin fix for #915

- src/main/java/picard/fingerprint/CrosscheckFingerprints.java
Issue: CrosscheckFingerprints produces results in a different order each time. 
Change: Switched from HashMap and HashSet to Java's LinkedHashMap and LinkedHashSet, respectively
Intended result: Produce stable sorted output.
Issue: https://github.com/broadinstitute/picard/issues/1854
> Changed CrosscheckFingerprints hashing to linked hashing

- Dockerfile
- build_push_docker.sh
Removing the cloud jar broke the `Dockerfile` and `build_push_docker.sh` 
* Rewrote the docker file to use staged builds
this reduces the build size from about 1.7gb to about 650mb
* Properly set the build version so it's not listed as a 'snapshot'
> Update Dockerfile and build_push_docker.sh

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
> MarkDuplicates: Add read group ID instead of string "RG"

- build.gradle
- src/main/java/picard/nio/DeleteRecursive.java
Use the 'java-library' plugin instead of the 'java' one.  This should improve our dependency resolution for downstream projects.
As part of this change, remove picard dependency on log4j and replace it with a version constraint so that transitive dependencies don't import a vulnerable version.
I don't have any automatic tooling to distinguish api from implementation dependencies so this is a best effort.  We should be ready to change any if we are exposing some that we don't expect.
Addresses the issue brought up in https://github.com/broadinstitute/picard/pull/1919, however we've made the deliberate decision to include the minimum required dependencies instead of marking them all as api.
> Convert to use the java-library plugin

- .gitignore
- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/sam/markduplicates/MarkDuplicatesForFlowArgumentCollection.java
- src/main/java/picard/sam/markduplicates/MarkDuplicatesForFlowHelper.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesForFlowHelperTest.java
1. We found that when the duplication rate is very high, we sometimes also get variability at the start position (although usually it is more precise than the end position). In this version we added a parameter that also allows for an uncertainty in the read start position to be counted as duplicate. We introduced a parameter `UNPAIRED_START_UNCERTAINTY` in flow mode. 
2. When duplication rate is very high for large cluster of reads when all reads (start,end) are (A,B) we will sometimes get read with (start,end) at (A-1,B). In the default configuration, we will select the read with the best quality sum over all the reads. However, we found that if it is desirable to select read that starts and ends on (A,B) it is better to only look at the qualities close to the end. We thus introduced a …
> MarkDuplicates strategy of flow based reads that looks only at the qualities close to the end of the read

- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
When number of reads in input file is over max value of signed int, the comparator for SortingCollection may return a value with sign opposite to the intended because the comparator calculates difference between two long numbers then down-casts into signed int.
_compareDifference = (int) (lhs.read1IndexInFile - rhs.read1IndexInFile);_
This comparison acts as a tie-score-breaker, so affects best read election among duplicate reads with same score.
Furthermore, because of this, same input file may result in different duplicate read set if run with different Java memory configuration - such as Xmx - which determines number of temp file chunks created by SortingCollection.
It is because order of element insertion into TreeSet which is internally used by SortingCollection for merging temp …
> Fix for order flipping in SortingCollection used for MarkDuplicates

- src/main/java/picard/util/BedToIntervalList.java
- src/test/java/picard/util/BedToIntervalListTest.java
As the title states, reject piped input (/dev/stdin) for BedToIntervalList since it cannot process such input.
> Reject piped input (/dev/stdin) for BedToIntervalList

- src/main/java/picard/fingerprint/FingerprintChecker.java
- src/test/java/picard/fingerprint/CrosscheckFingerprintsTest.java
- testdata/picard/fingerprint/Homo_sapiens_assembly19.haplotype_database.subset.shifted.for.crams.short_dictionary.txt
- testdata/picard/fingerprint/Homo_sapiens_assembly19.haplotype_database.subset.short_dictionary.txt
Despite efforts to the contrary, FingerprintChecker cannot fingerprinting sam files that have a mismatching dictionary from the one stated in the haplotype map (it works for vcfs). This is because when fingerprinting sam files, the SamLocusIterator is given an IntervalList to query, and this IL has a mismatching dictionary which isn't supported.
This PR resolves this by creating a new IL just before querying the Iterator using the proper dictionary.
_Mention any issues fixed, addressed or otherwise related to this pull request, including issue numbers or hard links for issues in other …
> Allow fingerprinting of SAM files that only have a partial dictionary match to the haplotype map

- build.gradle
This release fixes several bugs when using HttpPath resolve methods that have been affecting users. In particular, they were causing issues when trying to construct HTTP URIs for companion files such as fasta/bam indices.
> Update http-nio to 1.1.1

- src/main/java/picard/sam/RevertSam.java
- src/test/java/picard/sam/MergeBamAlignmentTest.java
- src/test/java/picard/sam/PipedDataTest.java
When we cloudify a Picard tool, we change the input and output file types from `FILE` to `PicardHtsPath.` This could trigger a "java.io.IOException: Illegal seek" if the input SAM is piped (/dev/stdin). I believe this is related to a known issue (see samtools/htsjdk#1084, samtools/htsjdk#1077). The workaround is to wrap a Path object in `SamInputResource.of()`, which was put in place in samtools/htsjdk#1124. The tests in PR should safeguard us from inadvertently removing the workaround until a more robust fix can be implemented.
The targeted tools are RevertSam and MergeBamAlignment, both of which are used with piped input in warp pipelines. For example, see
https://github.com/broadinstitute/warp/blob/develop/tasks/broad/UltimaGenomicsWholeGenomeGermlineTasks.wdl …
> Add piped input tests for RevertSam, MergeBamAlignment

- src/main/java/picard/analysis/directed/PanelMetricsBase.java
The metrics `AT_DROPOUT` and `GC_DROPOUT` are calculated in a pretty much identical manner in two different places in Picard. One is `TargetMetricsCollector.java` which will perform this functionality for `CollectHsMetrics.java` if a reference sequence is provided and the other is `GcBiasMetricsCollector.java`. A user has highlighted an inconsistency with the documentation in #1973 . If we look at `GcBiasSummaryMetrics.java`, we see:
```
/**
* Illumina-style AT dropout metric.  Calculated by taking each GC bin independently and calculating
* (%ref_at_gc - %reads_at_gc) and summing all positive values for GC=[0..50].
*/
public double AT_DROPOUT;
/**
* Illumina-style GC dropout metric.  Calculated by taking each GC bin independently and calculating
* (%ref_at_gc - %reads_at_gc) and summing …
```
> Fix documentation for AT_DROPOUT and GC_DROPOUT in PanelMetricsBase.java

- src/main/java/picard/sam/markduplicates/MarkDuplicatesForFlowArgumentCollection.java
- src/main/java/picard/sam/markduplicates/MarkDuplicatesForFlowHelper.java
- src/test/java/picard/sam/markduplicates/MarkDuplicatesForFlowHelperTest.java
> MarkDuplicates flow options now start with FLOW_

- src/main/java/picard/fingerprint/FingerprintChecker.java
when many files are included in a crosscheck and a few of the files contain a problematic dictionary the exception will appear after all the files have been processed, but the error message will not inform the user of the problematic file(s). This change solves that by wrapping the fingerprinting calls in a try/catch and logging an error when this happens. 
Moves the log message above the checkdictionary call and wraps fingerprinting in a try/catch to get an informative error message regarding the name of the file that caused the problem
----
For more detailed guidelines, …
> better error message for crosscheck when dictionary checks fail.

- src/main/java/picard/fingerprint/CalculateFingerprintMetrics.java
- src/main/java/picard/fingerprint/CheckFingerprint.java
- src/main/java/picard/fingerprint/CrosscheckFingerprints.java
- src/main/java/picard/fingerprint/ExtractFingerprint.java
- src/main/java/picard/fingerprint/IdentifyContaminant.java
The link to the HaplotypeMap format was dead, now it's not.
> Update outdated links to HaplotypeMap file format

- src/main/java/picard/sam/markduplicates/EstimateLibraryComplexity.java
- src/main/java/picard/sam/markduplicates/MarkDuplicates.java
- src/main/java/picard/util/SequenceDictionaryUtils.java
The maximum length of a Java array is not exactly `Integer.MAX_VALUE`, but slightly less due to the space taken up by the object header. The exact maximum differs depending on the platform and Java version. This was already accounted for in one instance, but not others. This was causing MarkDuplicates to fail with a Java heap size of slightly less than 1TB when `MAX_RECORDS_IN_RAM` was not specified (and therefore calculated based on the amount of available memory). This commit fixes the other instances and changes the maximum size in the existing instance to `Integer.MAX_VALUE - 32` instead of `Integer.MAX_VALUE - 5` to decrease the likelihood of allocation failures on different Java versions and platforms.
----
Never delete this, it is our record that procedure was followed. If you find …
> Fix failures to allocate arrays with a very large Java heap size

- src/main/java/picard/analysis/directed/HsMetrics.java
closes: #1996
The documentation in HsMetrics class was inaccurate regarding the filtering of reads that go into the PCT_USABLE_BASES_ON_BAIT. It now correctly reflects the fact that the reads/bases that go into this calculation are _not_ unique, i.e. duplicate reads are counted.
----
Never delete this, it is our record that procedure was followed. If you find that for …
> fix: documentation errors in HsMetrics

- src/test/java/picard/analysis/directed/CollectHsMetricsTest.java
* fix for https://github.com/broadinstitute/picard/issues/1987
* This should fix an issue when running tests on debian systems
@pgrt I added your patch + I changed the numbers it's comparing against to doubles.  I suspect that might  be sufficient to fix the issue but I'm not sure exactly why it's happening on your systems so I kept your epsilons too.
> Change test values to doubles and add epsilon in CollectHsMetricsTest
